// Code generated by Tester Agent. DO NOT EDIT.
// Task: agentic-memory processor unit tests (greenfield)
// Builder must make these tests pass without modification.

package teamsmemory_test

import (
	"encoding/json"
	"testing"

	"github.com/c360studio/semstreams/component"
	teamsmemory "github.com/c360studio/semteams/processor/teams-memory"
)

func TestComponent_Meta(t *testing.T) {
	comp := createTestComponent(t)

	meta := comp.Meta()

	if meta.Name != "agentic-memory" {
		t.Errorf("Meta().Name = %s, want agentic-memory", meta.Name)
	}
	if meta.Type != "processor" {
		t.Errorf("Meta().Type = %s, want processor", meta.Type)
	}
	if meta.Description == "" {
		t.Error("Meta().Description should not be empty")
	}
	if meta.Version == "" {
		t.Error("Meta().Version should not be empty")
	}
}

func TestComponent_InputPorts(t *testing.T) {
	comp := createTestComponent(t)

	ports := comp.InputPorts()

	// Should have 3 input ports: compaction_events, hydrate_requests, entity_states
	if len(ports) < 2 {
		t.Fatalf("InputPorts() count = %d, want at least 2", len(ports))
	}

	// Verify ports have correct direction
	for _, port := range ports {
		if port.Direction != component.DirectionInput {
			t.Errorf("Port %s direction = %v, want DirectionInput", port.Name, port.Direction)
		}
	}

	// Find compaction_events port
	var foundCompaction bool
	for _, port := range ports {
		if port.Name == "compaction_events" {
			foundCompaction = true
			if !port.Required {
				t.Error("compaction_events port should be required")
			}
		}
	}
	if !foundCompaction {
		t.Error("Should have compaction_events input port")
	}
}

func TestComponent_OutputPorts(t *testing.T) {
	comp := createTestComponent(t)

	ports := comp.OutputPorts()

	// Should have at least 3 output ports: injected_context, graph_mutations, checkpoint_events
	if len(ports) < 3 {
		t.Fatalf("OutputPorts() count = %d, want at least 3", len(ports))
	}

	// Verify ports have correct direction
	for _, port := range ports {
		if port.Direction != component.DirectionOutput {
			t.Errorf("Port %s direction = %v, want DirectionOutput", port.Name, port.Direction)
		}
	}

	// Find specific output ports
	portNames := make(map[string]bool)
	for _, port := range ports {
		portNames[port.Name] = true
	}

	if !portNames["injected_context"] {
		t.Error("Should have injected_context output port")
	}
	if !portNames["graph_mutations"] {
		t.Error("Should have graph_mutations output port")
	}
}

func TestComponent_ConfigSchema(t *testing.T) {
	comp := createTestComponent(t)

	schema := comp.ConfigSchema()

	// Should have properties
	if len(schema.Properties) == 0 {
		t.Error("ConfigSchema().Properties should not be empty")
	}

	// Verify extraction property exists
	extractionProp, ok := schema.Properties["extraction"]
	if !ok {
		t.Fatal("ConfigSchema() should have 'extraction' property")
	}
	if extractionProp.Type != "object" {
		t.Errorf("extraction property type = %s, want object", extractionProp.Type)
	}

	// Verify hydration property exists
	hydrationProp, ok := schema.Properties["hydration"]
	if !ok {
		t.Fatal("ConfigSchema() should have 'hydration' property")
	}
	if hydrationProp.Type != "object" {
		t.Errorf("hydration property type = %s, want object", hydrationProp.Type)
	}

	// Verify checkpoint property exists
	checkpointProp, ok := schema.Properties["checkpoint"]
	if !ok {
		t.Fatal("ConfigSchema() should have 'checkpoint' property")
	}
	if checkpointProp.Type != "object" {
		t.Errorf("checkpoint property type = %s, want object", checkpointProp.Type)
	}
}

func TestComponent_Health_NotStarted(t *testing.T) {
	comp := createTestComponent(t)

	health := comp.Health()

	if health.Healthy {
		t.Error("Health() should be unhealthy before Start()")
	}
}

func TestNewComponent_ValidConfig(t *testing.T) {
	config := teamsmemory.DefaultConfig()

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil, // Unit test doesn't need real NATS
	}

	comp, err := teamsmemory.NewComponent(rawConfig, deps)
	if err != nil {
		t.Fatalf("NewComponent() failed: %v", err)
	}
	if comp == nil {
		t.Fatal("NewComponent() returned nil component")
	}
}

func TestNewComponent_InvalidConfigJSON(t *testing.T) {
	rawConfig := []byte(`{invalid json}`)

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := teamsmemory.NewComponent(rawConfig, deps)
	if err == nil {
		t.Fatal("NewComponent() should fail with invalid JSON")
	}
	if comp != nil {
		t.Error("NewComponent() should return nil on error")
	}
}

func TestNewComponent_InvalidExtractionConfig(t *testing.T) {
	config := teamsmemory.DefaultConfig()
	config.Extraction.LLMAssisted.TriggerIterationInterval = -1 // Invalid

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := teamsmemory.NewComponent(rawConfig, deps)
	if err == nil {
		t.Fatal("NewComponent() should fail with invalid extraction config")
	}
	if comp != nil {
		t.Error("NewComponent() should return nil on error")
	}
}

func TestNewComponent_InvalidHydrationConfig(t *testing.T) {
	config := teamsmemory.DefaultConfig()
	config.Hydration.PreTask.MaxContextTokens = -100 // Invalid

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := teamsmemory.NewComponent(rawConfig, deps)
	if err == nil {
		t.Fatal("NewComponent() should fail with invalid hydration config")
	}
	if comp != nil {
		t.Error("NewComponent() should return nil on error")
	}
}

func TestNewComponent_InvalidCheckpointConfig(t *testing.T) {
	config := teamsmemory.DefaultConfig()
	config.Checkpoint.RetentionDays = -1 // Invalid

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := teamsmemory.NewComponent(rawConfig, deps)
	if err == nil {
		t.Fatal("NewComponent() should fail with invalid checkpoint config")
	}
	if comp != nil {
		t.Error("NewComponent() should return nil on error")
	}
}

func TestComponent_PortConfiguration(t *testing.T) {
	comp := createTestComponent(t)

	// Verify input port subjects
	inputs := comp.InputPorts()
	for _, port := range inputs {
		if port.Config == nil {
			t.Errorf("Port %s should have config", port.Name)
			continue
		}

		// Check port type
		portType := port.Config.Type()
		if portType == "" {
			t.Errorf("Port %s should have a type", port.Name)
		}
	}

	// Verify output port subjects
	outputs := comp.OutputPorts()
	for _, port := range outputs {
		if port.Config == nil {
			t.Errorf("Port %s should have config", port.Name)
			continue
		}

		// Check port type
		portType := port.Config.Type()
		if portType == "" {
			t.Errorf("Port %s should have a type", port.Name)
		}
	}
}

func TestComponent_DataFlow(t *testing.T) {
	comp := createTestComponent(t)

	// DataFlow should be available even before start
	flow := comp.DataFlow()

	// Should not panic and return valid struct
	if flow.MessagesPerSecond < 0 {
		t.Error("DataFlow().MessagesPerSecond should not be negative")
	}
	if flow.BytesPerSecond < 0 {
		t.Error("DataFlow().BytesPerSecond should not be negative")
	}
	if flow.ErrorRate < 0 {
		t.Error("DataFlow().ErrorRate should not be negative")
	}
}

// createTestComponent creates a minimal component for testing
func createTestComponent(t *testing.T) component.Discoverable {
	config := teamsmemory.DefaultConfig()

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := teamsmemory.NewComponent(rawConfig, deps)
	if err != nil {
		t.Fatalf("NewComponent() failed: %v", err)
	}

	return comp
}
