// Code generated by Tester Agent. DO NOT EDIT.
// Task: agentic-memory component wiring - consumer setup tests (greenfield)
// Builder must make these tests pass without modification.

package teamsmemory_test

import (
	"context"
	"testing"
	"time"

	"github.com/c360studio/semstreams/component"
)

func TestComponent_Start_WithoutNATSClient(t *testing.T) {
	// Component should start successfully even without NATS client (for unit tests)
	comp := createTestComponent(t)
	lc, ok := comp.(component.LifecycleComponent)
	if !ok {
		t.Fatal("Component should implement LifecycleComponent")
	}

	ctx := context.Background()
	err := lc.Start(ctx)
	if err != nil {
		t.Fatalf("Start() with nil NATS client should succeed: %v", err)
	}

	// Verify health reports running
	health := comp.Health()
	if !health.Healthy {
		t.Error("Component should be healthy after Start()")
	}
}

func TestComponent_Start_AlreadyRunning(t *testing.T) {
	comp := createTestComponent(t)
	lc, ok := comp.(component.LifecycleComponent)
	if !ok {
		t.Fatal("Component should implement LifecycleComponent")
	}

	ctx := context.Background()

	// Start first time
	err := lc.Start(ctx)
	if err != nil {
		t.Fatalf("First Start() failed: %v", err)
	}

	// Start second time should fail
	err = lc.Start(ctx)
	if err == nil {
		t.Fatal("Start() should fail when already running")
	}
	if !containsIgnoreCase(err.Error(), "already started") {
		t.Errorf("Start() error = %v, want 'already started' message", err)
	}
}

func TestComponent_Stop_NotRunning(t *testing.T) {
	comp := createTestComponent(t)
	lc, ok := comp.(component.LifecycleComponent)
	if !ok {
		t.Fatal("Component should implement LifecycleComponent")
	}

	// Stop before start should succeed (no-op)
	err := lc.Stop(5 * time.Second)
	if err != nil {
		t.Errorf("Stop() when not running should succeed (no-op): %v", err)
	}
}

func TestComponent_Stop_AfterStart(t *testing.T) {
	comp := createTestComponent(t)
	lc, ok := comp.(component.LifecycleComponent)
	if !ok {
		t.Fatal("Component should implement LifecycleComponent")
	}

	ctx := context.Background()
	err := lc.Start(ctx)
	if err != nil {
		t.Fatalf("Start() failed: %v", err)
	}

	// Stop should succeed
	err = lc.Stop(5 * time.Second)
	if err != nil {
		t.Fatalf("Stop() failed: %v", err)
	}

	// Verify health reports stopped
	health := comp.Health()
	if health.Healthy {
		t.Error("Component should not be healthy after Stop()")
	}
}

func TestComponent_StartStopCycle(t *testing.T) {
	comp := createTestComponent(t)
	lc, ok := comp.(component.LifecycleComponent)
	if !ok {
		t.Fatal("Component should implement LifecycleComponent")
	}

	ctx := context.Background()

	// Start
	err := lc.Start(ctx)
	if err != nil {
		t.Fatalf("Start() failed: %v", err)
	}

	// Stop
	err = lc.Stop(5 * time.Second)
	if err != nil {
		t.Fatalf("Stop() failed: %v", err)
	}

	// Start again should succeed
	err = lc.Start(ctx)
	if err != nil {
		t.Fatalf("Second Start() failed: %v", err)
	}

	// Clean up
	_ = lc.Stop(5 * time.Second)
}

func TestComponent_Initialize(t *testing.T) {
	comp := createTestComponent(t)
	lc, ok := comp.(component.LifecycleComponent)
	if !ok {
		t.Fatal("Component should implement LifecycleComponent")
	}

	// Initialize should not fail
	err := lc.Initialize()
	if err != nil {
		t.Fatalf("Initialize() failed: %v", err)
	}
}

func TestComponent_InputPortTypes(t *testing.T) {
	comp := createTestComponent(t)

	ports := comp.InputPorts()

	// Verify port configurations are correct
	portConfigs := make(map[string]component.Portable)
	for _, port := range ports {
		if port.Config != nil {
			portConfigs[port.Name] = port.Config
		}
	}

	// compaction_events should be JetStream
	if cfg, ok := portConfigs["compaction_events"]; ok {
		if cfg.Type() != "jetstream" {
			t.Errorf("compaction_events port type = %s, want jetstream", cfg.Type())
		}
	}

	// hydrate_requests should be JetStream
	if cfg, ok := portConfigs["hydrate_requests"]; ok {
		if cfg.Type() != "jetstream" {
			t.Errorf("hydrate_requests port type = %s, want jetstream", cfg.Type())
		}
	}

	// entity_states should be kv-watch
	if cfg, ok := portConfigs["entity_states"]; ok {
		portType := cfg.Type()
		if portType != "kv-watch" && portType != "kvwatch" {
			t.Errorf("entity_states port type = %s, want kv-watch or kvwatch", portType)
		}
	}
}

func TestComponent_OutputPortTypes(t *testing.T) {
	comp := createTestComponent(t)

	ports := comp.OutputPorts()

	// Verify port configurations are correct
	portConfigs := make(map[string]component.Portable)
	for _, port := range ports {
		if port.Config != nil {
			portConfigs[port.Name] = port.Config
		}
	}

	// injected_context should be JetStream
	if cfg, ok := portConfigs["injected_context"]; ok {
		if cfg.Type() != "jetstream" {
			t.Errorf("injected_context port type = %s, want jetstream", cfg.Type())
		}
	}

	// graph_mutations should be NATS
	if cfg, ok := portConfigs["graph_mutations"]; ok {
		if cfg.Type() != "nats" {
			t.Errorf("graph_mutations port type = %s, want nats", cfg.Type())
		}
	}

	// checkpoint_events should be NATS
	if cfg, ok := portConfigs["checkpoint_events"]; ok {
		if cfg.Type() != "nats" {
			t.Errorf("checkpoint_events port type = %s, want nats", cfg.Type())
		}
	}
}

func TestComponent_RequiredPorts(t *testing.T) {
	comp := createTestComponent(t)

	inputs := comp.InputPorts()
	outputs := comp.OutputPorts()

	// Check required input ports
	for _, port := range inputs {
		if port.Name == "compaction_events" && !port.Required {
			t.Error("compaction_events port should be required")
		}
	}

	// Check required output ports
	requiredOutputs := map[string]bool{
		"injected_context":  true,
		"graph_mutations":   true,
		"checkpoint_events": true,
	}

	for _, port := range outputs {
		if requiredOutputs[port.Name] && !port.Required {
			t.Errorf("Output port %s should be required", port.Name)
		}
	}
}

func TestComponent_HealthUptime(t *testing.T) {
	comp := createTestComponent(t)
	lc, ok := comp.(component.LifecycleComponent)
	if !ok {
		t.Fatal("Component should implement LifecycleComponent")
	}

	ctx := context.Background()
	err := lc.Start(ctx)
	if err != nil {
		t.Fatalf("Start() failed: %v", err)
	}
	defer lc.Stop(5 * time.Second)

	// Wait a bit to ensure uptime is measurable
	time.Sleep(10 * time.Millisecond)

	health := comp.Health()
	if health.Uptime <= 0 {
		t.Error("Health().Uptime should be positive after Start()")
	}
}

func TestComponent_DataFlowMetrics(t *testing.T) {
	comp := createTestComponent(t)
	lc, ok := comp.(component.LifecycleComponent)
	if !ok {
		t.Fatal("Component should implement LifecycleComponent")
	}

	ctx := context.Background()
	err := lc.Start(ctx)
	if err != nil {
		t.Fatalf("Start() failed: %v", err)
	}
	defer lc.Stop(5 * time.Second)

	// DataFlow should return valid metrics
	flow := comp.DataFlow()

	if flow.ErrorRate < 0 || flow.ErrorRate > 1 {
		t.Errorf("DataFlow().ErrorRate = %f, want 0.0-1.0", flow.ErrorRate)
	}
}
