// Code generated by Tester Agent. DO NOT EDIT.
// Task: Write comprehensive unit tests for graph-anomalies component
// Builder must make these tests pass without modification.

package graphanomalies

import (
	"context"
	"encoding/json"
	"errors"
	"sync"
	"testing"
	"time"

	"github.com/c360/semstreams/component"
	"github.com/c360/semstreams/natsclient"
	"github.com/nats-io/nats.go/jetstream"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Mock KV bucket for testing
type mockKVBucket struct {
	mu         sync.Mutex
	data       map[string][]byte
	putFunc    func(ctx context.Context, key string, value []byte) (uint64, error)
	getFunc    func(ctx context.Context, key string) (jetstream.KeyValueEntry, error)
	deleteFunc func(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error
}

func newMockKVBucket() *mockKVBucket {
	return &mockKVBucket{
		data: make(map[string][]byte),
	}
}

func (m *mockKVBucket) Put(ctx context.Context, key string, value []byte) (uint64, error) {
	if m.putFunc != nil {
		return m.putFunc(ctx, key, value)
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	m.data[key] = value
	return 1, nil
}

func (m *mockKVBucket) Get(ctx context.Context, key string) (jetstream.KeyValueEntry, error) {
	if m.getFunc != nil {
		return m.getFunc(ctx, key)
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if data, exists := m.data[key]; exists {
		return &mockKVEntry{data: data}, nil
	}
	return nil, jetstream.ErrKeyNotFound
}

func (m *mockKVBucket) Delete(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error {
	if m.deleteFunc != nil {
		return m.deleteFunc(ctx, key, opts...)
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.data, key)
	return nil
}

func (m *mockKVBucket) Bucket() string {
	return "MOCK_BUCKET"
}

// Stub methods to satisfy jetstream.KeyValue interface
func (m *mockKVBucket) GetRevision(ctx context.Context, key string, revision uint64) (jetstream.KeyValueEntry, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) PutString(ctx context.Context, key string, value string) (uint64, error) {
	return m.Put(ctx, key, []byte(value))
}

func (m *mockKVBucket) Create(ctx context.Context, key string, value []byte, opts ...jetstream.KVCreateOpt) (uint64, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, exists := m.data[key]; exists {
		return 0, jetstream.ErrKeyExists
	}
	m.data[key] = value
	return 1, nil
}

func (m *mockKVBucket) Update(ctx context.Context, key string, value []byte, revision uint64) (uint64, error) {
	return m.Put(ctx, key, value)
}

func (m *mockKVBucket) Purge(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error {
	return m.Delete(ctx, key, opts...)
}

func (m *mockKVBucket) Watch(ctx context.Context, keys string, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) WatchAll(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) WatchFiltered(ctx context.Context, keys []string, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) Keys(ctx context.Context, opts ...jetstream.WatchOpt) ([]string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	keys := make([]string, 0, len(m.data))
	for k := range m.data {
		keys = append(keys, k)
	}
	return keys, nil
}

func (m *mockKVBucket) ListKeys(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyLister, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) ListKeysFiltered(ctx context.Context, filters ...string) (jetstream.KeyLister, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) History(ctx context.Context, key string, opts ...jetstream.WatchOpt) ([]jetstream.KeyValueEntry, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) PurgeDeletes(ctx context.Context, opts ...jetstream.KVPurgeOpt) error {
	return errors.New("not implemented")
}

func (m *mockKVBucket) Status(ctx context.Context) (jetstream.KeyValueStatus, error) {
	return nil, errors.New("not implemented")
}

// Mock KV entry for testing
type mockKVEntry struct {
	data []byte
}

func (m *mockKVEntry) Key() string                     { return "test-key" }
func (m *mockKVEntry) Value() []byte                   { return m.data }
func (m *mockKVEntry) Revision() uint64                { return 1 }
func (m *mockKVEntry) Created() time.Time              { return time.Now() }
func (m *mockKVEntry) Delta() uint64                   { return 0 }
func (m *mockKVEntry) Operation() jetstream.KeyValueOp { return jetstream.KeyValuePut }
func (m *mockKVEntry) Bucket() string                  { return "MOCK_BUCKET" }

// ====================================================================================
// Config Tests
// ====================================================================================

func TestConfig_Validate_ValidConfig(t *testing.T) {
	tests := []struct {
		name   string
		config Config
	}{
		{
			name: "valid minimal config",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
		},
		{
			name: "valid config with custom values",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  30 * time.Minute,
				PivotCount:       20,
				MaxHopDistance:   15,
				ComputeOnStartup: false,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			assert.NoError(t, err)
		})
	}
}

func TestConfig_Validate_MissingPorts(t *testing.T) {
	tests := []struct {
		name    string
		config  Config
		wantErr bool
	}{
		{
			name: "missing ports config",
			config: Config{
				Ports:            nil,
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
			wantErr: true,
		},
		{
			name: "empty inputs",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
			wantErr: true,
		},
		{
			name: "missing OUTGOING_INDEX input",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
			wantErr: true,
		},
		{
			name: "missing INCOMING_INDEX input",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
			wantErr: true,
		},
		{
			name: "missing STRUCTURAL_INDEX output",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "other", Type: "kv-write", Subject: "OTHER_BUCKET"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

func TestConfig_Validate_InvalidInterval(t *testing.T) {
	tests := []struct {
		name     string
		interval time.Duration
		wantErr  bool
	}{
		{
			name:     "zero interval",
			interval: 0,
			wantErr:  true,
		},
		{
			name:     "negative interval",
			interval: -1 * time.Hour,
			wantErr:  true,
		},
		{
			name:     "valid interval",
			interval: 1 * time.Hour,
			wantErr:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			config := Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  tt.interval,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			}

			err := config.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

func TestConfig_Validate_InvalidPivotCount(t *testing.T) {
	tests := []struct {
		name       string
		pivotCount int
		wantErr    bool
	}{
		{
			name:       "zero pivot count",
			pivotCount: 0,
			wantErr:    true,
		},
		{
			name:       "negative pivot count",
			pivotCount: -5,
			wantErr:    true,
		},
		{
			name:       "valid pivot count",
			pivotCount: 16,
			wantErr:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			config := Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       tt.pivotCount,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			}

			err := config.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

func TestConfig_Validate_InvalidMaxHopDistance(t *testing.T) {
	tests := []struct {
		name           string
		maxHopDistance int
		wantErr        bool
	}{
		{
			name:           "zero max hop distance",
			maxHopDistance: 0,
			wantErr:        true,
		},
		{
			name:           "negative max hop distance",
			maxHopDistance: -10,
			wantErr:        true,
		},
		{
			name:           "valid max hop distance",
			maxHopDistance: 10,
			wantErr:        false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			config := Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   tt.maxHopDistance,
				ComputeOnStartup: true,
			}

			err := config.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

func TestConfig_ApplyDefaults(t *testing.T) {
	config := Config{
		Ports: &component.PortConfig{
			Inputs: []component.PortDefinition{
				{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
				{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
			},
			Outputs: []component.PortDefinition{
				{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
			},
		},
	}

	config.ApplyDefaults()

	// Verify defaults are applied
	assert.Equal(t, 1*time.Hour, config.ComputeInterval, "ComputeInterval should default to 1 hour")
	assert.Equal(t, 16, config.PivotCount, "PivotCount should default to 16")
	assert.Equal(t, 10, config.MaxHopDistance, "MaxHopDistance should default to 10")
	assert.Equal(t, true, config.ComputeOnStartup, "ComputeOnStartup should default to true")
}

func TestDefaultConfig_ReturnsValidConfig(t *testing.T) {
	config := DefaultConfig()

	// Default config should pass validation
	err := config.Validate()
	assert.NoError(t, err)

	// Verify expected defaults
	assert.NotNil(t, config.Ports)
	assert.Equal(t, 2, len(config.Ports.Inputs), "should have 2 input ports")
	assert.Equal(t, 1, len(config.Ports.Outputs), "should have 1 output port")
	assert.Equal(t, 1*time.Hour, config.ComputeInterval)
	assert.Equal(t, 16, config.PivotCount)
	assert.Equal(t, 10, config.MaxHopDistance)
	assert.Equal(t, true, config.ComputeOnStartup)

	// Verify required inputs
	inputs := config.Ports.Inputs
	hasOutgoingWatch := false
	hasIncomingWatch := false
	for _, in := range inputs {
		if in.Subject == "OUTGOING_INDEX" && in.Type == "kv-watch" {
			hasOutgoingWatch = true
		}
		if in.Subject == "INCOMING_INDEX" && in.Type == "kv-watch" {
			hasIncomingWatch = true
		}
	}
	assert.True(t, hasOutgoingWatch, "should have OUTGOING_INDEX kv-watch input")
	assert.True(t, hasIncomingWatch, "should have INCOMING_INDEX kv-watch input")

	// Verify required output
	outputs := config.Ports.Outputs
	hasStructuralIndex := false
	for _, out := range outputs {
		if out.Subject == "STRUCTURAL_INDEX" && out.Type == "kv-write" {
			hasStructuralIndex = true
		}
	}
	assert.True(t, hasStructuralIndex, "should have STRUCTURAL_INDEX kv-write output")
}

// ====================================================================================
// Discoverable Interface Tests
// ====================================================================================

func TestComponent_Meta_ReturnsCorrectMetadata(t *testing.T) {
	comp := createTestComponent(t)

	meta := comp.Meta()

	assert.Equal(t, "processor", meta.Type)
	assert.Equal(t, "graph-anomalies", meta.Name)
	assert.NotEmpty(t, meta.Description)
	assert.NotEmpty(t, meta.Version)
}

func TestComponent_InputPorts_ReturnsTwoKVWatchPorts(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize()) // Ports are populated during Initialize

	ports := comp.InputPorts()

	require.Equal(t, 2, len(ports), "should have exactly 2 input ports")

	// Verify both KV watch ports exist
	hasOutgoingWatch := false
	hasIncomingWatch := false

	for _, port := range ports {
		assert.NotEmpty(t, port.Name)
		assert.Equal(t, component.DirectionInput, port.Direction)

		if kvPort, ok := port.Config.(component.KVWatchPort); ok {
			if kvPort.Bucket == "OUTGOING_INDEX" {
				hasOutgoingWatch = true
			}
			if kvPort.Bucket == "INCOMING_INDEX" {
				hasIncomingWatch = true
			}
		}
	}

	assert.True(t, hasOutgoingWatch, "should have OUTGOING_INDEX kv-watch port")
	assert.True(t, hasIncomingWatch, "should have INCOMING_INDEX kv-watch port")
}

func TestComponent_OutputPorts_ReturnsStructuralIndex(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize()) // Ports are populated during Initialize

	ports := comp.OutputPorts()

	require.Equal(t, 1, len(ports), "should have exactly 1 output port")

	// Verify STRUCTURAL_INDEX output bucket
	port := ports[0]
	assert.NotEmpty(t, port.Name)
	assert.Equal(t, component.DirectionOutput, port.Direction)

	kvPort, ok := port.Config.(component.KVWritePort)
	require.True(t, ok, "output port should be KVWritePort type")
	assert.Equal(t, "STRUCTURAL_INDEX", kvPort.Bucket)
}

func TestComponent_ConfigSchema_ReturnsValidSchema(t *testing.T) {
	comp := createTestComponent(t)

	schema := comp.ConfigSchema()

	// Verify schema has required properties
	assert.NotNil(t, schema.Properties)

	// Check for expected config properties
	_, hasPortsProperty := schema.Properties["ports"]
	assert.True(t, hasPortsProperty, "schema should have 'ports' property")

	_, hasComputeIntervalProperty := schema.Properties["compute_interval"]
	assert.True(t, hasComputeIntervalProperty, "schema should have 'compute_interval' property")

	_, hasPivotCountProperty := schema.Properties["pivot_count"]
	assert.True(t, hasPivotCountProperty, "schema should have 'pivot_count' property")

	_, hasMaxHopDistanceProperty := schema.Properties["max_hop_distance"]
	assert.True(t, hasMaxHopDistanceProperty, "schema should have 'max_hop_distance' property")

	_, hasComputeOnStartupProperty := schema.Properties["compute_on_startup"]
	assert.True(t, hasComputeOnStartupProperty, "schema should have 'compute_on_startup' property")
}

func TestComponent_Health_NotStarted(t *testing.T) {
	comp := createTestComponent(t)

	health := comp.Health()

	assert.False(t, health.Healthy, "component should be unhealthy before start")
	assert.Equal(t, "stopped", health.Status)
	assert.Equal(t, 0, health.ErrorCount)
}

func TestComponent_Health_Running(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))
	defer comp.Stop(1 * time.Second)

	// Allow time for component to become healthy
	time.Sleep(100 * time.Millisecond)

	health := comp.Health()

	assert.True(t, health.Healthy, "component should be healthy when running")
	assert.Equal(t, "running", health.Status)
	assert.Greater(t, health.Uptime, time.Duration(0))
}

func TestComponent_DataFlow_ReturnsMetrics(t *testing.T) {
	comp := createTestComponent(t)

	metrics := comp.DataFlow()

	// Verify FlowMetrics structure
	assert.GreaterOrEqual(t, metrics.MessagesPerSecond, float64(0))
	assert.GreaterOrEqual(t, metrics.BytesPerSecond, float64(0))
	assert.GreaterOrEqual(t, metrics.ErrorRate, float64(0))
	assert.NotZero(t, metrics.LastActivity)
}

// ====================================================================================
// LifecycleComponent Interface Tests
// ====================================================================================

func TestComponent_Initialize_Success(t *testing.T) {
	comp := createTestComponent(t)

	err := comp.Initialize()

	assert.NoError(t, err)

	// Verify ports are initialized
	assert.Equal(t, 2, len(comp.InputPorts()), "should have 2 input ports")
	assert.Equal(t, 1, len(comp.OutputPorts()), "should have 1 output port")
}

func TestComponent_Initialize_InvalidConfig(t *testing.T) {
	// Create component with invalid config (no ports)
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	comp := &Component{
		config: Config{
			Ports:            nil, // Invalid - missing ports
			ComputeInterval:  1 * time.Hour,
			PivotCount:       16,
			MaxHopDistance:   10,
			ComputeOnStartup: true,
		},
		natsClient: natsClient,
	}

	err = comp.Initialize()

	assert.Error(t, err, "Initialize should fail with invalid config")
}

func TestComponent_Initialize_Idempotent(t *testing.T) {
	comp := createTestComponent(t)

	// Initialize twice
	err1 := comp.Initialize()
	err2 := comp.Initialize()

	assert.NoError(t, err1)
	assert.NoError(t, err2, "Initialize should be idempotent")
}

func TestComponent_Start_Success(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	err := comp.Start(ctx)
	defer comp.Stop(1 * time.Second)

	assert.NoError(t, err)
}

func TestComponent_Start_BeforeInitialize(t *testing.T) {
	comp := createTestComponent(t)
	ctx := context.Background()

	// Start without Initialize
	err := comp.Start(ctx)

	assert.Error(t, err, "Start should fail if not initialized")
}

func TestComponent_Start_AlreadyStarted(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))
	defer comp.Stop(1 * time.Second)

	// Start again - should be idempotent
	err := comp.Start(ctx)

	assert.NoError(t, err, "Start should be idempotent")
}

func TestComponent_Stop_Success(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	err := comp.Stop(5 * time.Second)

	assert.NoError(t, err)
}

func TestComponent_Stop_BeforeStart(t *testing.T) {
	comp := createTestComponent(t)

	// Stop without Start
	err := comp.Stop(1 * time.Second)

	assert.NoError(t, err, "Stop should be safe even if not started")
}

func TestComponent_Stop_Timeout(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	// Very short timeout
	err := comp.Stop(1 * time.Nanosecond)

	// Should either succeed quickly or timeout gracefully
	// Implementation may vary, but should not panic
	_ = err
}

// ====================================================================================
// Factory and Registration Tests
// ====================================================================================

func TestCreateGraphAnomalies_ValidConfig(t *testing.T) {
	config := DefaultConfig()
	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := CreateGraphAnomalies(configJSON, deps)

	assert.NoError(t, err)
	assert.NotNil(t, comp)
	assert.Implements(t, (*component.Discoverable)(nil), comp)
	assert.Implements(t, (*component.LifecycleComponent)(nil), comp)
}

func TestCreateGraphAnomalies_EmptyConfig(t *testing.T) {
	// Empty config should use defaults
	emptyJSON := []byte(`{}`)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := CreateGraphAnomalies(emptyJSON, deps)

	assert.NoError(t, err)
	assert.NotNil(t, comp)
}

func TestCreateGraphAnomalies_InvalidConfig(t *testing.T) {
	// Invalid JSON
	invalidJSON := []byte(`{invalid json}`)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := CreateGraphAnomalies(invalidJSON, deps)

	assert.Error(t, err)
	assert.Nil(t, comp)
}

func TestCreateGraphAnomalies_MissingDependencies(t *testing.T) {
	config := DefaultConfig()
	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	// Missing NATSClient dependency
	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := CreateGraphAnomalies(configJSON, deps)

	assert.Error(t, err, "should fail without NATSClient")
	assert.Nil(t, comp)
}

func TestCreateGraphAnomalies_CustomConfig(t *testing.T) {
	config := Config{
		Ports: &component.PortConfig{
			Inputs: []component.PortDefinition{
				{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
				{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
			},
			Outputs: []component.PortDefinition{
				{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
			},
		},
		ComputeInterval:  30 * time.Minute,
		PivotCount:       20,
		MaxHopDistance:   15,
		ComputeOnStartup: false,
	}

	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := CreateGraphAnomalies(configJSON, deps)

	assert.NoError(t, err)
	assert.NotNil(t, comp)

	// Verify custom configuration
	component := comp.(*Component)
	assert.Equal(t, 30*time.Minute, component.config.ComputeInterval)
	assert.Equal(t, 20, component.config.PivotCount)
	assert.Equal(t, 15, component.config.MaxHopDistance)
	assert.Equal(t, false, component.config.ComputeOnStartup)
}

func TestRegister_AddsToRegistry(t *testing.T) {
	registry := component.NewRegistry()

	err := Register(registry)

	assert.NoError(t, err)

	// Verify factory was registered
	factories := registry.ListFactories()
	_, exists := factories["graph-anomalies"]
	assert.True(t, exists, "graph-anomalies factory should be registered")
}

// ====================================================================================
// Context Handling Tests
// ====================================================================================

func TestComponent_RespectsContext_Cancellation(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx, cancel := context.WithCancel(context.Background())

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	// Cancel context
	cancel()

	// Allow time for cancellation to propagate
	time.Sleep(100 * time.Millisecond)

	// Component should handle cancellation gracefully
	err := comp.Stop(1 * time.Second)
	assert.NoError(t, err)
}

func TestComponent_RespectsContext_Timeout(t *testing.T) {
	comp := createTestComponent(t)
	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
	defer cancel()

	require.NoError(t, comp.Initialize())

	// Start with timeout context
	err := comp.Start(ctx)

	// Should either succeed or handle timeout gracefully
	if err != nil {
		// If error, it should be context-related
		assert.Contains(t, err.Error(), "context")
	}
}

// ====================================================================================
// Concurrent Operations Tests
// ====================================================================================

func TestComponent_ConcurrentHealthChecks_ThreadSafe(t *testing.T) {
	comp := createTestComponent(t)

	// Run concurrent health checks
	const numGoroutines = 50

	done := make(chan bool)
	for i := 0; i < numGoroutines; i++ {
		go func() {
			for j := 0; j < 100; j++ {
				_ = comp.Health()
				_ = comp.DataFlow()
			}
			done <- true
		}()
	}

	// Wait for all goroutines
	for i := 0; i < numGoroutines; i++ {
		<-done
	}

	// No assertions needed - test passes if no data race detected
}

func TestComponent_ConcurrentMetaAccess_ThreadSafe(t *testing.T) {
	comp := createTestComponent(t)

	// Run concurrent metadata access
	const numGoroutines = 50

	done := make(chan bool)
	for i := 0; i < numGoroutines; i++ {
		go func() {
			for j := 0; j < 100; j++ {
				_ = comp.Meta()
				_ = comp.ConfigSchema()
			}
			done <- true
		}()
	}

	// Wait for all goroutines
	for i := 0; i < numGoroutines; i++ {
		<-done
	}

	// No assertions needed - test passes if no data race detected
}

// ====================================================================================
// Error Handling Tests
// ====================================================================================

func TestComponent_InitializeError_InvalidConfig(t *testing.T) {
	// Create component with invalid config that will fail validation
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	comp := &Component{
		config: Config{
			Ports:            nil, // Invalid
			ComputeInterval:  1 * time.Hour,
			PivotCount:       16,
			MaxHopDistance:   10,
			ComputeOnStartup: true,
		},
		natsClient: natsClient,
	}

	// Try to initialize
	err = comp.Initialize()

	assert.Error(t, err, "Initialize should fail")
}

func TestComponent_MultipleConfigValidations(t *testing.T) {
	tests := []struct {
		name      string
		config    Config
		shouldErr bool
	}{
		{
			name: "valid minimal",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
			shouldErr: false,
		},
		{
			name: "invalid - zero interval",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  0,
				PivotCount:       16,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
			shouldErr: true,
		},
		{
			name: "invalid - zero pivot count",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       0,
				MaxHopDistance:   10,
				ComputeOnStartup: true,
			},
			shouldErr: true,
		},
		{
			name: "invalid - zero max hop distance",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "outgoing_watch", Type: "kv-watch", Subject: "OUTGOING_INDEX"},
						{Name: "incoming_watch", Type: "kv-watch", Subject: "INCOMING_INDEX"},
					},
					Outputs: []component.PortDefinition{
						{Name: "structural_index", Type: "kv-write", Subject: "STRUCTURAL_INDEX"},
					},
				},
				ComputeInterval:  1 * time.Hour,
				PivotCount:       16,
				MaxHopDistance:   0,
				ComputeOnStartup: true,
			},
			shouldErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if tt.shouldErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

// ====================================================================================
// Helper Functions
// ====================================================================================

// createTestComponent creates a basic test component with unconnected NATS client
func createTestComponent(t *testing.T) *Component {
	t.Helper()

	// Create unconnected NATS client (won't actually connect)
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	config := DefaultConfig()
	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	comp, err := CreateGraphAnomalies(configJSON, deps)
	require.NoError(t, err)

	return comp.(*Component)
}
