// Code generated by Tester Agent. DO NOT EDIT.
// Task: Chat UI Phase 2 — ChatInput component tests
// Builder must make these tests pass without modification.

import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/svelte";
import userEvent from "@testing-library/user-event";
import ChatInput from "./ChatInput.svelte";

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

describe("ChatInput — initial render", () => {
  it("should render a textarea with the correct placeholder", () => {
    render(ChatInput, { props: { onSubmit: vi.fn() } });

    const textarea = screen.getByTestId("chat-input");
    expect(textarea).toBeInTheDocument();
    expect(textarea).toHaveAttribute(
      "placeholder",
      "Ask a question or type / for commands...",
    );
  });

  it("should render a submit button by default", () => {
    render(ChatInput, { props: { onSubmit: vi.fn() } });

    expect(screen.getByTestId("chat-submit")).toBeInTheDocument();
  });

  it("should NOT render a cancel button by default", () => {
    render(ChatInput, { props: { onSubmit: vi.fn() } });

    expect(screen.queryByTestId("chat-cancel")).not.toBeInTheDocument();
  });

  it("should have data-testid='chat-input' on the textarea", () => {
    render(ChatInput, { props: { onSubmit: vi.fn() } });

    expect(screen.getByTestId("chat-input").tagName).toBe("TEXTAREA");
  });
});

// ---------------------------------------------------------------------------
// Submit behavior
// ---------------------------------------------------------------------------

describe("ChatInput — submit on Enter", () => {
  it("should call onSubmit with content when Enter is pressed", async () => {
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    render(ChatInput, { props: { onSubmit } });

    const textarea = screen.getByTestId("chat-input");
    await user.type(textarea, "Build a pipeline{Enter}");

    expect(onSubmit).toHaveBeenCalledOnce();
    expect(onSubmit).toHaveBeenCalledWith("Build a pipeline");
  });

  it("should NOT submit on Shift+Enter (allows newline)", async () => {
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    render(ChatInput, { props: { onSubmit } });

    const textarea = screen.getByTestId("chat-input");
    await user.type(textarea, "Line one{Shift>}{Enter}{/Shift}Line two");

    expect(onSubmit).not.toHaveBeenCalled();
  });

  it("should NOT submit empty input", async () => {
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    render(ChatInput, { props: { onSubmit } });

    const textarea = screen.getByTestId("chat-input");
    await user.type(textarea, "{Enter}");

    expect(onSubmit).not.toHaveBeenCalled();
  });

  it("should NOT submit whitespace-only input", async () => {
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    render(ChatInput, { props: { onSubmit } });

    const textarea = screen.getByTestId("chat-input");
    await user.type(textarea, "   {Enter}");

    expect(onSubmit).not.toHaveBeenCalled();
  });

  it("should trim content before submitting", async () => {
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    render(ChatInput, { props: { onSubmit } });

    const textarea = screen.getByTestId("chat-input");
    await user.type(textarea, "  hello world  {Enter}");

    expect(onSubmit).toHaveBeenCalledWith("hello world");
  });

  it("should clear the textarea after successful submit", async () => {
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    render(ChatInput, { props: { onSubmit } });

    const textarea = screen.getByTestId("chat-input");
    await user.type(textarea, "Build a flow{Enter}");

    expect(textarea).toHaveValue("");
  });
});

// ---------------------------------------------------------------------------
// Streaming state
// ---------------------------------------------------------------------------

describe("ChatInput — streaming state", () => {
  it("should show cancel button when isStreaming=true", () => {
    render(ChatInput, {
      props: { onSubmit: vi.fn(), isStreaming: true },
    });

    expect(screen.getByTestId("chat-cancel")).toBeInTheDocument();
  });

  it("should NOT show submit button when isStreaming=true", () => {
    render(ChatInput, {
      props: { onSubmit: vi.fn(), isStreaming: true },
    });

    expect(screen.queryByTestId("chat-submit")).not.toBeInTheDocument();
  });

  it("should call onCancel when cancel button is clicked", async () => {
    const onCancel = vi.fn();
    const user = userEvent.setup();

    render(ChatInput, {
      props: { onSubmit: vi.fn(), onCancel, isStreaming: true },
    });

    await user.click(screen.getByTestId("chat-cancel"));

    expect(onCancel).toHaveBeenCalledOnce();
  });
});

// ---------------------------------------------------------------------------
// Disabled state
// ---------------------------------------------------------------------------

describe("ChatInput — disabled state", () => {
  it("should disable the textarea when disabled=true", () => {
    render(ChatInput, { props: { onSubmit: vi.fn(), disabled: true } });

    expect(screen.getByTestId("chat-input")).toBeDisabled();
  });

  it("should disable the submit button when disabled=true", () => {
    render(ChatInput, { props: { onSubmit: vi.fn(), disabled: true } });

    expect(screen.getByTestId("chat-submit")).toBeDisabled();
  });

  it("should not call onSubmit when Enter is pressed and disabled=true", async () => {
    const onSubmit = vi.fn();

    render(ChatInput, { props: { onSubmit, disabled: true } });

    // Input is disabled — type should not fire on the element
    expect(onSubmit).not.toHaveBeenCalled();
  });
});

// ---------------------------------------------------------------------------
// Table-driven: isStreaming × disabled combinations
// ---------------------------------------------------------------------------

describe("ChatInput — prop combinations", () => {
  const cases = [
    {
      description: "default: submit visible, cancel hidden, textarea enabled",
      props: { disabled: false, isStreaming: false },
      expectSubmit: true,
      expectCancel: false,
      expectDisabled: false,
    },
    {
      description: "streaming: cancel visible, submit hidden",
      props: { disabled: false, isStreaming: true },
      expectSubmit: false,
      expectCancel: true,
      expectDisabled: false,
    },
    {
      description: "disabled: submit visible, textarea disabled",
      props: { disabled: true, isStreaming: false },
      expectSubmit: true,
      expectCancel: false,
      expectDisabled: true,
    },
    {
      description: "streaming + disabled: cancel visible, textarea disabled",
      props: { disabled: true, isStreaming: true },
      expectSubmit: false,
      expectCancel: true,
      expectDisabled: true,
    },
  ] as const;

  it.each(cases)(
    "$description",
    ({ props, expectSubmit, expectCancel, expectDisabled }) => {
      render(ChatInput, { props: { onSubmit: vi.fn(), ...props } });

      if (expectSubmit) {
        expect(screen.getByTestId("chat-submit")).toBeInTheDocument();
      } else {
        expect(screen.queryByTestId("chat-submit")).not.toBeInTheDocument();
      }

      if (expectCancel) {
        expect(screen.getByTestId("chat-cancel")).toBeInTheDocument();
      } else {
        expect(screen.queryByTestId("chat-cancel")).not.toBeInTheDocument();
      }

      if (expectDisabled) {
        expect(screen.getByTestId("chat-input")).toBeDisabled();
      } else {
        expect(screen.getByTestId("chat-input")).not.toBeDisabled();
      }
    },
  );
});
