// Code generated by Tester Agent. DO NOT EDIT.
// Task: agentic-loop processor unit tests (greenfield)
// Builder must make these tests pass without modification.

package agenticloop_test

import (
	"testing"

	"github.com/c360studio/semstreams/agentic"
	agenticloop "github.com/c360studio/semstreams/processor/agentic-loop"
)

func TestLoopManager_CreateLoop(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	tests := []struct {
		name          string
		taskID        string
		role          string
		model         string
		maxIterations int
	}{
		{
			name:          "create with default max iterations",
			taskID:        "task-001",
			role:          "general",
			model:         "qwen-32b",
			maxIterations: 0, // 0 means use default
		},
		{
			name:          "create with custom max iterations",
			taskID:        "task-002",
			role:          "architect",
			model:         "deepseek-16b",
			maxIterations: 30,
		},
		{
			name:          "create editor role",
			taskID:        "task-003",
			role:          "editor",
			model:         "qwen-32b",
			maxIterations: 20,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var loopID string
			var err error

			if tt.maxIterations > 0 {
				loopID, err = manager.CreateLoop(tt.taskID, tt.role, tt.model, tt.maxIterations)
			} else {
				loopID, err = manager.CreateLoop(tt.taskID, tt.role, tt.model)
			}

			if err != nil {
				t.Fatalf("CreateLoop() error = %v", err)
			}

			if loopID == "" {
				t.Fatal("CreateLoop() returned empty loop ID")
			}

			// Verify loop was created
			entity, err := manager.GetLoop(loopID)
			if err != nil {
				t.Fatalf("GetLoop() error = %v", err)
			}

			if entity.ID != loopID {
				t.Errorf("Entity.ID = %s, want %s", entity.ID, loopID)
			}
			if entity.TaskID != tt.taskID {
				t.Errorf("Entity.TaskID = %s, want %s", entity.TaskID, tt.taskID)
			}
			if entity.Role != tt.role {
				t.Errorf("Entity.Role = %s, want %s", entity.Role, tt.role)
			}
			if entity.Model != tt.model {
				t.Errorf("Entity.Model = %s, want %s", entity.Model, tt.model)
			}
			if entity.State != agentic.LoopStateExploring {
				t.Errorf("Entity.State = %s, want exploring", entity.State)
			}
			if entity.Iterations != 0 {
				t.Errorf("Entity.Iterations = %d, want 0", entity.Iterations)
			}

			expectedMaxIter := tt.maxIterations
			if expectedMaxIter == 0 {
				expectedMaxIter = 20 // default
			}
			if entity.MaxIterations != expectedMaxIter {
				t.Errorf("Entity.MaxIterations = %d, want %d", entity.MaxIterations, expectedMaxIter)
			}
		})
	}
}

func TestLoopManager_GetLoop(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	// Create a loop
	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	tests := []struct {
		name    string
		loopID  string
		wantErr bool
	}{
		{
			name:    "get existing loop",
			loopID:  loopID,
			wantErr: false,
		},
		{
			name:    "get non-existent loop",
			loopID:  "loop-does-not-exist",
			wantErr: true,
		},
		{
			name:    "get with empty ID",
			loopID:  "",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			entity, err := manager.GetLoop(tt.loopID)

			if (err != nil) != tt.wantErr {
				t.Errorf("GetLoop() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if !tt.wantErr {
				if entity.ID != tt.loopID {
					t.Errorf("Entity.ID = %s, want %s", entity.ID, tt.loopID)
				}
			}
		})
	}
}

func TestLoopManager_UpdateLoop(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	// Create a loop
	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	// Get the entity
	entity, err := manager.GetLoop(loopID)
	if err != nil {
		t.Fatalf("GetLoop() error = %v", err)
	}

	// Modify the entity
	entity.State = agentic.LoopStatePlanning
	entity.Iterations = 5

	// Update
	err = manager.UpdateLoop(entity)
	if err != nil {
		t.Fatalf("UpdateLoop() error = %v", err)
	}

	// Verify update
	updated, err := manager.GetLoop(loopID)
	if err != nil {
		t.Fatalf("GetLoop() after update error = %v", err)
	}

	if updated.State != agentic.LoopStatePlanning {
		t.Errorf("Updated.State = %s, want planning", updated.State)
	}
	if updated.Iterations != 5 {
		t.Errorf("Updated.Iterations = %d, want 5", updated.Iterations)
	}
}

func TestLoopManager_UpdateLoop_NonExistent(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	entity := agentic.NewLoopEntity("loop-does-not-exist", "task-001", "general", "qwen-32b")

	err := manager.UpdateLoop(entity)
	if err == nil {
		t.Fatal("UpdateLoop() with non-existent ID should return error")
	}

	if !containsIgnoreCase(err.Error(), "not found") && !containsIgnoreCase(err.Error(), "does not exist") {
		t.Errorf("Error should mention not found/does not exist, got: %v", err)
	}
}

func TestLoopManager_DeleteLoop(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	// Create a loop
	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	// Verify it exists
	_, err = manager.GetLoop(loopID)
	if err != nil {
		t.Fatalf("GetLoop() before delete error = %v", err)
	}

	// Delete
	err = manager.DeleteLoop(loopID)
	if err != nil {
		t.Fatalf("DeleteLoop() error = %v", err)
	}

	// Verify it's gone
	_, err = manager.GetLoop(loopID)
	if err == nil {
		t.Fatal("GetLoop() after delete should return error")
	}
}

func TestLoopManager_DeleteLoop_NonExistent(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	err := manager.DeleteLoop("loop-does-not-exist")
	// Deleting non-existent loop may or may not error depending on implementation
	// Just ensure it doesn't panic
	_ = err
}

func TestLoopManager_StateTransition(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	// Create a loop
	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	tests := []struct {
		name      string
		fromState agentic.LoopState
		toState   agentic.LoopState
		wantErr   bool
	}{
		{
			name:      "exploring to planning",
			fromState: agentic.LoopStateExploring,
			toState:   agentic.LoopStatePlanning,
			wantErr:   false,
		},
		{
			name:      "planning to architecting",
			fromState: agentic.LoopStatePlanning,
			toState:   agentic.LoopStateArchitecting,
			wantErr:   false,
		},
		{
			name:      "architecting to executing",
			fromState: agentic.LoopStateArchitecting,
			toState:   agentic.LoopStateExecuting,
			wantErr:   false,
		},
		{
			name:      "executing to reviewing",
			fromState: agentic.LoopStateExecuting,
			toState:   agentic.LoopStateReviewing,
			wantErr:   false,
		},
		{
			name:      "reviewing to complete",
			fromState: agentic.LoopStateReviewing,
			toState:   agentic.LoopStateComplete,
			wantErr:   false,
		},
		{
			name:      "backward transition (executing to exploring)",
			fromState: agentic.LoopStateExecuting,
			toState:   agentic.LoopStateExploring,
			wantErr:   false, // Fluid transitions allow backward movement
		},
		{
			name:      "same state transition",
			fromState: agentic.LoopStatePlanning,
			toState:   agentic.LoopStatePlanning,
			wantErr:   false, // Same state is allowed (no-op)
		},
		{
			name:      "transition from terminal state (complete)",
			fromState: agentic.LoopStateComplete,
			toState:   agentic.LoopStateExecuting,
			wantErr:   true, // Cannot transition from terminal state
		},
		{
			name:      "transition from terminal state (failed)",
			fromState: agentic.LoopStateFailed,
			toState:   agentic.LoopStateExploring,
			wantErr:   true, // Cannot transition from terminal state
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Get entity and set to fromState
			entity, err := manager.GetLoop(loopID)
			if err != nil {
				t.Fatalf("GetLoop() error = %v", err)
			}

			entity.State = tt.fromState
			err = manager.UpdateLoop(entity)
			if err != nil {
				t.Fatalf("UpdateLoop() to set fromState error = %v", err)
			}

			// Attempt transition
			err = manager.TransitionLoop(loopID, tt.toState)

			if (err != nil) != tt.wantErr {
				t.Errorf("TransitionLoop() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if !tt.wantErr {
				// Verify state changed
				entity, err := manager.GetLoop(loopID)
				if err != nil {
					t.Fatalf("GetLoop() after transition error = %v", err)
				}
				if entity.State != tt.toState {
					t.Errorf("After transition, State = %s, want %s", entity.State, tt.toState)
				}
			}
		})
	}
}

func TestLoopManager_IncrementIteration(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	// Create a loop with max 3 iterations
	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b", 3)
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	// Increment 3 times (should succeed)
	for i := 1; i <= 3; i++ {
		err = manager.IncrementIteration(loopID)
		if err != nil {
			t.Fatalf("IncrementIteration() #%d error = %v", i, err)
		}

		entity, err := manager.GetLoop(loopID)
		if err != nil {
			t.Fatalf("GetLoop() error = %v", err)
		}
		if entity.Iterations != i {
			t.Errorf("After increment #%d, Iterations = %d, want %d", i, entity.Iterations, i)
		}
	}

	// 4th increment should fail (max reached)
	err = manager.IncrementIteration(loopID)
	if err == nil {
		t.Fatal("IncrementIteration() beyond max should return error")
	}

	if !containsIgnoreCase(err.Error(), "max") && !containsIgnoreCase(err.Error(), "limit") {
		t.Errorf("Error should mention max/limit, got: %v", err)
	}
}

func TestLoopManager_IncrementIteration_NonExistent(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	err := manager.IncrementIteration("loop-does-not-exist")
	if err == nil {
		t.Fatal("IncrementIteration() with non-existent ID should return error")
	}
}

func TestLoopManager_PendingTools(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	// Create a loop
	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	// Initially no pending tools
	pending := manager.GetPendingTools(loopID)
	if len(pending) != 0 {
		t.Errorf("GetPendingTools() initially should be empty, got %d", len(pending))
	}

	// Should be complete with no pending tools
	if !manager.AllToolsComplete(loopID) {
		t.Error("AllToolsComplete() should be true with no pending tools")
	}

	// Add pending tools
	err = manager.AddPendingTool(loopID, "call-001")
	if err != nil {
		t.Fatalf("AddPendingTool() error = %v", err)
	}

	err = manager.AddPendingTool(loopID, "call-002")
	if err != nil {
		t.Fatalf("AddPendingTool() error = %v", err)
	}

	err = manager.AddPendingTool(loopID, "call-003")
	if err != nil {
		t.Fatalf("AddPendingTool() error = %v", err)
	}

	// Verify pending tools
	pending = manager.GetPendingTools(loopID)
	if len(pending) != 3 {
		t.Errorf("GetPendingTools() count = %d, want 3", len(pending))
	}

	// Not all complete
	if manager.AllToolsComplete(loopID) {
		t.Error("AllToolsComplete() should be false with pending tools")
	}

	// Remove one tool
	err = manager.RemovePendingTool(loopID, "call-001")
	if err != nil {
		t.Fatalf("RemovePendingTool() error = %v", err)
	}

	pending = manager.GetPendingTools(loopID)
	if len(pending) != 2 {
		t.Errorf("GetPendingTools() after remove count = %d, want 2", len(pending))
	}

	// Remove remaining tools
	err = manager.RemovePendingTool(loopID, "call-002")
	if err != nil {
		t.Fatalf("RemovePendingTool() error = %v", err)
	}

	err = manager.RemovePendingTool(loopID, "call-003")
	if err != nil {
		t.Fatalf("RemovePendingTool() error = %v", err)
	}

	pending = manager.GetPendingTools(loopID)
	if len(pending) != 0 {
		t.Errorf("GetPendingTools() after removing all should be empty, got %d", len(pending))
	}

	// All tools complete again
	if !manager.AllToolsComplete(loopID) {
		t.Error("AllToolsComplete() should be true after removing all pending tools")
	}
}

func TestLoopManager_PendingTools_DuplicateAdd(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	// Add same call ID twice
	err = manager.AddPendingTool(loopID, "call-001")
	if err != nil {
		t.Fatalf("First AddPendingTool() error = %v", err)
	}

	err = manager.AddPendingTool(loopID, "call-001")
	// Duplicate add may or may not error depending on implementation
	// Just ensure it doesn't panic
	_ = err

	// Should have at least one pending tool
	pending := manager.GetPendingTools(loopID)
	if len(pending) < 1 {
		t.Error("GetPendingTools() should have at least 1 pending tool")
	}
}

func TestLoopManager_PendingTools_RemoveNonExistent(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	// Remove non-existent call ID
	err = manager.RemovePendingTool(loopID, "call-does-not-exist")
	// Removing non-existent may or may not error
	// Just ensure it doesn't panic
	_ = err
}

func TestLoopManager_PendingTools_NonExistentLoop(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	loopID := "loop-does-not-exist"

	// GetPendingTools on non-existent loop should return empty or error
	pending := manager.GetPendingTools(loopID)
	if pending == nil {
		// If nil, that's okay (indicates not found)
	} else if len(pending) != 0 {
		// If non-nil, should be empty
		t.Errorf("GetPendingTools() on non-existent loop should be empty, got %d", len(pending))
	}

	// AllToolsComplete on non-existent loop
	complete := manager.AllToolsComplete(loopID)
	// May return true (no pending) or false (loop not found)
	// Just ensure it doesn't panic
	_ = complete

	// AddPendingTool on non-existent loop should error
	err := manager.AddPendingTool(loopID, "call-001")
	if err == nil {
		t.Error("AddPendingTool() on non-existent loop should return error")
	}
}

func TestLoopManager_ConcurrentAccess(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	// Create a loop
	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	// Concurrent updates
	done := make(chan bool)
	for i := 0; i < 10; i++ {
		go func() {
			entity, err := manager.GetLoop(loopID)
			if err != nil {
				done <- false
				return
			}
			entity.Iterations++
			_ = manager.UpdateLoop(entity)
			done <- true
		}()
	}

	// Wait for all goroutines
	for i := 0; i < 10; i++ {
		<-done
	}

	// Race detector will catch any concurrency issues
	// Final state may vary due to concurrent updates (that's expected)
}

func TestLoopManager_ConcurrentPendingTools(t *testing.T) {
	manager := agenticloop.NewLoopManager()

	loopID, err := manager.CreateLoop("task-001", "general", "qwen-32b")
	if err != nil {
		t.Fatalf("CreateLoop() error = %v", err)
	}

	// Concurrent add/remove of pending tools
	done := make(chan bool)
	for i := 0; i < 10; i++ {
		go func(n int) {
			callID := "call-" + string(rune('0'+n))
			_ = manager.AddPendingTool(loopID, callID)
			_ = manager.GetPendingTools(loopID)
			_ = manager.AllToolsComplete(loopID)
			_ = manager.RemovePendingTool(loopID, callID)
			done <- true
		}(i)
	}

	for i := 0; i < 10; i++ {
		<-done
	}

	// Race detector will catch any concurrency issues
}
