// Code generated by Tester Agent. DO NOT EDIT.
// Task: Query handler unit tests for graph-ingest component
// Builder must make these tests pass without modification.

package graphingest

import (
	"context"
	"encoding/json"
	"fmt"
	"testing"
	"time"

	"github.com/c360/semstreams/component"
	"github.com/c360/semstreams/graph"
	"github.com/c360/semstreams/message"
	"github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/jetstream"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ====================================================================================
// QueryCapabilityProvider Interface Tests
// ====================================================================================

func TestComponent_ImplementsQueryCapabilityProvider(t *testing.T) {
	comp := createTestComponent(t)

	// Verify component implements QueryCapabilityProvider interface
	var _ component.QueryCapabilityProvider = comp
}

func TestComponent_QueryCapabilities_ReturnsValidCapabilities(t *testing.T) {
	comp := createTestComponent(t)

	caps := comp.QueryCapabilities()

	// Verify basic structure
	assert.Equal(t, "graph-ingest", caps.Component, "component name should be graph-ingest")
	assert.NotEmpty(t, caps.Version, "version should not be empty")
	assert.NotEmpty(t, caps.Queries, "should have at least one query capability")

	// Verify required query operations exist
	operations := make(map[string]component.QueryCapability)
	for _, q := range caps.Queries {
		operations[q.Operation] = q
	}

	// Check for entity query
	entityQuery, hasEntity := operations["getEntity"]
	assert.True(t, hasEntity, "should have getEntity operation")
	if hasEntity {
		assert.Equal(t, "graph.ingest.query.entity", entityQuery.Subject, "entity query should use correct subject")
		assert.NotNil(t, entityQuery.RequestSchema, "request schema should be defined")
		assert.NotNil(t, entityQuery.ResponseSchema, "response schema should be defined")
	}

	// Check for batch query
	batchQuery, hasBatch := operations["getBatch"]
	assert.True(t, hasBatch, "should have getBatch operation")
	if hasBatch {
		assert.Equal(t, "graph.ingest.query.batch", batchQuery.Subject, "batch query should use correct subject")
		assert.NotNil(t, batchQuery.RequestSchema, "request schema should be defined")
		assert.NotNil(t, batchQuery.ResponseSchema, "response schema should be defined")
	}
}

func TestComponent_QueryCapabilities_SchemasAreValid(t *testing.T) {
	comp := createTestComponent(t)

	caps := comp.QueryCapabilities()

	for _, q := range caps.Queries {
		// Verify schemas can be marshaled to JSON
		requestJSON, err := json.Marshal(q.RequestSchema)
		assert.NoError(t, err, "request schema for %s should be valid JSON", q.Operation)
		assert.NotEmpty(t, requestJSON, "request schema should not be empty")

		responseJSON, err := json.Marshal(q.ResponseSchema)
		assert.NoError(t, err, "response schema for %s should be valid JSON", q.Operation)
		assert.NotEmpty(t, responseJSON, "response schema should not be empty")
	}
}

// ====================================================================================
// Query Handler: handleQueryEntity Tests
// ====================================================================================

func TestComponent_HandleQueryEntity_Success(t *testing.T) {
	tests := []struct {
		name     string
		entityID string
		entity   *graph.EntityState
	}{
		{
			name:     "minimal entity",
			entityID: "c360.platform.robotics.mav1.drone.001",
			entity: &graph.EntityState{
				ID:        "c360.platform.robotics.mav1.drone.001",
				Triples:   []message.Triple{},
				Version:   1,
				UpdatedAt: time.Now(),
			},
		},
		{
			name:     "entity with triples",
			entityID: "c360.platform.robotics.mav1.drone.002",
			entity: &graph.EntityState{
				ID: "c360.platform.robotics.mav1.drone.002",
				Triples: []message.Triple{
					{
						Subject:   "c360.platform.robotics.mav1.drone.002",
						Predicate: "robotics.status.armed",
						Object:    true,
						Timestamp: time.Now(),
					},
					{
						Subject:   "c360.platform.robotics.mav1.drone.002",
						Predicate: "robotics.battery.level",
						Object:    85.5,
						Timestamp: time.Now(),
					},
				},
				Version:   1,
				UpdatedAt: time.Now(),
			},
		},
		{
			name:     "entity with complex ID",
			entityID: "acme.ops.logistics.warehouse.robot.robot-007",
			entity: &graph.EntityState{
				ID: "acme.ops.logistics.warehouse.robot.robot-007",
				Triples: []message.Triple{
					{
						Subject:   "acme.ops.logistics.warehouse.robot.robot-007",
						Predicate: "location.zone",
						Object:    "A-12",
						Timestamp: time.Now(),
					},
				},
				Version:   1,
				UpdatedAt: time.Now(),
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			comp := createTestComponentWithMockKV(t)
			ctx := context.Background()

			// Store entity in KV bucket
			require.NoError(t, comp.CreateEntity(ctx, tt.entity))

			// Create request
			request := map[string]string{"id": tt.entityID}
			requestJSON, err := json.Marshal(request)
			require.NoError(t, err)

			// Create mock NATS message
			msg := &mockNATSMsg{
				data: requestJSON,
			}

			// Handle query
			comp.handleQueryEntity(msg)

			// Verify response
			require.NotNil(t, msg.response, "should have response")

			var responseEntity graph.EntityState
			err = json.Unmarshal(msg.response, &responseEntity)
			require.NoError(t, err, "response should be valid EntityState JSON")

			assert.Equal(t, tt.entity.ID, responseEntity.ID, "entity ID should match")
			assert.Equal(t, len(tt.entity.Triples), len(responseEntity.Triples), "triple count should match")
		})
	}
}

func TestComponent_HandleQueryEntity_NotFound(t *testing.T) {
	comp := createTestComponentWithMockKV(t)

	// Create request for non-existent entity
	request := map[string]string{"id": "c360.platform.robotics.mav1.drone.999"}
	requestJSON, err := json.Marshal(request)
	require.NoError(t, err)

	msg := &mockNATSMsg{
		data: requestJSON,
	}

	// Handle query
	comp.handleQueryEntity(msg)

	// Verify error response
	require.NotNil(t, msg.response, "should have response")

	var errorResp map[string]string
	err = json.Unmarshal(msg.response, &errorResp)
	require.NoError(t, err, "response should be valid JSON")

	assert.Contains(t, errorResp, "error", "response should contain error field")
	assert.NotEmpty(t, errorResp["error"], "error message should not be empty")
}

func TestComponent_HandleQueryEntity_InvalidRequest(t *testing.T) {
	tests := []struct {
		name        string
		requestData []byte
	}{
		{
			name:        "malformed JSON",
			requestData: []byte(`{invalid json}`),
		},
		{
			name:        "missing id field",
			requestData: []byte(`{}`),
		},
		{
			name:        "empty id",
			requestData: []byte(`{"id": ""}`),
		},
		{
			name:        "null id",
			requestData: []byte(`{"id": null}`),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			comp := createTestComponentWithMockKV(t)

			msg := &mockNATSMsg{
				data: tt.requestData,
			}

			// Handle query
			comp.handleQueryEntity(msg)

			// Verify error response
			require.NotNil(t, msg.response, "should have response")

			var errorResp map[string]string
			err := json.Unmarshal(msg.response, &errorResp)
			require.NoError(t, err, "response should be valid JSON")

			assert.Contains(t, errorResp, "error", "response should contain error field")
		})
	}
}

func TestComponent_HandleQueryEntity_RespectsContext(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	// Create entity
	entity := &graph.EntityState{
		ID:        "c360.platform.robotics.mav1.drone.001",
		Triples:   []message.Triple{},
		Version:   1,
		UpdatedAt: time.Now(),
	}
	require.NoError(t, comp.CreateEntity(ctx, entity))

	// Mock KV bucket with context timeout
	mockBucket := comp.entityBucket.(*mockKVBucket)
	mockBucket.getFunc = func(ctx context.Context, key string) (jetstream.KeyValueEntry, error) {
		// Verify context is passed to KV operations
		assert.NotNil(t, ctx, "context should be passed to KV Get operation")

		// Check if context has timeout (implementation creates context with timeout)
		deadline, hasDeadline := ctx.Deadline()
		if hasDeadline {
			assert.True(t, deadline.After(time.Now()), "context should have future deadline")
		}

		// Return entity
		entityJSON, _ := json.Marshal(entity)
		return &mockKVEntry{data: entityJSON}, nil
	}

	// Create request
	request := map[string]string{"id": entity.ID}
	requestJSON, _ := json.Marshal(request)

	msg := &mockNATSMsg{
		data: requestJSON,
	}

	// Handle query
	comp.handleQueryEntity(msg)

	// Verify response was sent
	require.NotNil(t, msg.response)
}

// ====================================================================================
// Query Handler: handleQueryBatch Tests
// ====================================================================================

func TestComponent_HandleQueryBatch_Success(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	// Create multiple entities
	entities := []*graph.EntityState{
		{
			ID:        "c360.platform.robotics.mav1.drone.001",
			Triples:   []message.Triple{},
			Version:   1,
			UpdatedAt: time.Now(),
		},
		{
			ID: "c360.platform.robotics.mav1.drone.002",
			Triples: []message.Triple{
				{
					Subject:   "c360.platform.robotics.mav1.drone.002",
					Predicate: "robotics.status.armed",
					Object:    true,
					Timestamp: time.Now(),
				},
			},
			Version:   1,
			UpdatedAt: time.Now(),
		},
		{
			ID: "c360.platform.robotics.mav1.drone.003",
			Triples: []message.Triple{
				{
					Subject:   "c360.platform.robotics.mav1.drone.003",
					Predicate: "robotics.battery.level",
					Object:    42.0,
					Timestamp: time.Now(),
				},
			},
			Version:   1,
			UpdatedAt: time.Now(),
		},
	}

	for _, entity := range entities {
		require.NoError(t, comp.CreateEntity(ctx, entity))
	}

	// Create batch request
	request := map[string][]string{
		"ids": {
			"c360.platform.robotics.mav1.drone.001",
			"c360.platform.robotics.mav1.drone.002",
			"c360.platform.robotics.mav1.drone.003",
		},
	}
	requestJSON, err := json.Marshal(request)
	require.NoError(t, err)

	msg := &mockNATSMsg{
		data: requestJSON,
	}

	// Handle batch query
	comp.handleQueryBatch(msg)

	// Verify response
	require.NotNil(t, msg.response, "should have response")

	var responseEntities []graph.EntityState
	err = json.Unmarshal(msg.response, &responseEntities)
	require.NoError(t, err, "response should be valid EntityState array JSON")

	assert.Equal(t, 3, len(responseEntities), "should return all 3 entities")

	// Verify entities
	entityMap := make(map[string]graph.EntityState)
	for _, e := range responseEntities {
		entityMap[e.ID] = e
	}

	for _, expected := range entities {
		actual, found := entityMap[expected.ID]
		assert.True(t, found, "entity %s should be in response", expected.ID)
		if found {
			assert.Equal(t, expected.ID, actual.ID)
			assert.Equal(t, len(expected.Triples), len(actual.Triples))
		}
	}
}

func TestComponent_HandleQueryBatch_PartialFailure(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	// Create only 2 out of 3 requested entities
	entities := []*graph.EntityState{
		{
			ID:        "c360.platform.robotics.mav1.drone.001",
			Triples:   []message.Triple{},
			Version:   1,
			UpdatedAt: time.Now(),
		},
		{
			ID:        "c360.platform.robotics.mav1.drone.003",
			Triples:   []message.Triple{},
			Version:   1,
			UpdatedAt: time.Now(),
		},
	}

	for _, entity := range entities {
		require.NoError(t, comp.CreateEntity(ctx, entity))
	}

	// Request 3 entities (one doesn't exist)
	request := map[string][]string{
		"ids": {
			"c360.platform.robotics.mav1.drone.001",
			"c360.platform.robotics.mav1.drone.002", // Does not exist
			"c360.platform.robotics.mav1.drone.003",
		},
	}
	requestJSON, err := json.Marshal(request)
	require.NoError(t, err)

	msg := &mockNATSMsg{
		data: requestJSON,
	}

	// Handle batch query
	comp.handleQueryBatch(msg)

	// Verify response
	require.NotNil(t, msg.response, "should have response")

	var responseEntities []graph.EntityState
	err = json.Unmarshal(msg.response, &responseEntities)
	require.NoError(t, err, "response should be valid EntityState array JSON")

	// Should return only the 2 entities that exist (partial success)
	assert.Equal(t, 2, len(responseEntities), "should return only existing entities")

	// Verify the returned entities are the correct ones
	ids := make(map[string]bool)
	for _, e := range responseEntities {
		ids[e.ID] = true
	}

	assert.True(t, ids["c360.platform.robotics.mav1.drone.001"], "should include drone.001")
	assert.False(t, ids["c360.platform.robotics.mav1.drone.002"], "should NOT include non-existent drone.002")
	assert.True(t, ids["c360.platform.robotics.mav1.drone.003"], "should include drone.003")
}

func TestComponent_HandleQueryBatch_EmptyRequest(t *testing.T) {
	tests := []struct {
		name        string
		requestData []byte
	}{
		{
			name:        "empty ids array",
			requestData: []byte(`{"ids": []}`),
		},
		{
			name:        "missing ids field",
			requestData: []byte(`{}`),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			comp := createTestComponentWithMockKV(t)

			msg := &mockNATSMsg{
				data: tt.requestData,
			}

			// Handle batch query
			comp.handleQueryBatch(msg)

			// Verify response (should return empty array or error)
			require.NotNil(t, msg.response, "should have response")

			// Try to unmarshal as array
			var responseEntities []graph.EntityState
			err := json.Unmarshal(msg.response, &responseEntities)

			if err == nil {
				// If successful, should be empty array
				assert.Empty(t, responseEntities, "should return empty array for empty request")
			} else {
				// Otherwise, should be error object
				var errorResp map[string]string
				err = json.Unmarshal(msg.response, &errorResp)
				require.NoError(t, err, "response should be valid JSON")
				assert.Contains(t, errorResp, "error", "response should contain error field")
			}
		})
	}
}

func TestComponent_HandleQueryBatch_InvalidRequest(t *testing.T) {
	tests := []struct {
		name        string
		requestData []byte
	}{
		{
			name:        "malformed JSON",
			requestData: []byte(`{invalid json}`),
		},
		{
			name:        "ids is not an array",
			requestData: []byte(`{"ids": "not-an-array"}`),
		},
		{
			name:        "null ids",
			requestData: []byte(`{"ids": null}`),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			comp := createTestComponentWithMockKV(t)

			msg := &mockNATSMsg{
				data: tt.requestData,
			}

			// Handle batch query
			comp.handleQueryBatch(msg)

			// Verify error response
			require.NotNil(t, msg.response, "should have response")

			var errorResp map[string]string
			err := json.Unmarshal(msg.response, &errorResp)
			require.NoError(t, err, "response should be valid JSON")

			assert.Contains(t, errorResp, "error", "response should contain error field")
		})
	}
}

func TestComponent_HandleQueryBatch_LargeNumberOfEntities(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	// Create 100 entities
	numEntities := 100
	entityIDs := make([]string, numEntities)

	for i := 0; i < numEntities; i++ {
		entityID := formatEntityID("c360.platform.robotics.mav1.drone", i+1)
		entityIDs[i] = entityID

		entity := &graph.EntityState{
			ID:        entityID,
			Triples:   []message.Triple{},
			Version:   1,
			UpdatedAt: time.Now(),
		}
		require.NoError(t, comp.CreateEntity(ctx, entity))
	}

	// Request all entities
	request := map[string][]string{"ids": entityIDs}
	requestJSON, err := json.Marshal(request)
	require.NoError(t, err)

	msg := &mockNATSMsg{
		data: requestJSON,
	}

	// Handle batch query
	comp.handleQueryBatch(msg)

	// Verify response
	require.NotNil(t, msg.response, "should have response")

	var responseEntities []graph.EntityState
	err = json.Unmarshal(msg.response, &responseEntities)
	require.NoError(t, err, "response should be valid EntityState array JSON")

	assert.Equal(t, numEntities, len(responseEntities), "should return all entities")
}

// ====================================================================================
// Query Handler: handleCapabilities Tests
// ====================================================================================

func TestComponent_HandleCapabilities_ReturnsValidJSON(t *testing.T) {
	comp := createTestComponentWithMockKV(t)

	msg := &mockNATSMsg{
		data: []byte(`{}`),
	}

	// Handle capabilities query
	comp.handleCapabilities(msg)

	// Verify response
	require.NotNil(t, msg.response, "should have response")

	var caps component.QueryCapabilities
	err := json.Unmarshal(msg.response, &caps)
	require.NoError(t, err, "response should be valid QueryCapabilities JSON")

	assert.Equal(t, "graph-ingest", caps.Component)
	assert.NotEmpty(t, caps.Version)
	assert.NotEmpty(t, caps.Queries)
}

func TestComponent_HandleCapabilities_EmptyRequest(t *testing.T) {
	comp := createTestComponentWithMockKV(t)

	msg := &mockNATSMsg{
		data: []byte(``), // Empty request
	}

	// Handle capabilities query
	comp.handleCapabilities(msg)

	// Verify response (should still work with empty request)
	require.NotNil(t, msg.response, "should have response")

	var caps component.QueryCapabilities
	err := json.Unmarshal(msg.response, &caps)
	require.NoError(t, err, "response should be valid QueryCapabilities JSON")

	assert.Equal(t, "graph-ingest", caps.Component)
}

func TestComponent_HandleCapabilities_ReturnsAllQueryOperations(t *testing.T) {
	comp := createTestComponentWithMockKV(t)

	msg := &mockNATSMsg{
		data: []byte(`{}`),
	}

	// Handle capabilities query
	comp.handleCapabilities(msg)

	// Verify response
	require.NotNil(t, msg.response, "should have response")

	var caps component.QueryCapabilities
	err := json.Unmarshal(msg.response, &caps)
	require.NoError(t, err, "response should be valid QueryCapabilities JSON")

	// Should have at least entity and batch queries
	operations := make(map[string]bool)
	for _, q := range caps.Queries {
		operations[q.Operation] = true
	}

	assert.True(t, operations["getEntity"], "should have getEntity operation")
	assert.True(t, operations["getBatch"], "should have getBatch operation")
}

func TestComponent_HandleCapabilities_SchemasMatchActualBehavior(t *testing.T) {
	comp := createTestComponentWithMockKV(t)

	msg := &mockNATSMsg{
		data: []byte(`{}`),
	}

	// Handle capabilities query
	comp.handleCapabilities(msg)

	// Verify response
	require.NotNil(t, msg.response, "should have response")

	var caps component.QueryCapabilities
	err := json.Unmarshal(msg.response, &caps)
	require.NoError(t, err, "response should be valid QueryCapabilities JSON")

	// Verify each query capability
	for _, q := range caps.Queries {
		t.Run(q.Operation, func(t *testing.T) {
			// Subject should be graph.ingest.query.*
			assert.True(t, len(q.Subject) > 0, "subject should not be empty")
			assert.Contains(t, q.Subject, "graph.ingest.query", "subject should start with graph.ingest.query")

			// Request and response schemas should be defined
			assert.NotNil(t, q.RequestSchema, "request schema should be defined")
			assert.NotNil(t, q.ResponseSchema, "response schema should be defined")

			// Schemas should be valid JSON
			_, err := json.Marshal(q.RequestSchema)
			assert.NoError(t, err, "request schema should be valid JSON")

			_, err = json.Marshal(q.ResponseSchema)
			assert.NoError(t, err, "response schema should be valid JSON")
		})
	}
}

// ====================================================================================
// Integration Test Requirements (for Builder)
// ====================================================================================
// Builder must create integration tests covering:
// 1. Query handlers with real NATS JetStream connection
// 2. handleQueryEntity with real KV bucket operations
// 3. handleQueryBatch with real KV bucket operations
// 4. handleCapabilities over real NATS request/reply
// 5. Context timeout behavior with actual network operations
// 6. Concurrent query requests
// ====================================================================================

// ====================================================================================
// Mock NATS Message
// ====================================================================================

type mockNATSMsg struct {
	data     []byte
	response []byte
	subject  string
}

func (m *mockNATSMsg) Data() []byte {
	return m.data
}

func (m *mockNATSMsg) Subject() string {
	if m.subject == "" {
		return "test.subject"
	}
	return m.subject
}

func (m *mockNATSMsg) Reply() string {
	return "test.reply"
}

func (m *mockNATSMsg) Respond(data []byte) error {
	m.response = data
	return nil
}

func (m *mockNATSMsg) RespondMsg(msg *nats.Msg) error {
	m.response = msg.Data
	return nil
}

func (m *mockNATSMsg) Header() nats.Header {
	return nats.Header{}
}

func (m *mockNATSMsg) Ack() error {
	return nil
}

func (m *mockNATSMsg) AckSync() error {
	return nil
}

func (m *mockNATSMsg) DoubleAck(ctx context.Context) error {
	return nil
}

func (m *mockNATSMsg) InProgress() error {
	return nil
}

func (m *mockNATSMsg) Nak() error {
	return nil
}

func (m *mockNATSMsg) NakWithDelay(delay time.Duration) error {
	return nil
}

func (m *mockNATSMsg) Term() error {
	return nil
}

func (m *mockNATSMsg) Metadata() (*jetstream.MsgMetadata, error) {
	return &jetstream.MsgMetadata{}, nil
}

// ====================================================================================
// Helper Functions
// ====================================================================================

// formatEntityID creates a valid entity ID with a numeric suffix
func formatEntityID(prefix string, num int) string {
	return fmt.Sprintf("%s.%03d", prefix, num)
}
