// Code generated by Tester Agent. DO NOT EDIT.
// Task: chat-redesign / Phase 1 — Generalize Types and Store
// Builder must make these tests pass without modification.

import { describe, it, expect } from "vitest";
import type {
  MessageAttachment,
  FlowAttachment,
  SearchResultAttachment,
  EntityDetailAttachment,
  ErrorAttachment,
  ChatPageContext,
  FlowBuilderContext,
  DataViewContext,
  ChatMessage,
  ContextChip,
  ContextChipKind,
  ChatRequest,
  ChatIntent,
} from "$lib/types/chat";

// ---------------------------------------------------------------------------
// Helpers: constructors that must be valid at compile time and runtime
// ---------------------------------------------------------------------------

function makeFlowAttachment(
  overrides: Partial<FlowAttachment> = {},
): FlowAttachment {
  return {
    kind: "flow",
    flow: { nodes: [], connections: [] },
    ...overrides,
  };
}

function makeSearchResultAttachment(
  overrides: Partial<SearchResultAttachment> = {},
): SearchResultAttachment {
  return {
    kind: "search-result",
    query: "drones near border",
    entityIds: ["e1", "e2"],
    count: 2,
    durationMs: 42,
    ...overrides,
  };
}

function makeEntityDetailAttachment(
  overrides: Partial<EntityDetailAttachment> = {},
): EntityDetailAttachment {
  return {
    kind: "entity-detail",
    entityId: "entity:org:abc:1",
    summary: "ABC Corporation — defense contractor",
    propertyCount: 12,
    relationshipCount: 7,
    ...overrides,
  };
}

function makeErrorAttachment(
  overrides: Partial<ErrorAttachment> = {},
): ErrorAttachment {
  return {
    kind: "error",
    code: "TOOL_FAILED",
    message: "The search tool timed out.",
    ...overrides,
  };
}

function makeFlowBuilderContext(
  overrides: Partial<FlowBuilderContext> = {},
): FlowBuilderContext {
  return {
    page: "flow-builder",
    flowId: "flow-1",
    flowName: "My Pipeline",
    nodes: [],
    connections: [],
    ...overrides,
  };
}

function makeDataViewContext(
  overrides: Partial<DataViewContext> = {},
): DataViewContext {
  return {
    page: "data-view",
    flowId: "flow-1",
    entityCount: 50,
    selectedEntityId: null,
    filters: {} as DataViewContext["filters"],
    ...overrides,
  };
}

function makeContextChip(overrides: Partial<ContextChip> = {}): ContextChip {
  return {
    id: "chip-1",
    kind: "entity",
    label: "ABC Corp",
    value: "entity:org:abc:1",
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// MessageAttachment — discriminated union
// ---------------------------------------------------------------------------

describe("MessageAttachment — FlowAttachment", () => {
  it("has kind='flow'", () => {
    const a = makeFlowAttachment();
    expect(a.kind).toBe("flow");
  });

  it("carries a flow payload", () => {
    const a = makeFlowAttachment({ flow: { nodes: [], connections: [] } });
    expect(a.flow).toBeDefined();
  });

  it("diff is optional", () => {
    const withoutDiff = makeFlowAttachment();
    expect(withoutDiff.diff).toBeUndefined();

    const withDiff = makeFlowAttachment({
      diff: {
        nodesAdded: ["n1"],
        nodesRemoved: [],
        nodesModified: [],
        connectionsAdded: 1,
        connectionsRemoved: 0,
      },
    });
    expect(withDiff.diff?.nodesAdded).toContain("n1");
  });

  it("applied defaults to undefined (not yet applied)", () => {
    const a = makeFlowAttachment();
    expect(a.applied).toBeUndefined();
  });

  it("applied can be set to true", () => {
    const a = makeFlowAttachment({ applied: true });
    expect(a.applied).toBe(true);
  });

  it("validationResult is optional", () => {
    const a = makeFlowAttachment();
    expect(a.validationResult).toBeUndefined();
  });
});

describe("MessageAttachment — SearchResultAttachment", () => {
  it("has kind='search-result'", () => {
    const a = makeSearchResultAttachment();
    expect(a.kind).toBe("search-result");
  });

  it("carries query, entityIds, count, durationMs", () => {
    const a = makeSearchResultAttachment({
      query: "missiles",
      entityIds: ["e1", "e2", "e3"],
      count: 3,
      durationMs: 123,
    });
    expect(a.query).toBe("missiles");
    expect(a.entityIds).toHaveLength(3);
    expect(a.count).toBe(3);
    expect(a.durationMs).toBe(123);
  });

  it("communitySummaries is optional", () => {
    const a = makeSearchResultAttachment();
    expect(a.communitySummaries).toBeUndefined();

    const withSummaries = makeSearchResultAttachment({
      communitySummaries: [
        { communityId: "c1", text: "Defense industry cluster" },
      ],
    });
    expect(withSummaries.communitySummaries).toHaveLength(1);
    expect(withSummaries.communitySummaries![0].communityId).toBe("c1");
  });
});

describe("MessageAttachment — EntityDetailAttachment", () => {
  it("has kind='entity-detail'", () => {
    const a = makeEntityDetailAttachment();
    expect(a.kind).toBe("entity-detail");
  });

  it("carries entityId, summary, propertyCount, relationshipCount", () => {
    const a = makeEntityDetailAttachment({
      entityId: "entity:person:jane:1",
      summary: "Jane Doe — analyst",
      propertyCount: 5,
      relationshipCount: 10,
    });
    expect(a.entityId).toBe("entity:person:jane:1");
    expect(a.summary).toBe("Jane Doe — analyst");
    expect(a.propertyCount).toBe(5);
    expect(a.relationshipCount).toBe(10);
  });
});

describe("MessageAttachment — ErrorAttachment", () => {
  it("has kind='error'", () => {
    const a = makeErrorAttachment();
    expect(a.kind).toBe("error");
  });

  it("carries code and message", () => {
    const a = makeErrorAttachment({
      code: "RATE_LIMIT",
      message: "Too many requests",
    });
    expect(a.code).toBe("RATE_LIMIT");
    expect(a.message).toBe("Too many requests");
  });
});

// ---------------------------------------------------------------------------
// MessageAttachment — discriminated union narrowing (exhaustive switch)
// ---------------------------------------------------------------------------

describe("MessageAttachment — discriminated union narrowing", () => {
  it.each([
    {
      attachment: makeFlowAttachment() as MessageAttachment,
      expectedKind: "flow",
    },
    {
      attachment: makeSearchResultAttachment() as MessageAttachment,
      expectedKind: "search-result",
    },
    {
      attachment: makeEntityDetailAttachment() as MessageAttachment,
      expectedKind: "entity-detail",
    },
    {
      attachment: makeErrorAttachment() as MessageAttachment,
      expectedKind: "error",
    },
  ])(
    "kind '$expectedKind' narrows correctly",
    ({ attachment, expectedKind }) => {
      // Test that the kind discriminant is the only one on each value
      expect(attachment.kind).toBe(expectedKind);

      // Verify narrowing works at runtime via exhaustive switch-like dispatch
      let dispatched = false;
      switch (attachment.kind) {
        case "flow":
          dispatched = attachment.kind === "flow";
          break;
        case "search-result":
          dispatched = attachment.kind === "search-result";
          break;
        case "entity-detail":
          dispatched = attachment.kind === "entity-detail";
          break;
        case "error":
          dispatched = attachment.kind === "error";
          break;
      }
      expect(dispatched).toBe(true);
    },
  );
});

// ---------------------------------------------------------------------------
// ChatPageContext — discriminated union
// ---------------------------------------------------------------------------

describe("ChatPageContext — FlowBuilderContext", () => {
  it("has page='flow-builder'", () => {
    const ctx = makeFlowBuilderContext();
    expect(ctx.page).toBe("flow-builder");
  });

  it("carries flowId, flowName, nodes, connections", () => {
    const ctx = makeFlowBuilderContext({
      flowId: "flow-42",
      flowName: "NATS Pipeline",
      nodes: [
        {
          id: "n1",
          component: "nats_source",
          type: "input",
          name: "NATS Source",
          position: { x: 0, y: 0 },
          config: {},
        },
      ],
      connections: [],
    });
    expect(ctx.flowId).toBe("flow-42");
    expect(ctx.flowName).toBe("NATS Pipeline");
    expect(ctx.nodes).toHaveLength(1);
    expect(ctx.connections).toHaveLength(0);
  });
});

describe("ChatPageContext — DataViewContext", () => {
  it("has page='data-view'", () => {
    const ctx = makeDataViewContext();
    expect(ctx.page).toBe("data-view");
  });

  it("carries flowId, entityCount, selectedEntityId, filters", () => {
    const ctx = makeDataViewContext({
      flowId: "flow-1",
      entityCount: 100,
      selectedEntityId: "entity:person:alice:1",
    });
    expect(ctx.flowId).toBe("flow-1");
    expect(ctx.entityCount).toBe(100);
    expect(ctx.selectedEntityId).toBe("entity:person:alice:1");
  });

  it("selectedEntityId can be null (nothing selected)", () => {
    const ctx = makeDataViewContext({ selectedEntityId: null });
    expect(ctx.selectedEntityId).toBeNull();
  });
});

describe("ChatPageContext — discriminant narrowing", () => {
  it.each([
    {
      ctx: makeFlowBuilderContext() as ChatPageContext,
      expectedPage: "flow-builder",
    },
    {
      ctx: makeDataViewContext() as ChatPageContext,
      expectedPage: "data-view",
    },
  ])(
    "page '$expectedPage' narrows to the correct shape",
    ({ ctx, expectedPage }) => {
      expect(ctx.page).toBe(expectedPage);

      let flowId: string | undefined;
      if (ctx.page === "flow-builder") {
        flowId = ctx.flowId;
      } else if (ctx.page === "data-view") {
        flowId = ctx.flowId;
      }
      expect(flowId).toBeDefined();
    },
  );
});

// ---------------------------------------------------------------------------
// ChatMessage — new shape with attachments
// ---------------------------------------------------------------------------

describe("ChatMessage — attachments field", () => {
  it("attachments is optional (absent for user messages)", () => {
    const msg: ChatMessage = {
      id: "m1",
      role: "user",
      content: "hello",
      timestamp: new Date(),
    };
    expect(msg.attachments).toBeUndefined();
  });

  it("assistant message can carry multiple attachments", () => {
    const msg: ChatMessage = {
      id: "m2",
      role: "assistant",
      content: "Here are the results.",
      timestamp: new Date(),
      attachments: [makeSearchResultAttachment(), makeEntityDetailAttachment()],
    };
    expect(msg.attachments).toHaveLength(2);
    expect(msg.attachments![0].kind).toBe("search-result");
    expect(msg.attachments![1].kind).toBe("entity-detail");
  });

  it("assistant message can carry a flow attachment", () => {
    const msg: ChatMessage = {
      id: "m3",
      role: "assistant",
      content: "Here is your flow.",
      timestamp: new Date(),
      attachments: [makeFlowAttachment()],
    };
    expect(msg.attachments).toHaveLength(1);
    expect(msg.attachments![0].kind).toBe("flow");
  });

  it("assistant message can carry an error attachment", () => {
    const msg: ChatMessage = {
      id: "m4",
      role: "assistant",
      content: "Something went wrong.",
      timestamp: new Date(),
      attachments: [makeErrorAttachment()],
    };
    expect(msg.attachments![0].kind).toBe("error");
  });

  it("attachments can be an empty array", () => {
    const msg: ChatMessage = {
      id: "m5",
      role: "assistant",
      content: "No tools needed.",
      timestamp: new Date(),
      attachments: [],
    };
    expect(msg.attachments).toHaveLength(0);
  });
});

describe("ChatMessage — chips field", () => {
  it("chips is optional", () => {
    const msg: ChatMessage = {
      id: "m1",
      role: "user",
      content: "tell me about this entity",
      timestamp: new Date(),
    };
    expect(msg.chips).toBeUndefined();
  });

  it("chips can carry context chips snapshotted at send time", () => {
    const msg: ChatMessage = {
      id: "m2",
      role: "user",
      content: "tell me about this entity",
      timestamp: new Date(),
      chips: [makeContextChip()],
    };
    expect(msg.chips).toHaveLength(1);
    expect(msg.chips![0].kind).toBe("entity");
  });
});

// ---------------------------------------------------------------------------
// ChatMessage — OLD fields (flow/flowDiff/applied) MUST NOT exist
// ---------------------------------------------------------------------------

describe("ChatMessage — old flow fields removed", () => {
  it("ChatMessage type does not have a top-level 'flow' field", () => {
    const msg: ChatMessage = {
      id: "m1",
      role: "assistant",
      content: "done",
      timestamp: new Date(),
    };
    // If the old field were present, this would be valid — but it should not be.
    // We verify at runtime that accessing it returns undefined (field does not exist).
    expect((msg as Record<string, unknown>)["flow"]).toBeUndefined();
  });

  it("ChatMessage type does not have a top-level 'flowDiff' field", () => {
    const msg: ChatMessage = {
      id: "m1",
      role: "assistant",
      content: "done",
      timestamp: new Date(),
    };
    expect((msg as Record<string, unknown>)["flowDiff"]).toBeUndefined();
  });

  it("ChatMessage type does not have a top-level 'applied' field", () => {
    const msg: ChatMessage = {
      id: "m1",
      role: "assistant",
      content: "done",
      timestamp: new Date(),
    };
    expect((msg as Record<string, unknown>)["applied"]).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// ContextChip
// ---------------------------------------------------------------------------

describe("ContextChip", () => {
  const validKinds: ContextChipKind[] = [
    "entity",
    "component",
    "flow",
    "community",
    "custom",
  ];

  it.each(validKinds)("kind '%s' is a valid ContextChipKind", (kind) => {
    const chip = makeContextChip({ kind });
    expect(chip.kind).toBe(kind);
  });

  it("carries id, kind, label, value", () => {
    const chip = makeContextChip({
      id: "chip-42",
      kind: "component",
      label: "NATS Source",
      value: "node-nats-1",
    });
    expect(chip.id).toBe("chip-42");
    expect(chip.kind).toBe("component");
    expect(chip.label).toBe("NATS Source");
    expect(chip.value).toBe("node-nats-1");
  });

  it("metadata is optional", () => {
    const chip = makeContextChip();
    expect(chip.metadata).toBeUndefined();

    const withMeta = makeContextChip({ metadata: { schema: "v2" } });
    expect(withMeta.metadata?.["schema"]).toBe("v2");
  });
});

// ---------------------------------------------------------------------------
// ChatRequest — new shape (context replaces currentFlow)
// ---------------------------------------------------------------------------

describe("ChatRequest — new shape", () => {
  it("has messages, context, chips fields", () => {
    const req: ChatRequest = {
      messages: [{ role: "user", content: "search for drones" }],
      context: makeFlowBuilderContext(),
      chips: [],
    };
    expect(req.messages).toHaveLength(1);
    expect(req.context.page).toBe("flow-builder");
    expect(req.chips).toHaveLength(0);
  });

  it("intent is optional", () => {
    const req: ChatRequest = {
      messages: [{ role: "user", content: "hello" }],
      context: makeFlowBuilderContext(),
      chips: [],
    };
    expect(req.intent).toBeUndefined();
  });

  it("intent can be set to a valid ChatIntent", () => {
    const intents: ChatIntent[] = [
      "general",
      "flow-create",
      "search",
      "explain",
      "debug",
      "health",
    ];

    for (const intent of intents) {
      const req: ChatRequest = {
        messages: [],
        context: makeDataViewContext(),
        chips: [],
        intent,
      };
      expect(req.intent).toBe(intent);
    }
  });

  it("does NOT have a currentFlow field", () => {
    const req: ChatRequest = {
      messages: [],
      context: makeFlowBuilderContext(),
      chips: [],
    };
    expect((req as Record<string, unknown>)["currentFlow"]).toBeUndefined();
  });

  it("accepts chips with multiple kinds", () => {
    const req: ChatRequest = {
      messages: [{ role: "user", content: "compare these" }],
      context: makeDataViewContext(),
      chips: [
        makeContextChip({ kind: "entity", value: "e1" }),
        makeContextChip({ id: "chip-2", kind: "community", value: "c1" }),
      ],
    };
    expect(req.chips).toHaveLength(2);
    expect(req.chips[0].kind).toBe("entity");
    expect(req.chips[1].kind).toBe("community");
  });

  it("accepts DataViewContext as context", () => {
    const req: ChatRequest = {
      messages: [],
      context: makeDataViewContext({ entityCount: 200 }),
      chips: [],
    };
    expect(req.context.page).toBe("data-view");
    if (req.context.page === "data-view") {
      expect(req.context.entityCount).toBe(200);
    }
  });
});
