// Code generated by Tester Agent. DO NOT EDIT.
// Task: Chat UI Phase 2 — ChatPanel component tests
// Builder must make these tests pass without modification.
//
// Migration note (chat-redesign Phase 1): The test that passes message.flow
// has been updated to use attachments: [{ kind: "flow", flow }] instead,
// as the top-level flow field was removed from ChatMessage.

import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/svelte";
import userEvent from "@testing-library/user-event";
import ChatPanel from "./ChatPanel.svelte";
import type { ChatMessage, FlowAttachment } from "$lib/types/chat";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function makeMessage(
  overrides: Partial<ChatMessage> & { id: string },
): ChatMessage {
  return {
    role: "user",
    content: "Hello",
    timestamp: new Date("2026-03-08T12:00:00Z"),
    ...overrides,
  };
}

function defaultProps() {
  return {
    messages: [] as ChatMessage[],
    isStreaming: false,
    streamingContent: "",
    error: null as string | null,
    onSubmit: vi.fn(),
    onCancel: vi.fn(),
    onApplyFlow: vi.fn(),
    onLoadJson: vi.fn(),
    onExportJson: vi.fn(),
    onNewChat: vi.fn(),
  };
}

// ---------------------------------------------------------------------------
// Presence and data-testid
// ---------------------------------------------------------------------------

describe("ChatPanel — presence", () => {
  it("should have data-testid='chat-panel'", () => {
    render(ChatPanel, { props: defaultProps() });

    expect(screen.getByTestId("chat-panel")).toBeInTheDocument();
  });

  it("should render the ChatToolbar", () => {
    render(ChatPanel, { props: defaultProps() });

    expect(screen.getByTestId("chat-toolbar")).toBeInTheDocument();
  });

  it("should render the ChatMessageList", () => {
    render(ChatPanel, { props: defaultProps() });

    expect(screen.getByTestId("chat-message-list")).toBeInTheDocument();
  });

  it("should render the ChatInput", () => {
    render(ChatPanel, { props: defaultProps() });

    expect(screen.getByTestId("chat-input")).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Error display
// ---------------------------------------------------------------------------

describe("ChatPanel — error display", () => {
  it("should show error alert when error prop is set", () => {
    render(ChatPanel, {
      props: { ...defaultProps(), error: "Something went wrong" },
    });

    expect(screen.getByRole("alert")).toBeInTheDocument();
    expect(screen.getByRole("alert")).toHaveTextContent("Something went wrong");
  });

  it("should NOT show alert when error is null", () => {
    render(ChatPanel, { props: { ...defaultProps(), error: null } });

    expect(screen.queryByRole("alert")).not.toBeInTheDocument();
  });

  it("should NOT show alert when error is empty string", () => {
    render(ChatPanel, { props: { ...defaultProps(), error: "" } });

    expect(screen.queryByRole("alert")).not.toBeInTheDocument();
  });

  it("should display the exact error message text", () => {
    const errorMessages = [
      "Connection refused",
      "API rate limit exceeded",
      "Internal server error",
    ];

    for (const msg of errorMessages) {
      const { unmount } = render(ChatPanel, {
        props: { ...defaultProps(), error: msg },
      });

      expect(screen.getByRole("alert")).toHaveTextContent(msg);
      unmount();
    }
  });
});

// ---------------------------------------------------------------------------
// Messages passthrough
// ---------------------------------------------------------------------------

describe("ChatPanel — messages passthrough", () => {
  it("should pass messages to ChatMessageList", () => {
    const messages = [
      makeMessage({ id: "1", content: "First message" }),
      makeMessage({ id: "2", content: "Second message" }),
    ];

    render(ChatPanel, { props: { ...defaultProps(), messages } });

    expect(screen.getByText("First message")).toBeInTheDocument();
    expect(screen.getByText("Second message")).toBeInTheDocument();
  });

  it("should show empty state when messages is empty", () => {
    render(ChatPanel, { props: { ...defaultProps(), messages: [] } });

    expect(screen.getByTestId("chat-empty-state")).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// isStreaming passthrough
// ---------------------------------------------------------------------------

describe("ChatPanel — isStreaming passthrough", () => {
  it("should pass isStreaming=true to ChatInput (shows cancel button)", () => {
    render(ChatPanel, {
      props: { ...defaultProps(), isStreaming: true, streamingContent: "..." },
    });

    expect(screen.getByTestId("chat-cancel")).toBeInTheDocument();
    expect(screen.queryByTestId("chat-submit")).not.toBeInTheDocument();
  });

  it("should pass isStreaming=false to ChatInput (shows submit button)", () => {
    render(ChatPanel, {
      props: { ...defaultProps(), isStreaming: false },
    });

    expect(screen.getByTestId("chat-submit")).toBeInTheDocument();
    expect(screen.queryByTestId("chat-cancel")).not.toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Callback passthrough
// ---------------------------------------------------------------------------

describe("ChatPanel — callback passthrough", () => {
  it("should call onSubmit when the chat input submits", async () => {
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    render(ChatPanel, { props: { ...defaultProps(), onSubmit } });

    const textarea = screen.getByTestId("chat-input");
    await user.type(textarea, "Build a flow{Enter}");

    expect(onSubmit).toHaveBeenCalledOnce();
    expect(onSubmit).toHaveBeenCalledWith("Build a flow");
  });

  it("should call onCancel when the cancel button is clicked during streaming", async () => {
    const onCancel = vi.fn();
    const user = userEvent.setup();

    render(ChatPanel, {
      props: { ...defaultProps(), onCancel, isStreaming: true },
    });

    await user.click(screen.getByTestId("chat-cancel"));

    expect(onCancel).toHaveBeenCalledOnce();
  });

  it("should call onNewChat when New Chat is clicked in the toolbar", async () => {
    const onNewChat = vi.fn();
    const user = userEvent.setup();

    render(ChatPanel, { props: { ...defaultProps(), onNewChat } });

    await user.click(screen.getByTestId("chat-new-chat"));

    expect(onNewChat).toHaveBeenCalledOnce();
  });

  it("should call onExportJson when Export JSON is clicked in the toolbar", async () => {
    const onExportJson = vi.fn();
    const user = userEvent.setup();

    render(ChatPanel, { props: { ...defaultProps(), onExportJson } });

    await user.click(screen.getByTestId("chat-export-json"));

    expect(onExportJson).toHaveBeenCalledOnce();
  });

  it("should call onApplyFlow with message id when Apply to Canvas is clicked", async () => {
    const onApplyFlow = vi.fn();
    const user = userEvent.setup();
    // Migration: flow is now in attachments[] as a FlowAttachment
    const flowAttachment: FlowAttachment = {
      kind: "flow",
      flow: { nodes: [], connections: [] },
    };

    render(ChatPanel, {
      props: {
        ...defaultProps(),
        onApplyFlow,
        messages: [
          makeMessage({
            id: "msg-99",
            role: "assistant",
            content: "Here is your flow",
            attachments: [flowAttachment],
          }),
        ],
      },
    });

    await user.click(screen.getByTestId("apply-flow-button"));

    expect(onApplyFlow).toHaveBeenCalledWith("msg-99");
  });
});

// ---------------------------------------------------------------------------
// Streaming content passthrough
// ---------------------------------------------------------------------------

describe("ChatPanel — streaming content", () => {
  it("should show streaming message when isStreaming and streamingContent is set", () => {
    render(ChatPanel, {
      props: {
        ...defaultProps(),
        isStreaming: true,
        streamingContent: "Building your flow...",
      },
    });

    expect(screen.getByTestId("chat-message-streaming")).toBeInTheDocument();
    expect(screen.getByTestId("chat-message-streaming")).toHaveTextContent(
      "Building your flow...",
    );
  });
});
