// Code generated by Reviewer Agent. DO NOT EDIT.
// Attack tests — permanent CI fixtures.
// Phase 6: FlowStatusCard adversarial inputs.

import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/svelte";
import userEvent from "@testing-library/user-event";
import FlowStatusCard from "./FlowStatusCard.svelte";
import type { FlowStatusAttachment } from "$lib/types/chat";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeAttachment(
  overrides: Partial<FlowStatusAttachment> = {},
): FlowStatusAttachment {
  return {
    kind: "flow-status",
    flowId: "flow-abc-123",
    flowName: "Sensor Ingestion Pipeline",
    state: "running",
    nodeCount: 4,
    connectionCount: 3,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// ATTACK: undefined / missing props
// ---------------------------------------------------------------------------

describe("ATTACK: FlowStatusCard — undefined props", () => {
  it("does not throw with all optional fields absent", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: {
          attachment: makeAttachment({ warnings: undefined }),
        },
      }),
    ).not.toThrow();
  });

  it("does not throw when onViewFlow is not provided", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: { attachment: makeAttachment() },
      }),
    ).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// ATTACK: XSS in flowName
// ---------------------------------------------------------------------------

describe("ATTACK: FlowStatusCard — XSS in flowName", () => {
  it("renders without throwing when flowName contains a script tag", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: {
          attachment: makeAttachment({
            flowName: '<script>alert("xss")</script>',
          }),
        },
      }),
    ).not.toThrow();
  });

  it("does not inject a live script element from flowName", () => {
    const { container } = render(FlowStatusCard, {
      props: {
        attachment: makeAttachment({
          flowName: '<script>alert("xss")</script>',
        }),
      },
    });

    expect(container.querySelectorAll("script").length).toBe(0);
  });

  it("renders without throwing when flowName contains an img onerror payload", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: {
          attachment: makeAttachment({
            flowName: "<img src=x onerror=alert(1)>",
          }),
        },
      }),
    ).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// ATTACK: XSS in warnings
// ---------------------------------------------------------------------------

describe("ATTACK: FlowStatusCard — XSS in warnings", () => {
  it("renders without throwing when a warning contains a script tag", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: {
          attachment: makeAttachment({
            warnings: ['<script>alert("warning-xss")</script>'],
          }),
        },
      }),
    ).not.toThrow();
  });

  it("does not inject live script elements from warnings", () => {
    const { container } = render(FlowStatusCard, {
      props: {
        attachment: makeAttachment({
          warnings: [
            '<script>alert(1)</script>',
            '<img src=x onerror=alert(2)>',
          ],
        }),
      },
    });

    expect(container.querySelectorAll("script").length).toBe(0);
  });

  it("renders without throwing when warnings contain HTML attribute injection", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: {
          attachment: makeAttachment({
            warnings: ['" onmouseover="alert(1)"'],
          }),
        },
      }),
    ).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// ATTACK: very many warnings
// ---------------------------------------------------------------------------

describe("ATTACK: FlowStatusCard — very many warnings", () => {
  it("renders without throwing when there are 1000 warnings", () => {
    const warnings = Array.from({ length: 1000 }, (_, i) => `Warning ${i}`);
    expect(() =>
      render(FlowStatusCard, {
        props: { attachment: makeAttachment({ warnings }) },
      }),
    ).not.toThrow();
  });

  it("card renders in the DOM with 1000 warnings", () => {
    const warnings = Array.from({ length: 1000 }, (_, i) => `Warning ${i}`);
    render(FlowStatusCard, {
      props: { attachment: makeAttachment({ warnings }) },
    });
    expect(screen.getByTestId("flow-status-card")).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// ATTACK: missing / null fields
// ---------------------------------------------------------------------------

describe("ATTACK: FlowStatusCard — missing / null fields", () => {
  it("renders without throwing when flowName is empty string", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: { attachment: makeAttachment({ flowName: "" }) },
      }),
    ).not.toThrow();
  });

  it("renders without throwing when state is empty string", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: { attachment: makeAttachment({ state: "" }) },
      }),
    ).not.toThrow();
  });

  it("renders without throwing when nodeCount is 0 and connectionCount is 0", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: {
          attachment: makeAttachment({ nodeCount: 0, connectionCount: 0 }),
        },
      }),
    ).not.toThrow();
  });

  it("renders without throwing when nodeCount is a very large number", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: {
          attachment: makeAttachment({ nodeCount: Number.MAX_SAFE_INTEGER }),
        },
      }),
    ).not.toThrow();
  });

  it("renders without throwing when warnings is an empty array", () => {
    expect(() =>
      render(FlowStatusCard, {
        props: { attachment: makeAttachment({ warnings: [] }) },
      }),
    ).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// ATTACK: rapid clicks on flow name button
// ---------------------------------------------------------------------------

describe("ATTACK: FlowStatusCard — rapid clicks on flow name", () => {
  it("calls onViewFlow once per click under rapid interaction", async () => {
    const onViewFlow = vi.fn();
    const user = userEvent.setup();

    render(FlowStatusCard, {
      props: {
        attachment: makeAttachment({ flowId: "flow-rapid" }),
        onViewFlow,
      },
    });

    const button = screen.getByTestId("flow-status-flow-name");

    // Three rapid clicks
    await user.click(button);
    await user.click(button);
    await user.click(button);

    expect(onViewFlow).toHaveBeenCalledTimes(3);
    expect(onViewFlow).toHaveBeenCalledWith("flow-rapid");
  });

  it("does not throw on rapid clicks when onViewFlow is not provided", async () => {
    const user = userEvent.setup();

    render(FlowStatusCard, {
      props: { attachment: makeAttachment() },
    });

    const button = screen.getByTestId("flow-status-flow-name");

    await expect(
      Promise.all([user.click(button), user.click(button), user.click(button)]),
    ).resolves.not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// ATTACK: very long flowId passed to onViewFlow
// ---------------------------------------------------------------------------

describe("ATTACK: FlowStatusCard — very long flowId", () => {
  it("does not throw when flowId is a very long string", async () => {
    const onViewFlow = vi.fn();
    const user = userEvent.setup();
    const longId = "flow-" + "x".repeat(10000);

    render(FlowStatusCard, {
      props: {
        attachment: makeAttachment({ flowId: longId }),
        onViewFlow,
      },
    });

    await user.click(screen.getByTestId("flow-status-flow-name"));

    expect(onViewFlow).toHaveBeenCalledWith(longId);
  });
});
