// Code generated by Tester Agent. DO NOT EDIT.
// Task: agentic package greenfield tests
// Builder must make these tests pass without modification.

package agentic_test

import (
	"encoding/json"
	"testing"

	"github.com/c360/semstreams/agentic"
)

func TestToolDefinition_JSONRoundTrip(t *testing.T) {
	tests := []struct {
		name string
		tool agentic.ToolDefinition
	}{
		{
			name: "simple tool",
			tool: agentic.ToolDefinition{
				Name:        "graph_query",
				Description: "Query the knowledge graph",
				Parameters: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"query": map[string]any{
							"type":        "string",
							"description": "SPARQL query",
						},
					},
					"required": []string{"query"},
				},
			},
		},
		{
			name: "complex tool with multiple parameters",
			tool: agentic.ToolDefinition{
				Name:        "file_write",
				Description: "Write content to a file",
				Parameters: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"path": map[string]any{
							"type":        "string",
							"description": "File path",
						},
						"content": map[string]any{
							"type":        "string",
							"description": "File content",
						},
						"mode": map[string]any{
							"type":        "string",
							"description": "File mode",
							"enum":        []string{"overwrite", "append"},
						},
					},
					"required": []string{"path", "content"},
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := json.Marshal(tt.tool)
			if err != nil {
				t.Fatalf("Marshal failed: %v", err)
			}

			var decoded agentic.ToolDefinition
			if err := json.Unmarshal(data, &decoded); err != nil {
				t.Fatalf("Unmarshal failed: %v", err)
			}

			if decoded.Name != tt.tool.Name {
				t.Errorf("Name = %v, want %v", decoded.Name, tt.tool.Name)
			}
			if decoded.Description != tt.tool.Description {
				t.Errorf("Description = %v, want %v", decoded.Description, tt.tool.Description)
			}
			if decoded.Parameters == nil {
				t.Errorf("Parameters should not be nil")
			}
		})
	}
}

func TestToolDefinition_Validation(t *testing.T) {
	tests := []struct {
		name    string
		tool    agentic.ToolDefinition
		wantErr bool
		errMsg  string
	}{
		{
			name: "valid tool",
			tool: agentic.ToolDefinition{
				Name:        "graph_query",
				Description: "Query the graph",
				Parameters: map[string]any{
					"type": "object",
				},
			},
			wantErr: false,
		},
		{
			name: "missing name",
			tool: agentic.ToolDefinition{
				Description: "Query the graph",
				Parameters: map[string]any{
					"type": "object",
				},
			},
			wantErr: true,
			errMsg:  "tool name required",
		},
		{
			name: "empty name",
			tool: agentic.ToolDefinition{
				Name:        "",
				Description: "Query the graph",
				Parameters: map[string]any{
					"type": "object",
				},
			},
			wantErr: true,
			errMsg:  "tool name required",
		},
		{
			name: "missing parameters",
			tool: agentic.ToolDefinition{
				Name:        "graph_query",
				Description: "Query the graph",
			},
			wantErr: true,
			errMsg:  "tool parameters required",
		},
		{
			name: "empty parameters",
			tool: agentic.ToolDefinition{
				Name:        "graph_query",
				Description: "Query the graph",
				Parameters:  map[string]any{},
			},
			wantErr: true,
			errMsg:  "tool parameters required",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.tool.Validate()
			if tt.wantErr {
				if err == nil {
					t.Errorf("Validate() expected error, got nil")
					return
				}
				if tt.errMsg != "" && err.Error() != tt.errMsg {
					t.Errorf("Validate() error = %v, want %v", err.Error(), tt.errMsg)
				}
			} else {
				if err != nil {
					t.Errorf("Validate() unexpected error = %v", err)
				}
			}
		})
	}
}

func TestToolCall_JSONRoundTrip(t *testing.T) {
	tests := []struct {
		name string
		call agentic.ToolCall
	}{
		{
			name: "simple call",
			call: agentic.ToolCall{
				ID:   "call-123",
				Name: "graph_query",
				Arguments: map[string]any{
					"query": "SELECT * FROM entities",
				},
			},
		},
		{
			name: "complex call with multiple arguments",
			call: agentic.ToolCall{
				ID:   "call-456",
				Name: "file_write",
				Arguments: map[string]any{
					"path":    "/tmp/test.txt",
					"content": "Hello World",
					"mode":    "overwrite",
				},
			},
		},
		{
			name: "call with nested arguments",
			call: agentic.ToolCall{
				ID:   "call-789",
				Name: "api_request",
				Arguments: map[string]any{
					"url":    "https://api.example.com",
					"method": "POST",
					"headers": map[string]any{
						"Content-Type": "application/json",
					},
					"body": map[string]any{
						"key": "value",
					},
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := json.Marshal(tt.call)
			if err != nil {
				t.Fatalf("Marshal failed: %v", err)
			}

			var decoded agentic.ToolCall
			if err := json.Unmarshal(data, &decoded); err != nil {
				t.Fatalf("Unmarshal failed: %v", err)
			}

			if decoded.ID != tt.call.ID {
				t.Errorf("ID = %v, want %v", decoded.ID, tt.call.ID)
			}
			if decoded.Name != tt.call.Name {
				t.Errorf("Name = %v, want %v", decoded.Name, tt.call.Name)
			}
			if decoded.Arguments == nil {
				t.Errorf("Arguments should not be nil")
			}
		})
	}
}

func TestToolCall_Validation(t *testing.T) {
	tests := []struct {
		name    string
		call    agentic.ToolCall
		wantErr bool
		errMsg  string
	}{
		{
			name: "valid call",
			call: agentic.ToolCall{
				ID:   "call-123",
				Name: "graph_query",
				Arguments: map[string]any{
					"query": "SELECT *",
				},
			},
			wantErr: false,
		},
		{
			name: "missing ID",
			call: agentic.ToolCall{
				Name: "graph_query",
				Arguments: map[string]any{
					"query": "SELECT *",
				},
			},
			wantErr: true,
			errMsg:  "tool call id required",
		},
		{
			name: "empty ID",
			call: agentic.ToolCall{
				ID:   "",
				Name: "graph_query",
				Arguments: map[string]any{
					"query": "SELECT *",
				},
			},
			wantErr: true,
			errMsg:  "tool call id required",
		},
		{
			name: "missing function name",
			call: agentic.ToolCall{
				ID: "call-123",
				Arguments: map[string]any{
					"query": "SELECT *",
				},
			},
			wantErr: true,
			errMsg:  "tool call function name required",
		},
		{
			name: "empty function name",
			call: agentic.ToolCall{
				ID:   "call-123",
				Name: "",
				Arguments: map[string]any{
					"query": "SELECT *",
				},
			},
			wantErr: true,
			errMsg:  "tool call function name required",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.call.Validate()
			if tt.wantErr {
				if err == nil {
					t.Errorf("Validate() expected error, got nil")
					return
				}
				if tt.errMsg != "" && err.Error() != tt.errMsg {
					t.Errorf("Validate() error = %v, want %v", err.Error(), tt.errMsg)
				}
			} else {
				if err != nil {
					t.Errorf("Validate() unexpected error = %v", err)
				}
			}
		})
	}
}

func TestToolResult_JSONRoundTrip(t *testing.T) {
	tests := []struct {
		name   string
		result agentic.ToolResult
	}{
		{
			name: "success result",
			result: agentic.ToolResult{
				CallID:  "call-123",
				Content: "Query returned 42 results",
			},
		},
		{
			name: "error result",
			result: agentic.ToolResult{
				CallID: "call-456",
				Error:  "Query syntax error",
			},
		},
		{
			name: "result with metadata",
			result: agentic.ToolResult{
				CallID:  "call-789",
				Content: "File written successfully",
				Metadata: map[string]any{
					"bytes_written": 1024,
					"path":          "/tmp/test.txt",
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			data, err := json.Marshal(tt.result)
			if err != nil {
				t.Fatalf("Marshal failed: %v", err)
			}

			var decoded agentic.ToolResult
			if err := json.Unmarshal(data, &decoded); err != nil {
				t.Fatalf("Unmarshal failed: %v", err)
			}

			if decoded.CallID != tt.result.CallID {
				t.Errorf("CallID = %v, want %v", decoded.CallID, tt.result.CallID)
			}
			if decoded.Content != tt.result.Content {
				t.Errorf("Content = %v, want %v", decoded.Content, tt.result.Content)
			}
			if decoded.Error != tt.result.Error {
				t.Errorf("Error = %v, want %v", decoded.Error, tt.result.Error)
			}
		})
	}
}

func TestToolResult_Validation(t *testing.T) {
	tests := []struct {
		name    string
		result  agentic.ToolResult
		wantErr bool
		errMsg  string
	}{
		{
			name: "valid result",
			result: agentic.ToolResult{
				CallID:  "call-123",
				Content: "Success",
			},
			wantErr: false,
		},
		{
			name: "missing call ID",
			result: agentic.ToolResult{
				Content: "Success",
			},
			wantErr: true,
			errMsg:  "tool result call_id required",
		},
		{
			name: "empty call ID",
			result: agentic.ToolResult{
				CallID:  "",
				Content: "Success",
			},
			wantErr: true,
			errMsg:  "tool result call_id required",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.result.Validate()
			if tt.wantErr {
				if err == nil {
					t.Errorf("Validate() expected error, got nil")
					return
				}
				if tt.errMsg != "" && err.Error() != tt.errMsg {
					t.Errorf("Validate() error = %v, want %v", err.Error(), tt.errMsg)
				}
			} else {
				if err != nil {
					t.Errorf("Validate() unexpected error = %v", err)
				}
			}
		})
	}
}

func TestValidateToolsAllowed(t *testing.T) {
	tests := []struct {
		name        string
		calls       []agentic.ToolCall
		allowed     []string
		wantErr     bool
		errContains string
	}{
		{
			name: "all tools allowed",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "graph_query"},
				{ID: "call-2", Name: "file_read"},
			},
			allowed: []string{"graph_query", "file_read", "file_write"},
			wantErr: false,
		},
		{
			name: "single tool allowed",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "graph_query"},
			},
			allowed: []string{"graph_query"},
			wantErr: false,
		},
		{
			name:    "empty calls allowed",
			calls:   []agentic.ToolCall{},
			allowed: []string{"graph_query"},
			wantErr: false,
		},
		{
			name:    "nil calls allowed",
			calls:   nil,
			allowed: []string{"graph_query"},
			wantErr: false,
		},
		{
			name: "single disallowed tool",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "file_delete"},
			},
			allowed:     []string{"graph_query", "file_read"},
			wantErr:     true,
			errContains: "file_delete",
		},
		{
			name: "multiple disallowed tools",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "file_delete"},
				{ID: "call-2", Name: "system_exec"},
			},
			allowed:     []string{"graph_query"},
			wantErr:     true,
			errContains: "file_delete",
		},
		{
			name: "mix of allowed and disallowed",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "graph_query"},
				{ID: "call-2", Name: "file_delete"},
				{ID: "call-3", Name: "file_read"},
			},
			allowed:     []string{"graph_query", "file_read"},
			wantErr:     true,
			errContains: "file_delete",
		},
		{
			name: "empty allowed list blocks all",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "graph_query"},
			},
			allowed:     []string{},
			wantErr:     true,
			errContains: "graph_query",
		},
		{
			name: "nil allowed list blocks all",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "graph_query"},
			},
			allowed:     nil,
			wantErr:     true,
			errContains: "graph_query",
		},
		{
			name: "case sensitive matching",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "Graph_Query"},
			},
			allowed:     []string{"graph_query"},
			wantErr:     true,
			errContains: "Graph_Query",
		},
		{
			name: "duplicate tool calls allowed",
			calls: []agentic.ToolCall{
				{ID: "call-1", Name: "graph_query"},
				{ID: "call-2", Name: "graph_query"},
			},
			allowed: []string{"graph_query"},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := agentic.ValidateToolsAllowed(tt.calls, tt.allowed)
			if tt.wantErr {
				if err == nil {
					t.Errorf("ValidateToolsAllowed() expected error, got nil")
					return
				}
				if tt.errContains != "" {
					errMsg := err.Error()
					if len(errMsg) == 0 || errMsg[:1] != errMsg[:1] {
						// Check contains
						found := false
						for i := 0; i <= len(errMsg)-len(tt.errContains); i++ {
							if errMsg[i:i+len(tt.errContains)] == tt.errContains {
								found = true
								break
							}
						}
						if !found {
							t.Errorf("ValidateToolsAllowed() error = %v, want to contain %v", errMsg, tt.errContains)
						}
					}
				}
			} else {
				if err != nil {
					t.Errorf("ValidateToolsAllowed() unexpected error = %v", err)
				}
			}
		})
	}
}
