// Code generated by Tester Agent. DO NOT EDIT.
// Task: External tool registration protocol unit tests
// Builder must make these tests pass without modification.

package agentictools_test

import (
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/c360/semstreams/agentic"
	agentictools "github.com/c360/semstreams/processor/agentic-tools"
)

// TestExternalToolRegistry_RegisterExternalTool tests registering external tools
func TestExternalToolRegistry_RegisterExternalTool(t *testing.T) {
	tests := []struct {
		name        string
		toolName    string
		description string
		provider    string
		params      map[string]interface{}
		wantErr     bool
	}{
		{
			name:        "valid external tool",
			toolName:    "file_read",
			description: "Read a file from disk",
			provider:    "filesystem-provider",
			params: map[string]interface{}{
				"type": "object",
				"properties": map[string]interface{}{
					"path": map[string]interface{}{
						"type": "string",
					},
				},
			},
			wantErr: false,
		},
		{
			name:        "another valid tool",
			toolName:    "graph.query",
			description: "Query the knowledge graph",
			provider:    "graph-provider",
			params: map[string]interface{}{
				"type": "object",
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			registry := agentictools.NewExternalToolRegistry()

			reg := agentictools.ExternalToolRegistration{
				Name:        tt.toolName,
				Description: tt.description,
				Parameters:  tt.params,
				Provider:    tt.provider,
				Timestamp:   time.Now(),
			}

			err := registry.RegisterExternalTool(reg)
			if (err != nil) != tt.wantErr {
				t.Errorf("RegisterExternalTool() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

// TestExternalToolRegistry_RegisterExternalTool_Duplicate tests duplicate tool registration
func TestExternalToolRegistry_RegisterExternalTool_Duplicate(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	reg := agentictools.ExternalToolRegistration{
		Name:        "file_read",
		Description: "Read a file",
		Provider:    "provider-1",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}

	// First registration should succeed
	err := registry.RegisterExternalTool(reg)
	if err != nil {
		t.Fatalf("First RegisterExternalTool() should succeed, got error: %v", err)
	}

	// Same tool from same provider should fail
	err = registry.RegisterExternalTool(reg)
	if err == nil {
		t.Fatal("RegisterExternalTool() with duplicate should return error")
	}

	// Same tool from different provider should succeed (different namespace)
	reg2 := reg
	reg2.Provider = "provider-2"
	err = registry.RegisterExternalTool(reg2)
	if err != nil {
		t.Errorf("RegisterExternalTool() from different provider should succeed, got error: %v", err)
	}
}

// TestExternalToolRegistry_UnregisterTool tests unregistering tools
func TestExternalToolRegistry_UnregisterTool(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register a tool
	reg := agentictools.ExternalToolRegistration{
		Name:        "file_read",
		Description: "Read a file",
		Provider:    "provider-1",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}
	err := registry.RegisterExternalTool(reg)
	if err != nil {
		t.Fatalf("RegisterExternalTool() failed: %v", err)
	}

	// Unregister it
	unreg := agentictools.ToolUnregister{
		Name:     "file_read",
		Provider: "provider-1",
	}
	err = registry.UnregisterTool(unreg)
	if err != nil {
		t.Fatalf("UnregisterTool() should succeed, got error: %v", err)
	}

	// Should not be in list anymore
	tools := registry.ListExternalTools()
	for _, tool := range tools {
		if tool.Name == "file_read" && tool.Provider == "provider-1" {
			t.Error("UnregisterTool() should remove tool from registry")
		}
	}
}

// TestExternalToolRegistry_UnregisterTool_NotFound tests unregistering non-existent tool
func TestExternalToolRegistry_UnregisterTool_NotFound(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	unreg := agentictools.ToolUnregister{
		Name:     "nonexistent",
		Provider: "provider-1",
	}

	// Unregistering non-existent tool should not error (idempotent)
	err := registry.UnregisterTool(unreg)
	if err != nil {
		t.Errorf("UnregisterTool() for non-existent tool should not error, got: %v", err)
	}
}

// TestExternalToolRegistry_ListExternalTools tests listing external tools
func TestExternalToolRegistry_ListExternalTools(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register multiple tools
	tools := []agentictools.ExternalToolRegistration{
		{
			Name:        "file_read",
			Description: "Read a file",
			Provider:    "fs-provider",
			Parameters: map[string]interface{}{
				"type": "object",
			},
			Timestamp: time.Now(),
		},
		{
			Name:        "file_write",
			Description: "Write a file",
			Provider:    "fs-provider",
			Parameters: map[string]interface{}{
				"type": "object",
			},
			Timestamp: time.Now(),
		},
		{
			Name:        "graph.query",
			Description: "Query graph",
			Provider:    "graph-provider",
			Parameters: map[string]interface{}{
				"type": "object",
			},
			Timestamp: time.Now(),
		},
	}

	for _, tool := range tools {
		if err := registry.RegisterExternalTool(tool); err != nil {
			t.Fatalf("RegisterExternalTool() failed: %v", err)
		}
	}

	// List all tools
	allTools := registry.ListExternalTools()

	if len(allTools) != len(tools) {
		t.Errorf("ListExternalTools() count = %d, want %d", len(allTools), len(tools))
	}

	// Verify all tools present
	for _, expected := range tools {
		found := false
		for _, actual := range allTools {
			if actual.Name == expected.Name && actual.Provider == expected.Provider {
				found = true
				if actual.Description != expected.Description {
					t.Errorf("Tool %q description = %q, want %q",
						expected.Name, actual.Description, expected.Description)
				}
				break
			}
		}
		if !found {
			t.Errorf("ListExternalTools() missing tool %q from provider %q",
				expected.Name, expected.Provider)
		}
	}
}

// TestExternalToolRegistry_ListExternalTools_Empty tests listing when empty
func TestExternalToolRegistry_ListExternalTools_Empty(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	tools := registry.ListExternalTools()
	if tools == nil {
		t.Error("ListExternalTools() should return empty slice, not nil")
	}
	if len(tools) != 0 {
		t.Errorf("ListExternalTools() on empty registry should return empty slice, got %d tools", len(tools))
	}
}

// TestExternalToolRegistry_RecordHeartbeat tests recording provider heartbeats
func TestExternalToolRegistry_RecordHeartbeat(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register a tool
	reg := agentictools.ExternalToolRegistration{
		Name:        "file_read",
		Description: "Read a file",
		Provider:    "fs-provider",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}
	err := registry.RegisterExternalTool(reg)
	if err != nil {
		t.Fatalf("RegisterExternalTool() failed: %v", err)
	}

	// Record heartbeat
	heartbeat := agentictools.ToolHeartbeat{
		Provider:  "fs-provider",
		Tools:     []string{"file_read"},
		Timestamp: time.Now(),
	}
	registry.RecordHeartbeat(heartbeat)

	// Provider should be healthy
	if !registry.IsProviderHealthy("fs-provider", 30*time.Second) {
		t.Error("IsProviderHealthy() should return true after recent heartbeat")
	}
}

// TestExternalToolRegistry_IsProviderHealthy_Timeout tests heartbeat timeout
func TestExternalToolRegistry_IsProviderHealthy_Timeout(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register tool
	reg := agentictools.ExternalToolRegistration{
		Name:        "file_read",
		Description: "Read a file",
		Provider:    "fs-provider",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}
	err := registry.RegisterExternalTool(reg)
	if err != nil {
		t.Fatalf("RegisterExternalTool() failed: %v", err)
	}

	// Record old heartbeat
	oldTime := time.Now().Add(-2 * time.Minute)
	heartbeat := agentictools.ToolHeartbeat{
		Provider:  "fs-provider",
		Tools:     []string{"file_read"},
		Timestamp: oldTime,
	}
	registry.RecordHeartbeat(heartbeat)

	// With 30s threshold, old heartbeat should be unhealthy
	if registry.IsProviderHealthy("fs-provider", 30*time.Second) {
		t.Error("IsProviderHealthy() should return false for old heartbeat")
	}

	// With longer threshold, should be healthy
	if !registry.IsProviderHealthy("fs-provider", 3*time.Minute) {
		t.Error("IsProviderHealthy() should return true with longer threshold")
	}
}

// TestExternalToolRegistry_IsProviderHealthy_NoHeartbeat tests provider with no heartbeat
func TestExternalToolRegistry_IsProviderHealthy_NoHeartbeat(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Provider with no heartbeat should be unhealthy
	if registry.IsProviderHealthy("unknown-provider", 30*time.Second) {
		t.Error("IsProviderHealthy() should return false for provider with no heartbeat")
	}
}

// TestExternalToolRegistry_MarkProviderUnavailable tests marking provider unavailable
func TestExternalToolRegistry_MarkProviderUnavailable(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register multiple tools from same provider
	tools := []agentictools.ExternalToolRegistration{
		{
			Name:        "file_read",
			Description: "Read a file",
			Provider:    "fs-provider",
			Parameters: map[string]interface{}{
				"type": "object",
			},
			Timestamp: time.Now(),
		},
		{
			Name:        "file_write",
			Description: "Write a file",
			Provider:    "fs-provider",
			Parameters: map[string]interface{}{
				"type": "object",
			},
			Timestamp: time.Now(),
		},
	}

	for _, tool := range tools {
		if err := registry.RegisterExternalTool(tool); err != nil {
			t.Fatalf("RegisterExternalTool() failed: %v", err)
		}
	}

	// Mark provider unavailable
	registry.MarkProviderUnavailable("fs-provider")

	// All tools from provider should be marked unavailable
	allTools := registry.ListExternalTools()
	for _, tool := range allTools {
		if tool.Provider == "fs-provider" && tool.Available {
			t.Errorf("Tool %q from fs-provider should be unavailable after MarkProviderUnavailable()",
				tool.Name)
		}
	}
}

// TestConsumerNameForTool tests consumer name generation for tools
func TestConsumerNameForTool(t *testing.T) {
	tests := []struct {
		toolName string
		expected string
	}{
		{
			toolName: "file_read",
			expected: "tool-exec-file-read",
		},
		{
			toolName: "graph.query",
			expected: "tool-exec-graph-query",
		},
		{
			toolName: "some_tool.with.dots_and_underscores",
			expected: "tool-exec-some-tool-with-dots-and-underscores",
		},
		{
			toolName: "simple",
			expected: "tool-exec-simple",
		},
	}

	for _, tt := range tests {
		t.Run(tt.toolName, func(t *testing.T) {
			result := agentictools.ConsumerNameForTool(tt.toolName)
			if result != tt.expected {
				t.Errorf("ConsumerNameForTool(%q) = %q, want %q",
					tt.toolName, result, tt.expected)
			}

			// Verify sanitization rules
			if strings.Contains(result, ".") {
				t.Errorf("ConsumerNameForTool() result should not contain '.', got %q", result)
			}
			if strings.Contains(result, "_") {
				t.Errorf("ConsumerNameForTool() result should not contain '_', got %q", result)
			}
			if !strings.HasPrefix(result, "tool-exec-") {
				t.Errorf("ConsumerNameForTool() result should have prefix 'tool-exec-', got %q", result)
			}
		})
	}
}

// TestExternalToolRegistry_ToolCollision tests internal tool precedence
func TestExternalToolRegistry_ToolCollision(t *testing.T) {
	// This test verifies that when an external tool tries to register with the same name
	// as an internal tool, the registration should log a warning but the internal tool
	// should take precedence in execution and listing.

	registry := agentictools.NewExecutorRegistry()

	// Register internal tool
	internalExecutor := &mockToolExecutor{
		name: "graph_query",
		listToolsFunc: func() []agentic.ToolDefinition {
			return []agentic.ToolDefinition{
				{
					Name:        "graph_query",
					Description: "Internal graph query",
					Parameters: map[string]any{
						"type": "object",
					},
				},
			}
		},
	}
	err := registry.RegisterTool("graph_query", internalExecutor)
	if err != nil {
		t.Fatalf("RegisterTool() for internal tool failed: %v", err)
	}

	// Create external registry
	externalRegistry := agentictools.NewExternalToolRegistry()

	// Register external tool with same name
	externalReg := agentictools.ExternalToolRegistration{
		Name:        "graph_query",
		Description: "External graph query",
		Provider:    "external-provider",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}

	// External registration should succeed (it's in separate namespace)
	err = externalRegistry.RegisterExternalTool(externalReg)
	if err != nil {
		t.Fatalf("RegisterExternalTool() should succeed even with name collision, got error: %v", err)
	}

	// When combined, internal tool should take precedence
	// This will be tested in the component integration, but we verify
	// that both registries can coexist with same tool names
	internalTools := registry.ListTools()
	externalTools := externalRegistry.ListExternalTools()

	foundInternal := false
	foundExternal := false

	for _, tool := range internalTools {
		if tool.Name == "graph_query" {
			foundInternal = true
			if tool.Description != "Internal graph query" {
				t.Error("Internal tool should maintain its description")
			}
		}
	}

	for _, tool := range externalTools {
		if tool.Name == "graph_query" {
			foundExternal = true
			if tool.Description != "External graph query" {
				t.Error("External tool should maintain its description")
			}
		}
	}

	if !foundInternal {
		t.Error("Internal tool should be present in internal registry")
	}
	if !foundExternal {
		t.Error("External tool should be present in external registry")
	}
}

// TestExternalToolRegistry_ConcurrentRegistration tests concurrent tool registration
func TestExternalToolRegistry_ConcurrentRegistration(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register tools concurrently
	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func(n int) {
			defer wg.Done()
			reg := agentictools.ExternalToolRegistration{
				Name:        "tool_" + string(rune('0'+n)),
				Description: "Concurrent tool",
				Provider:    "concurrent-provider",
				Parameters: map[string]interface{}{
					"type": "object",
				},
				Timestamp: time.Now(),
			}
			_ = registry.RegisterExternalTool(reg)
		}(i)
	}

	// Wait for all registrations
	wg.Wait()

	// All tools should be registered (race detector will catch issues)
	tools := registry.ListExternalTools()
	if len(tools) == 0 {
		t.Error("ListExternalTools() should return registered tools")
	}
}

// TestExternalToolRegistry_ConcurrentHeartbeats tests concurrent heartbeat recording
func TestExternalToolRegistry_ConcurrentHeartbeats(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register a tool
	reg := agentictools.ExternalToolRegistration{
		Name:        "file_read",
		Description: "Read a file",
		Provider:    "fs-provider",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}
	err := registry.RegisterExternalTool(reg)
	if err != nil {
		t.Fatalf("RegisterExternalTool() failed: %v", err)
	}

	// Record heartbeats concurrently
	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			heartbeat := agentictools.ToolHeartbeat{
				Provider:  "fs-provider",
				Tools:     []string{"file_read"},
				Timestamp: time.Now(),
			}
			registry.RecordHeartbeat(heartbeat)
		}()
	}

	// Wait for all heartbeats
	wg.Wait()

	// Provider should be healthy after concurrent updates
	if !registry.IsProviderHealthy("fs-provider", 30*time.Second) {
		t.Error("IsProviderHealthy() should return true after concurrent heartbeats")
	}

	// Race detector will catch any concurrency issues
}

// TestExternalToolRegistry_ConcurrentHealthChecks tests concurrent health checks
func TestExternalToolRegistry_ConcurrentHealthChecks(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register tool and heartbeat
	reg := agentictools.ExternalToolRegistration{
		Name:        "file_read",
		Description: "Read a file",
		Provider:    "fs-provider",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}
	err := registry.RegisterExternalTool(reg)
	if err != nil {
		t.Fatalf("RegisterExternalTool() failed: %v", err)
	}

	heartbeat := agentictools.ToolHeartbeat{
		Provider:  "fs-provider",
		Tools:     []string{"file_read"},
		Timestamp: time.Now(),
	}
	registry.RecordHeartbeat(heartbeat)

	// Check health concurrently while recording new heartbeats
	var wg sync.WaitGroup
	for i := 0; i < 5; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			registry.IsProviderHealthy("fs-provider", 30*time.Second)
		}()
	}

	for i := 0; i < 5; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			heartbeat := agentictools.ToolHeartbeat{
				Provider:  "fs-provider",
				Tools:     []string{"file_read"},
				Timestamp: time.Now(),
			}
			registry.RecordHeartbeat(heartbeat)
		}()
	}

	// Wait for all operations
	wg.Wait()

	// Race detector will catch any concurrency issues
}

// TestExternalToolRegistry_MultipleProvidersSameTool tests multiple providers registering same tool name
func TestExternalToolRegistry_MultipleProvidersSameTool(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register same tool name from different providers
	providers := []string{"provider-1", "provider-2", "provider-3"}
	for _, provider := range providers {
		reg := agentictools.ExternalToolRegistration{
			Name:        "file_read",
			Description: "Read a file from " + provider,
			Provider:    provider,
			Parameters: map[string]interface{}{
				"type": "object",
			},
			Timestamp: time.Now(),
		}
		err := registry.RegisterExternalTool(reg)
		if err != nil {
			t.Fatalf("RegisterExternalTool() from %s failed: %v", provider, err)
		}
	}

	// All three should be registered
	tools := registry.ListExternalTools()
	count := 0
	for _, tool := range tools {
		if tool.Name == "file_read" {
			count++
		}
	}

	if count != len(providers) {
		t.Errorf("Expected %d tools named 'file_read', got %d", len(providers), count)
	}

	// Unregister from one provider
	unreg := agentictools.ToolUnregister{
		Name:     "file_read",
		Provider: "provider-1",
	}
	err := registry.UnregisterTool(unreg)
	if err != nil {
		t.Fatalf("UnregisterTool() failed: %v", err)
	}

	// Should still have 2 remaining
	tools = registry.ListExternalTools()
	count = 0
	for _, tool := range tools {
		if tool.Name == "file_read" {
			count++
			if tool.Provider == "provider-1" {
				t.Error("Tool from provider-1 should be unregistered")
			}
		}
	}

	if count != 2 {
		t.Errorf("Expected 2 tools named 'file_read' after unregister, got %d", count)
	}
}

// TestExternalToolRegistry_HeartbeatUpdatesTimestamp tests that heartbeats update timestamp
func TestExternalToolRegistry_HeartbeatUpdatesTimestamp(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register tool
	reg := agentictools.ExternalToolRegistration{
		Name:        "file_read",
		Description: "Read a file",
		Provider:    "fs-provider",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}
	err := registry.RegisterExternalTool(reg)
	if err != nil {
		t.Fatalf("RegisterExternalTool() failed: %v", err)
	}

	// Record first heartbeat
	firstTime := time.Now()
	heartbeat1 := agentictools.ToolHeartbeat{
		Provider:  "fs-provider",
		Tools:     []string{"file_read"},
		Timestamp: firstTime,
	}
	registry.RecordHeartbeat(heartbeat1)

	// Small delay
	time.Sleep(10 * time.Millisecond)

	// Record second heartbeat
	secondTime := time.Now()
	heartbeat2 := agentictools.ToolHeartbeat{
		Provider:  "fs-provider",
		Tools:     []string{"file_read"},
		Timestamp: secondTime,
	}
	registry.RecordHeartbeat(heartbeat2)

	// Second timestamp should be more recent
	if !secondTime.After(firstTime) {
		t.Error("Second heartbeat timestamp should be after first")
	}

	// Provider should be healthy with recent heartbeat
	if !registry.IsProviderHealthy("fs-provider", 30*time.Second) {
		t.Error("IsProviderHealthy() should return true with recent heartbeat")
	}
}

// TestExternalToolRegistry_AvailabilityStateTransitions tests tool availability state changes
func TestExternalToolRegistry_AvailabilityStateTransitions(t *testing.T) {
	registry := agentictools.NewExternalToolRegistry()

	// Register tool
	reg := agentictools.ExternalToolRegistration{
		Name:        "file_read",
		Description: "Read a file",
		Provider:    "fs-provider",
		Parameters: map[string]interface{}{
			"type": "object",
		},
		Timestamp: time.Now(),
	}
	err := registry.RegisterExternalTool(reg)
	if err != nil {
		t.Fatalf("RegisterExternalTool() failed: %v", err)
	}

	// Record heartbeat - should make available
	heartbeat := agentictools.ToolHeartbeat{
		Provider:  "fs-provider",
		Tools:     []string{"file_read"},
		Timestamp: time.Now(),
	}
	registry.RecordHeartbeat(heartbeat)

	// Tool should be available
	tools := registry.ListExternalTools()
	available := false
	for _, tool := range tools {
		if tool.Name == "file_read" && tool.Provider == "fs-provider" {
			available = tool.Available
			break
		}
	}
	if !available {
		t.Error("Tool should be available after heartbeat")
	}

	// Mark provider unavailable
	registry.MarkProviderUnavailable("fs-provider")

	// Tool should now be unavailable
	tools = registry.ListExternalTools()
	for _, tool := range tools {
		if tool.Name == "file_read" && tool.Provider == "fs-provider" {
			if tool.Available {
				t.Error("Tool should be unavailable after MarkProviderUnavailable()")
			}
			break
		}
	}

	// Record new heartbeat - should restore availability
	heartbeat2 := agentictools.ToolHeartbeat{
		Provider:  "fs-provider",
		Tools:     []string{"file_read"},
		Timestamp: time.Now(),
	}
	registry.RecordHeartbeat(heartbeat2)

	// Tool should be available again
	tools = registry.ListExternalTools()
	available = false
	for _, tool := range tools {
		if tool.Name == "file_read" && tool.Provider == "fs-provider" {
			available = tool.Available
			break
		}
	}
	if !available {
		t.Error("Tool should be available again after new heartbeat")
	}
}
