// Code generated by Tester Agent. DO NOT EDIT.
// Task: velvety-jingling-tulip Step 6 - CLI input metrics tests
// Builder must make these tests pass without modification.

package cli

import (
	"testing"
	"time"

	"github.com/c360studio/semstreams/metric"
	"github.com/prometheus/client_golang/prometheus"
	dto "github.com/prometheus/client_model/go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ====================================================================================
// Metrics Creation Tests
// ====================================================================================

func TestCLIMetrics_Creation(t *testing.T) {
	// Create metrics registry
	registry := metric.NewMetricsRegistry()

	// Create CLI input metrics
	metrics := getMetrics(registry)

	// Verify all metrics were created
	require.NotNil(t, metrics, "Expected metrics to be created")
	assert.NotNil(t, metrics.messagesPublished, "Expected messagesPublished metric to be created")
	assert.NotNil(t, metrics.signalsSent, "Expected signalsSent metric to be created")
	assert.NotNil(t, metrics.responsesReceived, "Expected responsesReceived metric to be created")

	t.Log("All CLI input metrics successfully created")
}

func TestCLIMetrics_NilRegistry(t *testing.T) {
	// Test "nil input = nil feature" pattern
	// The metrics should still be created but use default Prometheus registry
	metrics := getMetrics(nil)

	require.NotNil(t, metrics, "Expected metrics to be created even with nil registry")
	assert.NotNil(t, metrics.messagesPublished, "Expected messagesPublished to be created")
}

// ====================================================================================
// Counter Tests - Messages Published
// ====================================================================================

func TestCLIMetrics_RecordMessagePublished(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	initial := getSimpleCounterValue(t, metrics.messagesPublished)

	// Record messages published
	metrics.recordMessagePublished()
	metrics.recordMessagePublished()
	metrics.recordMessagePublished()

	after := getSimpleCounterValue(t, metrics.messagesPublished)
	assert.Equal(t, initial+3, after, "Counter should increment by 3")
}

func TestCLIMetrics_RecordMessagePublished_SingleIncrement(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	initial := getSimpleCounterValue(t, metrics.messagesPublished)

	metrics.recordMessagePublished()

	after := getSimpleCounterValue(t, metrics.messagesPublished)
	assert.Equal(t, initial+1, after, "Counter should increment by 1")
}

// ====================================================================================
// Counter Tests - Signals Sent by Type
// ====================================================================================

func TestCLIMetrics_RecordSignalSent(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	tests := []struct {
		name       string
		signalType string
	}{
		{name: "cancel signal", signalType: "cancel"},
		{name: "pause signal", signalType: "pause"},
		{name: "resume signal", signalType: "resume"},
		{name: "approve signal", signalType: "approve"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			initial := getCounterValue(t, metrics.signalsSent, tt.signalType)

			metrics.recordSignalSent(tt.signalType)

			after := getCounterValue(t, metrics.signalsSent, tt.signalType)
			assert.Equal(t, initial+1, after, "Counter should increment by 1")
		})
	}
}

func TestCLIMetrics_RecordSignalSent_MultipleTypes(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	// Send different signal types
	metrics.recordSignalSent("cancel")
	metrics.recordSignalSent("cancel")
	metrics.recordSignalSent("cancel")
	metrics.recordSignalSent("pause")
	metrics.recordSignalSent("resume")

	// Verify correct counts per signal type
	cancelCount := getCounterValue(t, metrics.signalsSent, "cancel")
	pauseCount := getCounterValue(t, metrics.signalsSent, "pause")
	resumeCount := getCounterValue(t, metrics.signalsSent, "resume")

	assert.Equal(t, float64(3), cancelCount, "Cancel should be sent 3 times")
	assert.Equal(t, float64(1), pauseCount, "Pause should be sent 1 time")
	assert.Equal(t, float64(1), resumeCount, "Resume should be sent 1 time")
}

func TestCLIMetrics_RecordSignalSent_CtrlCScenario(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	initial := getCounterValue(t, metrics.signalsSent, "cancel")

	// Simulate Ctrl+C being pressed (sends cancel signal)
	metrics.recordSignalSent("cancel")

	after := getCounterValue(t, metrics.signalsSent, "cancel")
	assert.Equal(t, initial+1, after, "Cancel signal should be recorded when Ctrl+C is pressed")
}

// ====================================================================================
// Counter Tests - Responses Received by Type
// ====================================================================================

func TestCLIMetrics_RecordResponseReceived(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	tests := []struct {
		name         string
		responseType string
	}{
		{name: "ack response", responseType: "ack"},
		{name: "result response", responseType: "result"},
		{name: "error response", responseType: "error"},
		{name: "progress response", responseType: "progress"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			initial := getCounterValue(t, metrics.responsesReceived, tt.responseType)

			metrics.recordResponseReceived(tt.responseType)

			after := getCounterValue(t, metrics.responsesReceived, tt.responseType)
			assert.Equal(t, initial+1, after, "Counter should increment by 1")
		})
	}
}

func TestCLIMetrics_RecordResponseReceived_MultipleTypes(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	// Simulate typical response flow
	metrics.recordResponseReceived("ack")      // Initial acknowledgment
	metrics.recordResponseReceived("progress") // Progress update
	metrics.recordResponseReceived("progress") // Another progress update
	metrics.recordResponseReceived("progress") // Another progress update
	metrics.recordResponseReceived("result")   // Final result

	// Verify counts
	ackCount := getCounterValue(t, metrics.responsesReceived, "ack")
	progressCount := getCounterValue(t, metrics.responsesReceived, "progress")
	resultCount := getCounterValue(t, metrics.responsesReceived, "result")

	assert.Equal(t, float64(1), ackCount, "Should have 1 ack")
	assert.Equal(t, float64(3), progressCount, "Should have 3 progress updates")
	assert.Equal(t, float64(1), resultCount, "Should have 1 result")
}

func TestCLIMetrics_RecordResponseReceived_ErrorScenario(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	// Simulate error response flow
	metrics.recordResponseReceived("ack")
	metrics.recordResponseReceived("error")

	errorCount := getCounterValue(t, metrics.responsesReceived, "error")
	assert.GreaterOrEqual(t, errorCount, float64(1), "Should have at least 1 error response")
}

// ====================================================================================
// Integration Tests - Typical CLI Interaction Flow
// ====================================================================================

func TestCLIMetrics_TypicalInteractionFlow(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	// User types a message
	metrics.recordMessagePublished()

	// Router responds with acknowledgment
	metrics.recordResponseReceived("ack")

	// Loop sends progress updates
	metrics.recordResponseReceived("progress")
	metrics.recordResponseReceived("progress")

	// Final result
	metrics.recordResponseReceived("result")

	// Verify the flow
	messages := getSimpleCounterValue(t, metrics.messagesPublished)
	acks := getCounterValue(t, metrics.responsesReceived, "ack")
	progress := getCounterValue(t, metrics.responsesReceived, "progress")
	results := getCounterValue(t, metrics.responsesReceived, "result")

	assert.GreaterOrEqual(t, messages, float64(1), "Should have at least 1 message published")
	assert.GreaterOrEqual(t, acks, float64(1), "Should have at least 1 ack")
	assert.GreaterOrEqual(t, progress, float64(2), "Should have at least 2 progress updates")
	assert.GreaterOrEqual(t, results, float64(1), "Should have at least 1 result")
}

func TestCLIMetrics_CancelInteractionFlow(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	// User types a message
	metrics.recordMessagePublished()

	// Ack received
	metrics.recordResponseReceived("ack")

	// User presses Ctrl+C
	metrics.recordSignalSent("cancel")

	// Router acknowledges cancellation
	metrics.recordResponseReceived("ack")

	// Verify the flow
	messages := getSimpleCounterValue(t, metrics.messagesPublished)
	cancels := getCounterValue(t, metrics.signalsSent, "cancel")

	assert.GreaterOrEqual(t, messages, float64(1), "Should have message published")
	assert.GreaterOrEqual(t, cancels, float64(1), "Should have cancel signal")
}

// ====================================================================================
// Concurrent Access Tests
// ====================================================================================

func TestCLIMetrics_ConcurrentUpdates(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	// Simulate concurrent CLI operations
	done := make(chan struct{})

	// Messages published
	go func() {
		for i := 0; i < 100; i++ {
			metrics.recordMessagePublished()
			time.Sleep(time.Microsecond)
		}
		done <- struct{}{}
	}()

	// Signals sent
	go func() {
		for i := 0; i < 50; i++ {
			metrics.recordSignalSent("cancel")
			time.Sleep(time.Microsecond)
		}
		done <- struct{}{}
	}()

	// Responses received
	go func() {
		for i := 0; i < 75; i++ {
			metrics.recordResponseReceived("progress")
			time.Sleep(time.Microsecond)
		}
		done <- struct{}{}
	}()

	// Wait for all goroutines
	<-done
	<-done
	<-done

	// Verify all updates were recorded (no race conditions)
	messages := getSimpleCounterValue(t, metrics.messagesPublished)
	signals := getCounterValue(t, metrics.signalsSent, "cancel")
	responses := getCounterValue(t, metrics.responsesReceived, "progress")

	assert.GreaterOrEqual(t, messages, float64(100), "Should have at least 100 messages")
	assert.GreaterOrEqual(t, signals, float64(50), "Should have at least 50 signals")
	assert.GreaterOrEqual(t, responses, float64(75), "Should have at least 75 responses")
}

// ====================================================================================
// Edge Cases
// ====================================================================================

func TestCLIMetrics_ZeroState(t *testing.T) {
	registry := metric.NewMetricsRegistry()
	metrics := getMetrics(registry)

	// Verify initial state (should be zero or greater due to other tests)
	messages := getSimpleCounterValue(t, metrics.messagesPublished)
	assert.GreaterOrEqual(t, messages, float64(0), "Initial state should be non-negative")
}

func TestCLIMetrics_SingletonPattern(t *testing.T) {
	registry := metric.NewMetricsRegistry()

	// Get metrics multiple times
	metrics1 := getMetrics(registry)
	metrics2 := getMetrics(registry)

	// Should return the same instance due to sync.Once
	require.NotNil(t, metrics1)
	require.NotNil(t, metrics2)

	// Record on first instance
	metrics1.recordMessagePublished()

	// Verify both see the same value (same instance)
	val1 := getSimpleCounterValue(t, metrics1.messagesPublished)
	val2 := getSimpleCounterValue(t, metrics2.messagesPublished)
	assert.Equal(t, val1, val2, "Singleton pattern should return same instance")
}

// ====================================================================================
// Test Helpers
// ====================================================================================

// getCounterValue extracts the current value from a CounterVec with a label
func getCounterValue(t *testing.T, vec *prometheus.CounterVec, label string) float64 {
	t.Helper()

	counter, err := vec.GetMetricWithLabelValues(label)
	require.NoError(t, err, "Failed to get counter with label %s", label)

	var metric dto.Metric
	err = counter.Write(&metric)
	require.NoError(t, err, "Failed to write metric")

	return metric.Counter.GetValue()
}

// getSimpleCounterValue extracts the current value from a simple Counter
func getSimpleCounterValue(t *testing.T, counter prometheus.Counter) float64 {
	t.Helper()

	var metric dto.Metric
	err := counter.Write(&metric)
	require.NoError(t, err, "Failed to write metric")

	return metric.Counter.GetValue()
}
