// Code generated by Tester Agent. DO NOT EDIT.
// Task: Model Alias System unit tests (greenfield)
// Builder must make these tests pass without modification.

package agenticmodel_test

import (
	"encoding/json"
	"testing"

	agenticmodel "github.com/c360/semstreams/processor/agentic-model"
)

// TestConfig_ModelAliases_JSONSerialization verifies ModelAliases field
// serializes and deserializes correctly in JSON
func TestConfig_ModelAliases_JSONSerialization(t *testing.T) {
	tests := []struct {
		name        string
		config      agenticmodel.Config
		expectEmpty bool // true if aliases should be nil/omitted in JSON
	}{
		{
			name: "empty aliases map",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{},
				Endpoints: map[string]agenticmodel.Endpoint{
					"default": {
						URL:   "http://localhost:8080/v1",
						Model: "gpt-4",
					},
				},
			},
			expectEmpty: false,
		},
		{
			name: "nil aliases map",
			config: agenticmodel.Config{
				ModelAliases: nil,
				Endpoints: map[string]agenticmodel.Endpoint{
					"default": {
						URL:   "http://localhost:8080/v1",
						Model: "gpt-4",
					},
				},
			},
			expectEmpty: true,
		},
		{
			name: "single alias",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast": "gpt-4o-mini",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o-mini": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o-mini",
					},
				},
			},
			expectEmpty: false,
		},
		{
			name: "multiple semantic aliases",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast":  "gpt-4o-mini",
					"smart": "gpt-4o",
					"cheap": "gpt-3.5-turbo",
					"local": "ollama-llama",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o-mini": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o-mini",
					},
					"gpt-4o": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o",
					},
					"gpt-3.5-turbo": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-3.5-turbo",
					},
					"ollama-llama": {
						URL:   "http://ollama:11434/v1",
						Model: "llama3.2",
					},
				},
			},
			expectEmpty: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Marshal
			gotJSON, err := json.Marshal(tt.config)
			if err != nil {
				t.Fatalf("Marshal() error = %v", err)
			}

			// Unmarshal back
			var gotConfig agenticmodel.Config
			if err := json.Unmarshal(gotJSON, &gotConfig); err != nil {
				t.Fatalf("Unmarshal() error = %v", err)
			}

			// Verify round-trip preserves ModelAliases
			if tt.expectEmpty {
				if gotConfig.ModelAliases != nil && len(gotConfig.ModelAliases) > 0 {
					t.Errorf("Expected nil or empty ModelAliases after round-trip, got %d entries", len(gotConfig.ModelAliases))
				}
			} else {
				if len(gotConfig.ModelAliases) != len(tt.config.ModelAliases) {
					t.Errorf("ModelAliases count mismatch after round-trip: got %d, want %d",
						len(gotConfig.ModelAliases), len(tt.config.ModelAliases))
				}

				// Verify each alias preserved
				for alias, target := range tt.config.ModelAliases {
					gotTarget, exists := gotConfig.ModelAliases[alias]
					if !exists {
						t.Errorf("Alias %q missing after round-trip", alias)
						continue
					}
					if gotTarget != target {
						t.Errorf("Alias %q target = %q, want %q", alias, gotTarget, target)
					}
				}
			}
		})
	}
}

// TestConfig_Validate_AliasTargetsMustExist verifies that validation fails
// when an alias points to a non-existent endpoint
func TestConfig_Validate_AliasTargetsMustExist(t *testing.T) {
	tests := []struct {
		name    string
		config  agenticmodel.Config
		wantErr bool
		errMsg  string
	}{
		{
			name: "valid alias pointing to existing endpoint",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast": "gpt-4o-mini",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o-mini": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o-mini",
					},
				},
			},
			wantErr: false,
		},
		{
			name: "multiple valid aliases",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast":  "gpt-4o-mini",
					"smart": "gpt-4o",
					"cheap": "gpt-3.5-turbo",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o-mini": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o-mini",
					},
					"gpt-4o": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o",
					},
					"gpt-3.5-turbo": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-3.5-turbo",
					},
				},
			},
			wantErr: false,
		},
		{
			name: "alias points to non-existent endpoint",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast": "gpt-4o-mini",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o",
					},
				},
			},
			wantErr: true,
			errMsg:  "gpt-4o-mini",
		},
		{
			name: "one valid alias, one invalid",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast":  "gpt-4o-mini",
					"smart": "gpt-4o",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o-mini": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o-mini",
					},
					// Missing gpt-4o endpoint
				},
			},
			wantErr: true,
			errMsg:  "gpt-4o",
		},
		{
			name: "empty alias target",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast": "",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o-mini": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o-mini",
					},
				},
			},
			wantErr: true,
			errMsg:  "alias",
		},
		{
			name: "no aliases is valid",
			config: agenticmodel.Config{
				ModelAliases: nil,
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o",
					},
				},
			},
			wantErr: false,
		},
		{
			name: "empty aliases map is valid",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o",
					},
				},
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if (err != nil) != tt.wantErr {
				t.Errorf("Validate() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if tt.wantErr && err != nil && tt.errMsg != "" {
				if !containsIgnoreCase(err.Error(), tt.errMsg) {
					t.Errorf("Validate() error = %v, expected error message to contain %q", err, tt.errMsg)
				}
			}
		})
	}
}

// TestConfig_Validate_AliasChainNotSupported verifies that aliases cannot
// chain to other aliases (alias -> alias -> endpoint is forbidden)
func TestConfig_Validate_AliasChainNotSupported(t *testing.T) {
	tests := []struct {
		name    string
		config  agenticmodel.Config
		wantErr bool
		errMsg  string
	}{
		{
			name: "direct alias to endpoint (valid)",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast": "gpt-4o-mini",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o-mini": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o-mini",
					},
				},
			},
			wantErr: false,
		},
		{
			name: "alias points to another alias (invalid)",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast":    "cheap",
					"cheap":   "gpt-3.5-turbo",
					"fastest": "fast",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-3.5-turbo": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-3.5-turbo",
					},
				},
			},
			wantErr: true,
			errMsg:  "alias", // Error should mention alias chaining or that target is an alias
		},
		{
			name: "alias points to alias that doesn't exist as endpoint (invalid)",
			config: agenticmodel.Config{
				ModelAliases: map[string]string{
					"fast": "smart",
				},
				Endpoints: map[string]agenticmodel.Endpoint{
					"gpt-4o": {
						URL:   "https://api.openai.com/v1",
						Model: "gpt-4o",
					},
				},
			},
			wantErr: true,
			errMsg:  "smart",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if (err != nil) != tt.wantErr {
				t.Errorf("Validate() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if tt.wantErr && err != nil && tt.errMsg != "" {
				if !containsIgnoreCase(err.Error(), tt.errMsg) {
					t.Errorf("Validate() error = %v, expected error message to contain %q", err, tt.errMsg)
				}
			}
		})
	}
}
