// Code generated by Tester Agent. DO NOT EDIT.
// Task: Agentic Components Integration Tests
// Builder must make these tests pass without modification.

//go:build integration

package agenticmodel_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"
	"time"

	"github.com/nats-io/nats.go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/c360studio/semstreams/agentic"
	"github.com/c360studio/semstreams/component"
	"github.com/c360studio/semstreams/message"
	"github.com/c360studio/semstreams/natsclient"
	agenticmodel "github.com/c360studio/semstreams/processor/agentic-model"
)

var (
	sharedTestClient *natsclient.TestClient
	sharedNATSClient *natsclient.Client
)

// TestMain sets up shared NATS container for all model integration tests
func TestMain(m *testing.M) {
	streams := []natsclient.TestStreamConfig{
		{Name: "AGENT", Subjects: []string{"agent.>", "tool.>"}},
	}

	testClient, err := natsclient.NewSharedTestClient(
		natsclient.WithJetStream(),
		natsclient.WithStreams(streams...),
		natsclient.WithTestTimeout(5*time.Second),
		natsclient.WithStartTimeout(30*time.Second),
	)
	if err != nil {
		panic("Failed to create shared test client: " + err.Error())
	}

	sharedTestClient = testClient
	sharedNATSClient = testClient.Client

	exitCode := m.Run()

	sharedTestClient.Terminate()

	if exitCode != 0 {
		panic("tests failed")
	}
}

func getSharedNATSClient(t *testing.T) *natsclient.Client {
	if sharedNATSClient == nil {
		t.Fatal("Shared NATS client not initialized")
	}
	return sharedNATSClient
}

// publishAgentRequestMessage publishes an AgentRequest wrapped in a BaseMessage envelope
func publishAgentRequestMessage(t *testing.T, natsClient *natsclient.Client, subject string, req *agentic.AgentRequest) {
	t.Helper()
	baseMsg := message.NewBaseMessage(req.Schema(), req, "integration-test")
	msgData, err := json.Marshal(baseMsg)
	require.NoError(t, err, "Failed to marshal BaseMessage")
	err = natsClient.PublishToStream(context.Background(), subject, msgData)
	require.NoError(t, err, "Failed to publish agent request message")
}

// TestIntegration_ModelCompleteResponse tests that a complete response is published correctly
func TestIntegration_ModelCompleteResponse(t *testing.T) {
	natsClient := getSharedNATSClient(t)

	// Create mock LLM server that returns a complete response
	mockServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		response := map[string]any{
			"choices": []map[string]any{
				{
					"message": map[string]any{
						"role":    "assistant",
						"content": "Task completed successfully",
					},
					"finish_reason": "stop",
				},
			},
			"usage": map[string]any{
				"prompt_tokens":     100,
				"completion_tokens": 50,
			},
		}
		json.NewEncoder(w).Encode(response)
	}))
	defer mockServer.Close()

	// Create component config with mock endpoint
	config := agenticmodel.Config{
		Ports: &component.PortConfig{
			Inputs: []component.PortDefinition{
				{
					Name:       "requests",
					Type:       "jetstream",
					Subject:    "agent.request.>",
					StreamName: "AGENT",
					Required:   true,
				},
			},
			Outputs: []component.PortDefinition{
				{
					Name:       "responses",
					Type:       "jetstream",
					Subject:    "agent.response.*",
					StreamName: "AGENT",
				},
			},
		},
		StreamName:         "AGENT",
		ConsumerNameSuffix: "complete-test",
		Endpoints: map[string]agenticmodel.Endpoint{
			"test-model": {
				URL:   mockServer.URL + "/v1/chat/completions",
				Model: "test-model",
			},
		},
		Timeout: "5s",
	}

	rawConfig, err := json.Marshal(config)
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := agenticmodel.NewComponent(rawConfig, deps)
	require.NoError(t, err)

	lc, ok := comp.(component.LifecycleComponent)
	require.True(t, ok)

	err = lc.Initialize()
	require.NoError(t, err)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	err = lc.Start(ctx)
	require.NoError(t, err)
	defer lc.Stop(5 * time.Second)

	time.Sleep(200 * time.Millisecond)

	// Subscribe to responses
	receivedResponses := make([]agentic.AgentResponse, 0)
	var receiveMu sync.Mutex

	_, err = natsClient.Subscribe(ctx, "agent.response.>", func(_ context.Context, msg *nats.Msg) {
		var baseMsg message.BaseMessage
		if err := json.Unmarshal(msg.Data, &baseMsg); err == nil {
			if resp, ok := baseMsg.Payload().(*agentic.AgentResponse); ok {
				receiveMu.Lock()
				receivedResponses = append(receivedResponses, *resp)
				receiveMu.Unlock()
			}
		}
	})
	require.NoError(t, err)

	time.Sleep(100 * time.Millisecond)

	// Publish agent request (wrapped in BaseMessage)
	request := &agentic.AgentRequest{
		RequestID: "req_123",
		LoopID:    "loop_456",
		Role:      "general",
		Model:     "test-model",
		Messages: []agentic.ChatMessage{
			{
				Role:    "user",
				Content: "Test message",
			},
		},
	}
	publishAgentRequestMessage(t, natsClient, "agent.request.test", request)
	require.NoError(t, err)

	// Wait for response
	time.Sleep(1 * time.Second)

	// Verify response was received
	receiveMu.Lock()
	defer receiveMu.Unlock()

	require.Equal(t, 1, len(receivedResponses), "Should receive one response")
	resp := receivedResponses[0]
	assert.Equal(t, "req_123", resp.RequestID)
	assert.Equal(t, "complete", resp.Status)
	assert.Equal(t, "assistant", resp.Message.Role)
	assert.Equal(t, "Task completed successfully", resp.Message.Content)
	assert.Equal(t, 100, resp.TokenUsage.PromptTokens)
	assert.Equal(t, 50, resp.TokenUsage.CompletionTokens)
}

// TestIntegration_ModelToolCallResponse tests that tool calls are extracted correctly
func TestIntegration_ModelToolCallResponse(t *testing.T) {
	natsClient := getSharedNATSClient(t)

	// Create mock LLM server that returns tool calls
	mockServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		response := map[string]any{
			"choices": []map[string]any{
				{
					"message": map[string]any{
						"role":    "assistant",
						"content": "",
						"tool_calls": []map[string]any{
							{
								"id":   "call_001",
								"type": "function",
								"function": map[string]any{
									"name":      "read_file",
									"arguments": `{"path": "test.go"}`,
								},
							},
						},
					},
					"finish_reason": "tool_calls",
				},
			},
			"usage": map[string]any{
				"prompt_tokens":     150,
				"completion_tokens": 75,
			},
		}
		json.NewEncoder(w).Encode(response)
	}))
	defer mockServer.Close()

	config := agenticmodel.Config{
		Ports: &component.PortConfig{
			Inputs: []component.PortDefinition{
				{
					Name:       "requests",
					Type:       "jetstream",
					Subject:    "agent.request.>",
					StreamName: "AGENT",
					Required:   true,
				},
			},
			Outputs: []component.PortDefinition{
				{
					Name:       "responses",
					Type:       "jetstream",
					Subject:    "agent.response.*",
					StreamName: "AGENT",
				},
			},
		},
		StreamName:         "AGENT",
		ConsumerNameSuffix: "toolcall-test",
		Endpoints: map[string]agenticmodel.Endpoint{
			"tool-model": {
				URL:   mockServer.URL + "/v1/chat/completions",
				Model: "tool-model",
			},
		},
		Timeout: "5s",
	}

	rawConfig, err := json.Marshal(config)
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := agenticmodel.NewComponent(rawConfig, deps)
	require.NoError(t, err)

	lc, ok := comp.(component.LifecycleComponent)
	require.True(t, ok)

	err = lc.Initialize()
	require.NoError(t, err)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	err = lc.Start(ctx)
	require.NoError(t, err)
	defer lc.Stop(5 * time.Second)

	time.Sleep(200 * time.Millisecond)

	// Subscribe to responses
	receivedResponses := make([]agentic.AgentResponse, 0)
	var receiveMu sync.Mutex

	_, err = natsClient.Subscribe(ctx, "agent.response.>", func(_ context.Context, msg *nats.Msg) {
		var baseMsg message.BaseMessage
		if err := json.Unmarshal(msg.Data, &baseMsg); err == nil {
			if resp, ok := baseMsg.Payload().(*agentic.AgentResponse); ok {
				receiveMu.Lock()
				receivedResponses = append(receivedResponses, *resp)
				receiveMu.Unlock()
			}
		}
	})
	require.NoError(t, err)

	time.Sleep(100 * time.Millisecond)

	// Publish agent request with tools (wrapped in BaseMessage)
	request := &agentic.AgentRequest{
		RequestID: "req_tool_001",
		LoopID:    "loop_tool",
		Role:      "general",
		Model:     "tool-model",
		Messages: []agentic.ChatMessage{
			{
				Role:    "user",
				Content: "Read the test file",
			},
		},
		Tools: []agentic.ToolDefinition{
			{
				Name:        "read_file",
				Description: "Read file contents",
				Parameters: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"path": map[string]any{"type": "string"},
					},
				},
			},
		},
	}
	publishAgentRequestMessage(t, natsClient, "agent.request.tool", request)

	// Wait for response
	time.Sleep(1 * time.Second)

	// Verify response contains tool calls
	receiveMu.Lock()
	defer receiveMu.Unlock()

	require.Equal(t, 1, len(receivedResponses), "Should receive one response")
	resp := receivedResponses[0]
	assert.Equal(t, "req_tool_001", resp.RequestID)
	assert.Equal(t, "tool_call", resp.Status)
	assert.Equal(t, 1, len(resp.Message.ToolCalls))
	assert.Equal(t, "call_001", resp.Message.ToolCalls[0].ID)
	assert.Equal(t, "read_file", resp.Message.ToolCalls[0].Name)
}

// TestIntegration_ModelEndpointResolution tests that requests route to correct endpoints
func TestIntegration_ModelEndpointResolution(t *testing.T) {
	natsClient := getSharedNATSClient(t)

	// Create two mock servers to verify routing
	var endpoint1Called, endpoint2Called bool
	var mu sync.Mutex

	mockServer1 := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		endpoint1Called = true
		mu.Unlock()
		w.Header().Set("Content-Type", "application/json")
		response := map[string]any{
			"choices": []map[string]any{
				{
					"message": map[string]any{
						"role":    "assistant",
						"content": "Response from endpoint 1",
					},
					"finish_reason": "stop",
				},
			},
			"usage": map[string]any{
				"prompt_tokens":     10,
				"completion_tokens": 5,
			},
		}
		json.NewEncoder(w).Encode(response)
	}))
	defer mockServer1.Close()

	mockServer2 := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		endpoint2Called = true
		mu.Unlock()
		w.Header().Set("Content-Type", "application/json")
		response := map[string]any{
			"choices": []map[string]any{
				{
					"message": map[string]any{
						"role":    "assistant",
						"content": "Response from endpoint 2",
					},
					"finish_reason": "stop",
				},
			},
			"usage": map[string]any{
				"prompt_tokens":     15,
				"completion_tokens": 8,
			},
		}
		json.NewEncoder(w).Encode(response)
	}))
	defer mockServer2.Close()

	config := agenticmodel.Config{
		Ports: &component.PortConfig{
			Inputs: []component.PortDefinition{
				{
					Name:       "requests",
					Type:       "jetstream",
					Subject:    "agent.request.>",
					StreamName: "AGENT",
					Required:   true,
				},
			},
			Outputs: []component.PortDefinition{
				{
					Name:       "responses",
					Type:       "jetstream",
					Subject:    "agent.response.*",
					StreamName: "AGENT",
				},
			},
		},
		StreamName:         "AGENT",
		ConsumerNameSuffix: "endpoint-test",
		Endpoints: map[string]agenticmodel.Endpoint{
			"model-a": {
				URL:   mockServer1.URL + "/v1/chat/completions",
				Model: "model-a",
			},
			"model-b": {
				URL:   mockServer2.URL + "/v1/chat/completions",
				Model: "model-b",
			},
		},
		Timeout: "5s",
	}

	rawConfig, err := json.Marshal(config)
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := agenticmodel.NewComponent(rawConfig, deps)
	require.NoError(t, err)

	lc, ok := comp.(component.LifecycleComponent)
	require.True(t, ok)

	err = lc.Initialize()
	require.NoError(t, err)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	err = lc.Start(ctx)
	require.NoError(t, err)
	defer lc.Stop(5 * time.Second)

	time.Sleep(200 * time.Millisecond)

	// Subscribe to responses
	receivedResponses := make([]agentic.AgentResponse, 0)
	var receiveMu sync.Mutex

	_, err = natsClient.Subscribe(ctx, "agent.response.>", func(_ context.Context, msg *nats.Msg) {
		var baseMsg message.BaseMessage
		if err := json.Unmarshal(msg.Data, &baseMsg); err == nil {
			if resp, ok := baseMsg.Payload().(*agentic.AgentResponse); ok {
				receiveMu.Lock()
				receivedResponses = append(receivedResponses, *resp)
				receiveMu.Unlock()
			}
		}
	})
	require.NoError(t, err)

	time.Sleep(100 * time.Millisecond)

	// Send request to model-a (wrapped in BaseMessage)
	request1 := &agentic.AgentRequest{
		RequestID: "req_a",
		LoopID:    "loop_a",
		Role:      "general",
		Model:     "model-a",
		Messages: []agentic.ChatMessage{
			{Role: "user", Content: "Test A"},
		},
	}
	publishAgentRequestMessage(t, natsClient, "agent.request.a", request1)

	time.Sleep(500 * time.Millisecond)

	// Send request to model-b (wrapped in BaseMessage)
	request2 := &agentic.AgentRequest{
		RequestID: "req_b",
		LoopID:    "loop_b",
		Role:      "general",
		Model:     "model-b",
		Messages: []agentic.ChatMessage{
			{Role: "user", Content: "Test B"},
		},
	}
	publishAgentRequestMessage(t, natsClient, "agent.request.b", request2)

	time.Sleep(500 * time.Millisecond)

	// Verify both endpoints were called
	mu.Lock()
	assert.True(t, endpoint1Called, "Endpoint 1 should have been called")
	assert.True(t, endpoint2Called, "Endpoint 2 should have been called")
	mu.Unlock()

	// Verify responses
	receiveMu.Lock()
	defer receiveMu.Unlock()

	assert.Equal(t, 2, len(receivedResponses), "Should receive two responses")
}
