// Code generated by Tester Agent. DO NOT EDIT.
// Task: Simplify graph-query Routing - Replace IntentRouter with StaticRouter
// Builder must make these tests pass without modification.

package graphquery

import (
	"bytes"
	"log/slog"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewStaticRouter(t *testing.T) {
	t.Parallel()

	t.Run("creates router with all routes", func(t *testing.T) {
		logger := slog.New(slog.NewTextHandler(bytes.NewBuffer(nil), nil))
		router := NewStaticRouter(logger)

		require.NotNil(t, router)
		require.NotNil(t, router.routes)
		require.NotNil(t, router.logger)

		// Verify all expected routes are present
		expectedRoutes := map[string]string{
			// Entity queries
			"entity":       "graph.ingest.query.entity",
			"entityBatch":  "graph.ingest.query.batch",
			"entityPrefix": "graph.ingest.query.prefix",

			// Relationship queries
			"outgoing":          "graph.index.query.outgoing",
			"incoming":          "graph.index.query.incoming",
			"alias":             "graph.index.query.alias",
			"predicate":         "graph.index.query.predicate",
			"predicateList":     "graph.index.query.predicateList",
			"predicateStats":    "graph.index.query.predicateStats",
			"predicateCompound": "graph.index.query.predicateCompound",

			// Spatial/Temporal
			"spatial":  "graph.spatial.query.bounds",
			"temporal": "graph.temporal.query.range",

			// ML-based queries
			"semantic":  "graph.embedding.query.search",
			"similar":   "graph.embedding.query.similar",
			"community": "graph.clustering.query.community",
			"anomaly":   "graph.anomalies.query.detect",
		}

		assert.Len(t, router.routes, len(expectedRoutes))
		for queryType, expectedSubject := range expectedRoutes {
			assert.Equal(t, expectedSubject, router.routes[queryType],
				"route mismatch for query type %q", queryType)
		}
	})

	t.Run("does not panic with nil logger", func(t *testing.T) {
		require.NotPanics(t, func() {
			router := NewStaticRouter(nil)
			assert.NotNil(t, router)
		})
	})
}

func TestStaticRouter_Route(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name            string
		queryType       string
		expectedSubject string
	}{
		// Entity queries
		{
			name:            "entity query",
			queryType:       "entity",
			expectedSubject: "graph.ingest.query.entity",
		},
		{
			name:            "entity batch query",
			queryType:       "entityBatch",
			expectedSubject: "graph.ingest.query.batch",
		},
		{
			name:            "entity prefix query",
			queryType:       "entityPrefix",
			expectedSubject: "graph.ingest.query.prefix",
		},

		// Relationship queries
		{
			name:            "outgoing relationships",
			queryType:       "outgoing",
			expectedSubject: "graph.index.query.outgoing",
		},
		{
			name:            "incoming relationships",
			queryType:       "incoming",
			expectedSubject: "graph.index.query.incoming",
		},
		{
			name:            "alias resolution",
			queryType:       "alias",
			expectedSubject: "graph.index.query.alias",
		},
		{
			name:            "predicate query",
			queryType:       "predicate",
			expectedSubject: "graph.index.query.predicate",
		},

		// Spatial/Temporal
		{
			name:            "spatial bounds query",
			queryType:       "spatial",
			expectedSubject: "graph.spatial.query.bounds",
		},
		{
			name:            "temporal range query",
			queryType:       "temporal",
			expectedSubject: "graph.temporal.query.range",
		},

		// ML-based queries
		{
			name:            "semantic search",
			queryType:       "semantic",
			expectedSubject: "graph.embedding.query.search",
		},
		{
			name:            "similar entities",
			queryType:       "similar",
			expectedSubject: "graph.embedding.query.similar",
		},
		{
			name:            "community detection",
			queryType:       "community",
			expectedSubject: "graph.clustering.query.community",
		},
		{
			name:            "anomaly detection",
			queryType:       "anomaly",
			expectedSubject: "graph.anomalies.query.detect",
		},
	}

	logger := slog.New(slog.NewTextHandler(bytes.NewBuffer(nil), nil))
	router := NewStaticRouter(logger)

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			subject := router.Route(tt.queryType)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}

func TestStaticRouter_Route_UnknownQueryType(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		queryType string
	}{
		{
			name:      "unknown query type",
			queryType: "nonexistent",
		},
		{
			name:      "empty string",
			queryType: "",
		},
		{
			name:      "misspelled type",
			queryType: "entitty",
		},
		{
			name:      "wrong case",
			queryType: "Entity",
		},
		{
			name:      "random string",
			queryType: "foobar",
		},
		{
			name:      "legacy intent type",
			queryType: "relationship",
		},
		{
			name:      "whitespace",
			queryType: "  ",
		},
		{
			name:      "special characters",
			queryType: "entity!@#",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var buf bytes.Buffer
			logger := slog.New(slog.NewTextHandler(&buf, nil))
			router := NewStaticRouter(logger)

			subject := router.Route(tt.queryType)

			// Should return empty string for unknown types
			assert.Empty(t, subject)

			// Should log warning for unknown types
			logOutput := buf.String()
			assert.Contains(t, logOutput, "unknown query type")
			assert.Contains(t, logOutput, tt.queryType)
		})
	}
}

func TestStaticRouter_Route_LogWarningForUnknown(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	logger := slog.New(slog.NewTextHandler(&buf, nil))
	router := NewStaticRouter(logger)

	_ = router.Route("unknown")

	logOutput := buf.String()
	assert.Contains(t, logOutput, "unknown query type")
	assert.Contains(t, logOutput, "unknown")
	assert.Contains(t, logOutput, "WARN")
}

func TestStaticRouter_Route_MultipleCallsConsistent(t *testing.T) {
	t.Parallel()

	logger := slog.New(slog.NewTextHandler(bytes.NewBuffer(nil), nil))
	router := NewStaticRouter(logger)

	// Call Route multiple times for the same query type
	const queryType = "entity"
	const iterations = 100

	firstResult := router.Route(queryType)
	require.NotEmpty(t, firstResult)

	for i := 0; i < iterations; i++ {
		result := router.Route(queryType)
		assert.Equal(t, firstResult, result, "routing should be consistent across calls")
	}
}

func TestStaticRouter_Route_EdgeCases(t *testing.T) {
	t.Parallel()

	logger := slog.New(slog.NewTextHandler(bytes.NewBuffer(nil), nil))
	router := NewStaticRouter(logger)

	t.Run("nil router returns empty", func(t *testing.T) {
		// Nil receiver returns empty string gracefully (no panic)
		var nilRouter *StaticRouter
		subject := nilRouter.Route("entity")
		assert.Empty(t, subject)
	})

	t.Run("empty query type returns empty", func(t *testing.T) {
		subject := router.Route("")
		assert.Empty(t, subject)
	})

	t.Run("unicode query type returns empty", func(t *testing.T) {
		subject := router.Route("实体")
		assert.Empty(t, subject)
	})

	t.Run("query type with null bytes returns empty", func(t *testing.T) {
		subject := router.Route("entity\x00")
		assert.Empty(t, subject)
	})
}

func TestStaticRouter_Route_AllKnownTypesAreUnique(t *testing.T) {
	t.Parallel()

	logger := slog.New(slog.NewTextHandler(bytes.NewBuffer(nil), nil))
	router := NewStaticRouter(logger)

	queryTypes := []string{
		"entity", "entityBatch", "entityPrefix",
		"outgoing", "incoming", "alias", "predicate",
		"spatial", "temporal",
		"semantic", "similar", "community", "anomaly",
	}

	subjects := make(map[string]string)
	for _, queryType := range queryTypes {
		subject := router.Route(queryType)
		require.NotEmpty(t, subject, "query type %q should have a subject", queryType)

		// Verify no duplicate subjects
		if existingType, exists := subjects[subject]; exists {
			t.Errorf("duplicate subject %q for query types %q and %q",
				subject, existingType, queryType)
		}
		subjects[subject] = queryType
	}
}

func TestStaticRouter_Route_SubjectFormat(t *testing.T) {
	t.Parallel()

	logger := slog.New(slog.NewTextHandler(bytes.NewBuffer(nil), nil))
	router := NewStaticRouter(logger)

	queryTypes := []string{
		"entity", "entityBatch", "entityPrefix",
		"outgoing", "incoming", "alias", "predicate",
		"spatial", "temporal",
		"semantic", "similar", "community", "anomaly",
	}

	for _, queryType := range queryTypes {
		t.Run(queryType, func(t *testing.T) {
			subject := router.Route(queryType)
			require.NotEmpty(t, subject)

			// All subjects should follow pattern: graph.{component}.query.{operation}
			assert.Contains(t, subject, "graph.")
			assert.Contains(t, subject, ".query.")

			// Subject should not have trailing/leading whitespace
			assert.Equal(t, subject, subject, "subject should not have whitespace")

			// Subject should be ASCII
			for _, r := range subject {
				assert.True(t, r < 128, "subject should be ASCII only")
			}
		})
	}
}

func TestStaticRouter_Route_DoesNotModifyState(t *testing.T) {
	t.Parallel()

	logger := slog.New(slog.NewTextHandler(bytes.NewBuffer(nil), nil))
	router := NewStaticRouter(logger)

	// Route should not modify the router's internal state
	// Call with known and unknown types in various orders
	_ = router.Route("entity")
	_ = router.Route("unknown")
	_ = router.Route("outgoing")
	_ = router.Route("another-unknown")
	_ = router.Route("semantic")

	// Verify all known types still work
	assert.Equal(t, "graph.ingest.query.entity", router.Route("entity"))
	assert.Equal(t, "graph.index.query.outgoing", router.Route("outgoing"))
	assert.Equal(t, "graph.embedding.query.search", router.Route("semantic"))

	// Verify unknown types still return empty
	assert.Empty(t, router.Route("unknown"))
	assert.Empty(t, router.Route("another-unknown"))
}
