// Code generated by Tester Agent. DO NOT EDIT.
// Task: graph-index - Index operations unit tests (refactor mode)
// Builder must make these tests pass without modification.

package graphindex

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/c360studio/semstreams/graph"
	"github.com/c360studio/semstreams/message"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ====================================================================================
// Index Update Logic Tests
// ====================================================================================

func TestUpdateOutgoingIndex_SerializationFormat(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	entityID := "c360.platform.robotics.mav1.drone.001"
	targetID := "c360.platform.robotics.mav1.mission.001"
	predicate := "robotics.assigned.mission"

	err := comp.UpdateOutgoingIndex(ctx, entityID, targetID, predicate)
	require.NoError(t, err)

	// Verify data was written
	bucket := outgoingMock(comp)
	bucket.mu.Lock()
	data, exists := bucket.data[entityID]
	bucket.mu.Unlock()

	assert.True(t, exists, "outgoing index should have entry for entity")
	assert.NotEmpty(t, data, "outgoing index data should not be empty")

	// Verify serialization format (array format matching graph/indexmanager)
	var entries []map[string]interface{}
	err = json.Unmarshal(data, &entries)
	require.NoError(t, err, "outgoing index should serialize as JSON array")
	require.Len(t, entries, 1, "should have one entry")

	assert.Equal(t, targetID, entries[0]["to_entity_id"], "should have to_entity_id field")
	assert.Equal(t, predicate, entries[0]["predicate"], "should have predicate field")
}

func TestUpdateIncomingIndex_SerializationFormat(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	targetID := "c360.platform.robotics.mav1.mission.001"
	sourceID := "c360.platform.robotics.mav1.drone.001"
	predicate := "robotics.assigned.mission"

	err := comp.UpdateIncomingIndex(ctx, targetID, sourceID, predicate)
	require.NoError(t, err)

	// Verify data was written
	bucket := incomingMock(comp)
	bucket.mu.Lock()
	data, exists := bucket.data[targetID]
	bucket.mu.Unlock()

	assert.True(t, exists, "incoming index should have entry for target")
	assert.NotEmpty(t, data, "incoming index data should not be empty")

	// Verify serialization format (array format matching graph/indexmanager)
	var entries []map[string]interface{}
	err = json.Unmarshal(data, &entries)
	require.NoError(t, err, "incoming index should serialize as JSON array")
	require.Len(t, entries, 1, "should have one entry")

	assert.Equal(t, sourceID, entries[0]["from_entity_id"], "should have from_entity_id field")
	assert.Equal(t, predicate, entries[0]["predicate"], "should have predicate field")
}

func TestUpdateAliasIndex_StoresPlainString(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	alias := "drone-001"
	entityID := "c360.platform.robotics.mav1.drone.001"

	err := comp.UpdateAliasIndex(ctx, alias, entityID)
	require.NoError(t, err)

	// Verify data was written (alias index stores plain strings)
	bucket := aliasMock(comp)
	bucket.mu.Lock()
	data, exists := bucket.data[alias]
	bucket.mu.Unlock()

	assert.True(t, exists, "alias index should have entry for alias")
	assert.Equal(t, entityID, string(data), "alias should map directly to entity ID")
}

func TestUpdatePredicateIndex_SerializationFormat(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	entityID := "c360.platform.robotics.mav1.drone.001"
	predicate := "robotics.status.armed"

	err := comp.UpdatePredicateIndex(ctx, entityID, predicate)
	require.NoError(t, err)

	// Verify data was written
	bucket := predicateMock(comp)
	bucket.mu.Lock()
	data, exists := bucket.data[predicate]
	bucket.mu.Unlock()

	assert.True(t, exists, "predicate index should have entry")
	assert.NotEmpty(t, data, "predicate index data should not be empty")

	// Verify serialization format
	var entry map[string]interface{}
	err = json.Unmarshal(data, &entry)
	require.NoError(t, err, "predicate index should serialize as JSON")

	assert.Equal(t, entityID, entry["entity_id"], "should have entity_id field")
	assert.Equal(t, predicate, entry["predicate"], "should have predicate field")
}

// ====================================================================================
// Index Update Validation Tests
// ====================================================================================

func TestUpdateOutgoingIndex_EmptyEntityID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdateOutgoingIndex(ctx, "", "target", "predicate")

	assert.Error(t, err, "should reject empty entity ID")
	assert.Contains(t, err.Error(), "entity ID cannot be empty")
}

func TestUpdateOutgoingIndex_EmptyTargetID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdateOutgoingIndex(ctx, "entity", "", "predicate")

	assert.Error(t, err, "should reject empty target ID")
	assert.Contains(t, err.Error(), "target ID cannot be empty")
}

func TestUpdateOutgoingIndex_EmptyPredicate_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdateOutgoingIndex(ctx, "entity", "target", "")

	assert.Error(t, err, "should reject empty predicate")
	assert.Contains(t, err.Error(), "predicate cannot be empty")
}

func TestUpdateIncomingIndex_EmptyTargetID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdateIncomingIndex(ctx, "", "source", "predicate")

	assert.Error(t, err, "should reject empty target ID")
	assert.Contains(t, err.Error(), "target ID cannot be empty")
}

func TestUpdateIncomingIndex_EmptySourceID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdateIncomingIndex(ctx, "target", "", "predicate")

	assert.Error(t, err, "should reject empty source ID")
	assert.Contains(t, err.Error(), "source ID cannot be empty")
}

func TestUpdateIncomingIndex_EmptyPredicate_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdateIncomingIndex(ctx, "target", "source", "")

	assert.Error(t, err, "should reject empty predicate")
	assert.Contains(t, err.Error(), "predicate cannot be empty")
}

func TestUpdateAliasIndex_EmptyAlias_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdateAliasIndex(ctx, "", "entity")

	assert.Error(t, err, "should reject empty alias")
	assert.Contains(t, err.Error(), "alias cannot be empty")
}

func TestUpdateAliasIndex_EmptyEntityID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdateAliasIndex(ctx, "alias", "")

	assert.Error(t, err, "should reject empty entity ID")
	assert.Contains(t, err.Error(), "entity ID cannot be empty")
}

func TestUpdatePredicateIndex_EmptyEntityID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdatePredicateIndex(ctx, "", "predicate")

	assert.Error(t, err, "should reject empty entity ID")
	assert.Contains(t, err.Error(), "entity ID cannot be empty")
}

func TestUpdatePredicateIndex_EmptyPredicate_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.UpdatePredicateIndex(ctx, "entity", "")

	assert.Error(t, err, "should reject empty predicate")
	assert.Contains(t, err.Error(), "predicate cannot be empty")
}

// ====================================================================================
// Index Deletion Validation Tests
// ====================================================================================

func TestDeleteFromIndexes_EmptyEntityID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.DeleteFromIndexes(ctx, "")

	assert.Error(t, err, "should reject empty entity ID")
	assert.Contains(t, err.Error(), "entity ID cannot be empty")
}

func TestDeleteFromPredicateIndex_EmptyEntityID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.DeleteFromPredicateIndex(ctx, "", "predicate")

	assert.Error(t, err, "should reject empty entity ID")
	assert.Contains(t, err.Error(), "entity ID cannot be empty")
}

func TestDeleteFromPredicateIndex_EmptyPredicate_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.DeleteFromPredicateIndex(ctx, "entity", "")

	assert.Error(t, err, "should reject empty predicate")
	assert.Contains(t, err.Error(), "predicate cannot be empty")
}

func TestDeleteFromAliasIndex_EmptyAlias_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.DeleteFromAliasIndex(ctx, "")

	assert.Error(t, err, "should reject empty alias")
	assert.Contains(t, err.Error(), "alias cannot be empty")
}

func TestDeleteFromIncomingIndex_EmptyTargetID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.DeleteFromIncomingIndex(ctx, "", "source")

	assert.Error(t, err, "should reject empty target ID")
	assert.Contains(t, err.Error(), "target ID cannot be empty")
}

func TestDeleteFromIncomingIndex_EmptySourceID_ReturnsError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	err := comp.DeleteFromIncomingIndex(ctx, "target", "")

	assert.Error(t, err, "should reject empty source ID")
	assert.Contains(t, err.Error(), "source ID cannot be empty")
}

// ====================================================================================
// Entity State Processing Tests
// ====================================================================================

func TestProcessEntityUpdate_TripleIndexing(t *testing.T) {
	tests := []struct {
		name          string
		triples       []message.Triple
		wantOutgoing  bool
		wantIncoming  bool
		wantAlias     bool
		wantPredicate int // Count of predicates indexed
	}{
		{
			name: "relationship triple indexes outgoing and incoming",
			triples: []message.Triple{
				{
					Subject:   "c360.platform.robotics.mav1.drone.001",
					Predicate: "robotics.assigned.mission",
					Object:    "c360.platform.robotics.mav1.mission.001",
				},
			},
			wantOutgoing:  true,
			wantIncoming:  true,
			wantAlias:     false,
			wantPredicate: 1,
		},
		{
			name: "literal triple indexes only predicate",
			triples: []message.Triple{
				{
					Subject:   "c360.platform.robotics.mav1.drone.001",
					Predicate: "robotics.status.armed",
					Object:    true,
				},
			},
			wantOutgoing:  false,
			wantIncoming:  false,
			wantAlias:     false,
			wantPredicate: 1,
		},
		{
			name: "alias triple indexes alias",
			triples: []message.Triple{
				{
					Subject:   "c360.platform.robotics.mav1.drone.001",
					Predicate: "core.identity.alias",
					Object:    "drone-001",
				},
			},
			wantOutgoing:  false,
			wantIncoming:  false,
			wantAlias:     true,
			wantPredicate: 1,
		},
		{
			name: "multiple triples index appropriately",
			triples: []message.Triple{
				{
					Subject:   "c360.platform.robotics.mav1.drone.001",
					Predicate: "robotics.assigned.mission",
					Object:    "c360.platform.robotics.mav1.mission.001",
				},
				{
					Subject:   "c360.platform.robotics.mav1.drone.001",
					Predicate: "robotics.status.armed",
					Object:    true,
				},
				{
					Subject:   "c360.platform.robotics.mav1.drone.001",
					Predicate: "core.identity.alias",
					Object:    "drone-001",
				},
			},
			wantOutgoing:  true,
			wantIncoming:  true,
			wantAlias:     true,
			wantPredicate: 3,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			comp := createTestComponentWithMockKV(t)

			entityID := "c360.platform.robotics.mav1.drone.001"
			state := graph.EntityState{
				Triples: tt.triples,
			}

			// Create mock entry
			data, err := json.Marshal(state)
			require.NoError(t, err)

			entry := &mockKVEntry{data: data}
			comp.processEntityUpdate(context.Background(), entry)

			// Verify outgoing index
			outgoing := outgoingMock(comp)
			outgoing.mu.Lock()
			_, hasOutgoing := outgoing.data[entityID]
			outgoing.mu.Unlock()
			assert.Equal(t, tt.wantOutgoing, hasOutgoing, "outgoing index presence mismatch")

			// Verify incoming index
			if tt.wantIncoming {
				incoming := incomingMock(comp)
				incoming.mu.Lock()
				hasIncoming := len(incoming.data) > 0
				incoming.mu.Unlock()
				assert.True(t, hasIncoming, "incoming index should have entries")
			}

			// Verify alias index
			if tt.wantAlias {
				alias := aliasMock(comp)
				alias.mu.Lock()
				hasAlias := len(alias.data) > 0
				alias.mu.Unlock()
				assert.True(t, hasAlias, "alias index should have entries")
			}

			// Verify predicate index
			predicate := predicateMock(comp)
			predicate.mu.Lock()
			predicateCount := len(predicate.data)
			predicate.mu.Unlock()
			assert.Equal(t, tt.wantPredicate, predicateCount, "predicate count mismatch")
		})
	}
}

func TestProcessEntityUpdate_RelationshipDetection(t *testing.T) {
	tests := []struct {
		name           string
		triple         message.Triple
		isRelationship bool
	}{
		{
			name: "entity ID as object is relationship",
			triple: message.Triple{
				Subject:   "c360.platform.robotics.mav1.drone.001",
				Predicate: "robotics.assigned.mission",
				Object:    "c360.platform.robotics.mav1.mission.001",
			},
			isRelationship: true,
		},
		{
			name: "string literal is not relationship",
			triple: message.Triple{
				Subject:   "c360.platform.robotics.mav1.drone.001",
				Predicate: "robotics.description",
				Object:    "A quadcopter drone",
			},
			isRelationship: false,
		},
		{
			name: "boolean literal is not relationship",
			triple: message.Triple{
				Subject:   "c360.platform.robotics.mav1.drone.001",
				Predicate: "robotics.status.armed",
				Object:    true,
			},
			isRelationship: false,
		},
		{
			name: "numeric literal is not relationship",
			triple: message.Triple{
				Subject:   "c360.platform.robotics.mav1.drone.001",
				Predicate: "robotics.battery.level",
				Object:    85.5,
			},
			isRelationship: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			comp := createTestComponentWithMockKV(t)

			entityID := "c360.platform.robotics.mav1.drone.001"
			state := graph.EntityState{
				Triples: []message.Triple{tt.triple},
			}

			// Create mock entry
			data, err := json.Marshal(state)
			require.NoError(t, err)

			entry := &mockKVEntry{data: data}
			comp.processEntityUpdate(context.Background(), entry)

			// Check if outgoing/incoming indexes were populated
			outgoing := outgoingMock(comp)
			outgoing.mu.Lock()
			_, hasOutgoing := outgoing.data[entityID]
			outgoing.mu.Unlock()

			assert.Equal(t, tt.isRelationship, hasOutgoing,
				"relationship detection mismatch: expected %v, got %v", tt.isRelationship, hasOutgoing)
		})
	}
}

// ====================================================================================
// Entity Deletion Tests
// ====================================================================================

func TestHandleEntityDelete_RemovesFromIndexes(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	entityID := "c360.platform.robotics.mav1.drone.001"

	// Create some index entries first
	require.NoError(t, comp.UpdateOutgoingIndex(ctx, entityID, "target", "predicate"))
	require.NoError(t, comp.UpdateIncomingIndex(ctx, entityID, "source", "predicate"))

	// Verify entries exist
	outgoing := outgoingMock(comp)
	outgoing.mu.Lock()
	_, hasOutgoing := outgoing.data[entityID]
	outgoing.mu.Unlock()
	assert.True(t, hasOutgoing, "should have outgoing entry before delete")

	// Delete entity
	comp.handleEntityDelete(ctx, entityID)

	// Verify entries removed
	outgoing.mu.Lock()
	_, stillHasOutgoing := outgoing.data[entityID]
	outgoing.mu.Unlock()
	assert.False(t, stillHasOutgoing, "should remove outgoing entry after delete")

	incoming := incomingMock(comp)
	incoming.mu.Lock()
	_, stillHasIncoming := incoming.data[entityID]
	incoming.mu.Unlock()
	assert.False(t, stillHasIncoming, "should remove incoming entry after delete")
}

func TestDeleteFromIndexes_IgnoresKeyNotFoundError(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	// Delete non-existent entity - should not error
	err := comp.DeleteFromIndexes(ctx, "non-existent-entity")

	assert.NoError(t, err, "should gracefully handle non-existent entity deletion")
}

// ====================================================================================
// Context Handling Tests
// ====================================================================================

func TestUpdateIndex_RespectsContextCancellation(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel() // Cancel immediately

	err := comp.UpdateOutgoingIndex(ctx, "entity", "target", "predicate")

	assert.Error(t, err, "should fail with cancelled context")
	assert.Contains(t, err.Error(), "context")
}

func TestUpdateIndex_RespectsContextTimeout(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Nanosecond)
	defer cancel()

	time.Sleep(10 * time.Millisecond) // Ensure timeout expires

	err := comp.UpdateOutgoingIndex(ctx, "entity", "target", "predicate")

	// Should either succeed (if fast enough) or fail with timeout
	if err != nil {
		assert.Contains(t, err.Error(), "context")
	}
}

func TestDeleteFromIndexes_RespectsContextCancellation(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel() // Cancel immediately

	err := comp.DeleteFromIndexes(ctx, "entity")

	assert.Error(t, err, "should fail with cancelled context")
	assert.Contains(t, err.Error(), "context")
}

// ====================================================================================
// Metrics Update Tests
// ====================================================================================

func TestUpdateIndex_UpdatesMetrics(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	initialProcessed := comp.messagesProcessed
	initialBytes := comp.bytesProcessed

	err := comp.UpdateOutgoingIndex(ctx, "entity", "target", "predicate")
	require.NoError(t, err)

	// Verify metrics incremented
	assert.Greater(t, comp.messagesProcessed, initialProcessed, "messages processed should increment")
	assert.Greater(t, comp.bytesProcessed, initialBytes, "bytes processed should increment")
}

func TestDeleteFromIndexes_UpdatesMetrics(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	// Add entry first
	require.NoError(t, comp.UpdateOutgoingIndex(ctx, "entity", "target", "predicate"))

	initialProcessed := comp.messagesProcessed

	err := comp.DeleteFromIndexes(ctx, "entity")
	require.NoError(t, err)

	// Verify metrics incremented
	assert.Greater(t, comp.messagesProcessed, initialProcessed, "messages processed should increment on delete")
}

func TestUpdateIndex_UpdatesLastActivity(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	initialActivity := comp.lastActivity.Load().(time.Time)

	time.Sleep(10 * time.Millisecond)

	err := comp.UpdateOutgoingIndex(ctx, "entity", "target", "predicate")
	require.NoError(t, err)

	updatedActivity := comp.lastActivity.Load().(time.Time)
	assert.True(t, updatedActivity.After(initialActivity), "last activity should update")
}
