// Code generated by Tester Agent. DO NOT EDIT.
// Task: NLQ Phase 1 — graphTransform.transformGlobalSearchResult tests
// Builder must make these tests pass without modification.

import { describe, it, expect } from "vitest";
import { transformGlobalSearchResult } from "./graphTransform";
import type { GlobalSearchResult } from "$lib/types/graph";

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

const DRONE_001 = "c360.ops.robotics.gcs.drone.001";
const DRONE_002 = "c360.ops.robotics.gcs.drone.002";
const FLEET_ALPHA = "c360.ops.robotics.gcs.fleet.alpha";

function makeResult(
  overrides: Partial<GlobalSearchResult> = {},
): GlobalSearchResult {
  return {
    entities: [],
    communitySummaries: [],
    relationships: [],
    count: 0,
    durationMs: 0,
    ...overrides,
  };
}

describe("transformGlobalSearchResult", () => {
  // ---------------------------------------------------------------------------
  // Basic transformation
  // ---------------------------------------------------------------------------

  describe("entity transformation", () => {
    it("should return an empty array for empty results", () => {
      const result = transformGlobalSearchResult(makeResult());
      expect(result).toEqual([]);
    });

    it("should transform a single entity to GraphEntity", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: DRONE_001,
              triples: [],
            },
          ],
        }),
      );

      expect(result).toHaveLength(1);
      expect(result[0].id).toBe(DRONE_001);
      expect(result[0].idParts).toEqual({
        org: "c360",
        platform: "ops",
        domain: "robotics",
        system: "gcs",
        type: "drone",
        instance: "001",
      });
    });

    it("should transform multiple entities", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            { id: DRONE_001, triples: [] },
            { id: DRONE_002, triples: [] },
            { id: FLEET_ALPHA, triples: [] },
          ],
        }),
      );

      expect(result).toHaveLength(3);
      const ids = result.map((e) => e.id);
      expect(ids).toContain(DRONE_001);
      expect(ids).toContain(DRONE_002);
      expect(ids).toContain(FLEET_ALPHA);
    });

    it("should handle entities with no triples", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [{ id: DRONE_001, triples: [] }],
        }),
      );

      expect(result[0].properties).toHaveLength(0);
      expect(result[0].outgoing).toHaveLength(0);
      expect(result[0].incoming).toHaveLength(0);
    });
  });

  // ---------------------------------------------------------------------------
  // Triple processing — properties vs relationships
  // ---------------------------------------------------------------------------

  describe("triple extraction", () => {
    it("should extract literal-valued triples as properties", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: DRONE_001,
              triples: [
                {
                  subject: DRONE_001,
                  predicate: "core.property.name",
                  object: "Drone 001",
                },
                {
                  subject: DRONE_001,
                  predicate: "telemetry.sensor.altitude",
                  object: 150.5,
                },
                {
                  subject: DRONE_001,
                  predicate: "core.status.armed",
                  object: false,
                },
              ],
            },
          ],
        }),
      );

      expect(result[0].properties).toHaveLength(3);
      expect(result[0].properties[0]).toMatchObject({
        predicate: "core.property.name",
        object: "Drone 001",
      });
      expect(result[0].properties[1]).toMatchObject({
        predicate: "telemetry.sensor.altitude",
        object: 150.5,
      });
      expect(result[0].properties[2]).toMatchObject({
        predicate: "core.status.armed",
        object: false,
      });
    });

    it("should extract entity-reference triples as outgoing relationships", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: DRONE_001,
              triples: [
                {
                  subject: DRONE_001,
                  predicate: "fleet.membership.current",
                  object: FLEET_ALPHA,
                },
              ],
            },
          ],
        }),
      );

      expect(result[0].properties).toHaveLength(0);
      expect(result[0].outgoing).toHaveLength(1);
      expect(result[0].outgoing[0]).toMatchObject({
        sourceId: DRONE_001,
        targetId: FLEET_ALPHA,
        predicate: "fleet.membership.current",
      });
      expect(result[0].outgoing[0].id).toBe(
        `${DRONE_001}:fleet.membership.current:${FLEET_ALPHA}`,
      );
    });

    it("should not treat short dotted strings as entity references", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: DRONE_001,
              triples: [
                {
                  subject: DRONE_001,
                  predicate: "core.property.shortcode",
                  object: "abc.def.ghi", // 3 parts — not an entity ID
                },
              ],
            },
          ],
        }),
      );

      expect(result[0].properties).toHaveLength(1);
      expect(result[0].outgoing).toHaveLength(0);
    });

    it("should mix properties and relationship triples correctly", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: DRONE_001,
              triples: [
                {
                  subject: DRONE_001,
                  predicate: "core.property.model",
                  object: "M30T",
                },
                {
                  subject: DRONE_001,
                  predicate: "fleet.membership.current",
                  object: FLEET_ALPHA,
                },
                {
                  subject: DRONE_001,
                  predicate: "telemetry.sensor.battery",
                  object: 85,
                },
              ],
            },
          ],
        }),
      );

      expect(result[0].properties).toHaveLength(2);
      expect(result[0].outgoing).toHaveLength(1);
    });
  });

  // ---------------------------------------------------------------------------
  // Explicit SearchRelationship processing
  // ---------------------------------------------------------------------------

  describe("explicit relationship processing", () => {
    it("should process explicit SearchRelationship entries as edges", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            { id: DRONE_001, triples: [] },
            { id: FLEET_ALPHA, triples: [] },
          ],
          relationships: [
            {
              from: DRONE_001,
              to: FLEET_ALPHA,
              predicate: "fleet.membership.current",
            },
          ],
        }),
      );

      const drone = result.find((e) => e.id === DRONE_001)!;
      const fleet = result.find((e) => e.id === FLEET_ALPHA)!;

      expect(drone.outgoing).toHaveLength(1);
      expect(drone.outgoing[0]).toMatchObject({
        sourceId: DRONE_001,
        targetId: FLEET_ALPHA,
        predicate: "fleet.membership.current",
      });

      expect(fleet.incoming).toHaveLength(1);
      expect(fleet.incoming[0]).toMatchObject({
        sourceId: DRONE_001,
        targetId: FLEET_ALPHA,
        predicate: "fleet.membership.current",
      });
    });

    it("should ignore explicit relationships where from entity is not in results", () => {
      // Only FLEET_ALPHA is in entities; DRONE_001 is not
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [{ id: FLEET_ALPHA, triples: [] }],
          relationships: [
            {
              from: DRONE_001,
              to: FLEET_ALPHA,
              predicate: "fleet.membership.current",
            },
          ],
        }),
      );

      // fleet.incoming should still be populated even when source isn't in results
      const fleet = result.find((e) => e.id === FLEET_ALPHA)!;
      // The relationship target is in results — the incoming edge should appear
      expect(fleet.incoming).toHaveLength(1);
      expect(fleet.incoming[0].sourceId).toBe(DRONE_001);
    });

    it("should handle multiple explicit relationships", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            { id: DRONE_001, triples: [] },
            { id: DRONE_002, triples: [] },
            { id: FLEET_ALPHA, triples: [] },
          ],
          relationships: [
            {
              from: DRONE_001,
              to: FLEET_ALPHA,
              predicate: "fleet.membership.current",
            },
            {
              from: DRONE_002,
              to: FLEET_ALPHA,
              predicate: "fleet.membership.current",
            },
          ],
        }),
      );

      const fleet = result.find((e) => e.id === FLEET_ALPHA)!;
      expect(fleet.incoming).toHaveLength(2);
    });
  });

  // ---------------------------------------------------------------------------
  // Deduplication — relationships from triples vs explicit list
  // ---------------------------------------------------------------------------

  describe("relationship deduplication", () => {
    it("should deduplicate relationships that appear in both triples and explicit list", () => {
      // Same relationship described twice: once as a triple on DRONE_001,
      // once in the explicit relationships array.
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: DRONE_001,
              triples: [
                {
                  subject: DRONE_001,
                  predicate: "fleet.membership.current",
                  object: FLEET_ALPHA,
                },
              ],
            },
            { id: FLEET_ALPHA, triples: [] },
          ],
          relationships: [
            {
              from: DRONE_001,
              to: FLEET_ALPHA,
              predicate: "fleet.membership.current",
            },
          ],
        }),
      );

      const drone = result.find((e) => e.id === DRONE_001)!;
      // Despite appearing twice (triple + explicit), the outgoing edge should
      // appear only once.
      expect(drone.outgoing).toHaveLength(1);
    });

    it("should not deduplicate genuinely different relationships", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: DRONE_001,
              triples: [
                {
                  subject: DRONE_001,
                  predicate: "fleet.membership.current",
                  object: FLEET_ALPHA,
                },
              ],
            },
            { id: FLEET_ALPHA, triples: [] },
          ],
          relationships: [
            {
              from: DRONE_001,
              to: FLEET_ALPHA,
              predicate: "fleet.membership.previous", // different predicate
            },
          ],
        }),
      );

      const drone = result.find((e) => e.id === DRONE_001)!;
      expect(drone.outgoing).toHaveLength(2);
    });
  });

  // ---------------------------------------------------------------------------
  // Table-driven edge cases
  // ---------------------------------------------------------------------------

  describe("table-driven edge cases", () => {
    const entityTripleCases = [
      {
        description: "numeric object (integer) is a property",
        triple: { subject: DRONE_001, predicate: "telemetry.speed", object: 42 },
        expectProperty: true,
      },
      {
        description: "numeric object (float) is a property",
        triple: {
          subject: DRONE_001,
          predicate: "telemetry.altitude",
          object: 3.14,
        },
        expectProperty: true,
      },
      {
        description: "boolean object is a property",
        triple: {
          subject: DRONE_001,
          predicate: "core.status.active",
          object: true,
        },
        expectProperty: true,
      },
      {
        description: "null object is a property",
        triple: {
          subject: DRONE_001,
          predicate: "core.property.optional",
          object: null,
        },
        expectProperty: true,
      },
      {
        description: "6-part dotted string is a relationship",
        triple: {
          subject: DRONE_001,
          predicate: "fleet.membership.current",
          object: FLEET_ALPHA,
        },
        expectProperty: false,
      },
      {
        description: "5-part dotted string is a property",
        triple: {
          subject: DRONE_001,
          predicate: "core.property.code",
          object: "a.b.c.d.e",
        },
        expectProperty: true,
      },
      {
        description: "7-part dotted string is a property",
        triple: {
          subject: DRONE_001,
          predicate: "core.property.code",
          object: "a.b.c.d.e.f.g",
        },
        expectProperty: true,
      },
    ];

    it.each(entityTripleCases)(
      "triple classification: $description",
      ({ triple, expectProperty }) => {
        const result = transformGlobalSearchResult(
          makeResult({
            entities: [{ id: DRONE_001, triples: [triple] }],
          }),
        );

        if (expectProperty) {
          expect(result[0].properties).toHaveLength(1);
          expect(result[0].outgoing).toHaveLength(0);
        } else {
          expect(result[0].properties).toHaveLength(0);
          expect(result[0].outgoing).toHaveLength(1);
        }
      },
    );
  });

  // ---------------------------------------------------------------------------
  // GraphEntity structure integrity
  // ---------------------------------------------------------------------------

  describe("GraphEntity structure", () => {
    it("should initialise outgoing and incoming as empty arrays by default", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [{ id: DRONE_001, triples: [] }],
        }),
      );

      expect(Array.isArray(result[0].outgoing)).toBe(true);
      expect(Array.isArray(result[0].incoming)).toBe(true);
      expect(Array.isArray(result[0].properties)).toBe(true);
    });

    it("should generate unique relationship IDs using source:predicate:target format", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: DRONE_001,
              triples: [
                {
                  subject: DRONE_001,
                  predicate: "fleet.membership.current",
                  object: FLEET_ALPHA,
                },
                {
                  subject: DRONE_001,
                  predicate: "fleet.membership.previous",
                  object: FLEET_ALPHA,
                },
              ],
            },
          ],
        }),
      );

      const outgoing = result[0].outgoing;
      expect(outgoing).toHaveLength(2);
      expect(outgoing[0].id).not.toBe(outgoing[1].id);
      expect(outgoing[0].id).toBe(
        `${DRONE_001}:fleet.membership.current:${FLEET_ALPHA}`,
      );
      expect(outgoing[1].id).toBe(
        `${DRONE_001}:fleet.membership.previous:${FLEET_ALPHA}`,
      );
    });

    it("should handle malformed entity IDs gracefully", () => {
      const result = transformGlobalSearchResult(
        makeResult({
          entities: [
            {
              id: "malformed.id",
              triples: [
                {
                  subject: "malformed.id",
                  predicate: "core.property.name",
                  object: "Bad Entity",
                },
              ],
            },
          ],
        }),
      );

      expect(result).toHaveLength(1);
      expect(result[0].id).toBe("malformed.id");
      expect(result[0].idParts).toMatchObject({
        org: "malformed",
        platform: "id",
        domain: "unknown",
      });
      expect(result[0].properties).toHaveLength(1);
    });
  });
});
