// Code generated by Tester Agent. DO NOT EDIT.
// Task: NLQ Phase 3 — DataView merge/replace mode integration tests
// Builder must make these tests pass without modification.

import { describe, it, expect, beforeEach, vi } from "vitest";
import { render, screen, waitFor } from "@testing-library/svelte";
import userEvent from "@testing-library/user-event";
import DataView from "./DataView.svelte";
import type { PathSearchResult, GlobalSearchResult } from "$lib/types/graph";
import { GraphApiError } from "$lib/services/graphApi";

// ---------------------------------------------------------------------------
// Module mocks — same pattern as DataView.nlq.test.ts
// ---------------------------------------------------------------------------

vi.mock("$lib/services/graphApi", () => {
  return {
    graphApi: {
      pathSearch: vi.fn(),
      globalSearch: vi.fn(),
    },
    GraphApiError: class GraphApiError extends Error {
      constructor(
        message: string,
        public statusCode: number,
        public details?: unknown,
      ) {
        super(message);
        this.name = "GraphApiError";
      }
    },
  };
});

import { graphApi } from "$lib/services/graphApi";

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

const mockPathSearchFn = graphApi.pathSearch as ReturnType<typeof vi.fn>;
const mockGlobalSearchFn = graphApi.globalSearch as ReturnType<typeof vi.fn>;

// Two distinct entity IDs — one from pathSearch, one from globalSearch
const FLEET_ALPHA = "c360.ops.robotics.gcs.fleet.alpha";
const DRONE_001 = "c360.ops.robotics.gcs.drone.001";
// A third entity that exists in both pathSearch and globalSearch (for dedup tests)
const SENSOR_NORTH = "c360.ops.robotics.gcs.sensor.north";

function makePathSearchResult(
  extraEntities: PathSearchResult["entities"] = [],
): PathSearchResult {
  return {
    entities: [
      {
        id: FLEET_ALPHA,
        triples: [
          {
            subject: FLEET_ALPHA,
            predicate: "fleet.name",
            object: "Alpha Fleet",
          },
        ],
      },
      ...extraEntities,
    ],
    edges: [],
  };
}

function makeGlobalSearchResult(
  overrides: Partial<GlobalSearchResult> = {},
): GlobalSearchResult {
  return {
    entities: [
      {
        id: DRONE_001,
        triples: [
          {
            subject: DRONE_001,
            predicate: "core.property.name",
            object: "Drone 001",
          },
        ],
      },
    ],
    communitySummaries: [],
    relationships: [],
    count: 1,
    durationMs: 30,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Shared setup
// ---------------------------------------------------------------------------

describe("DataView NLQ Phase 3 — Merge/Replace Mode", () => {
  beforeEach(() => {
    mockPathSearchFn.mockClear();
    mockGlobalSearchFn.mockClear();
    mockPathSearchFn.mockResolvedValue(makePathSearchResult());
  });

  // -------------------------------------------------------------------------
  // Replace mode — verify default behavior is unchanged
  // -------------------------------------------------------------------------

  describe("replace mode (default behavior)", () => {
    it("should use replace mode by default", async () => {
      render(DataView, { props: { flowId: "test-flow-p3" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      // The search mode toggle should reflect replace as default when visible
      // The toggle is only visible when searchMode prop is passed — DataView must
      // pass searchMode to NlqSearchBar. Verify toggle exists and shows "replace".
      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        expect(toggle).toHaveTextContent(/replace/i);
      }
    });

    it("should call globalSearch when a query is submitted in replace mode", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      await user.type(
        screen.getByRole("textbox"),
        "show all drones{Enter}",
      );

      await waitFor(() => {
        expect(mockGlobalSearchFn).toHaveBeenCalledOnce();
      });
    });

    it("should enter search mode after a successful search in replace mode", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      await user.type(screen.getByRole("textbox"), "drones{Enter}");

      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: /back to browse/i }),
        ).toBeInTheDocument();
      });
    });

    it("should reload pathSearch data when Back to browse is clicked in replace mode", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalledTimes(1));

      await user.type(screen.getByRole("textbox"), "drones{Enter}");

      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: /back to browse/i }),
        ).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: /back to browse/i }));

      await waitFor(() => {
        expect(mockPathSearchFn).toHaveBeenCalledTimes(2);
      });
    });
  });

  // -------------------------------------------------------------------------
  // Merge mode — core behavior
  // -------------------------------------------------------------------------

  describe("merge mode — entity preservation", () => {
    it("should not clear existing pathSearch entities when searching in merge mode", async () => {
      // pathSearch loads FLEET_ALPHA; globalSearch returns DRONE_001.
      // In merge mode, both should be in the graph.
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-merge" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      // Switch to merge mode
      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => {
          expect(toggle).toHaveTextContent(/merge/i);
        });
      } else {
        // Toggle not rendered yet — skip this test body; the merge behavior
        // is verified through DataView's internal state after mode switch.
        // This branch means the Builder has not yet added the toggle.
        return;
      }

      await user.type(screen.getByRole("textbox"), "find drones{Enter}");

      // After merge search, the loading indicator should resolve
      await waitFor(() => {
        expect(mockGlobalSearchFn).toHaveBeenCalledOnce();
        expect(
          screen.queryByTestId("nlq-loading-indicator"),
        ).not.toBeInTheDocument();
      });

      // Both pathSearch and globalSearch entities exist: entity count >= 2
      // We verify this by checking graphStore is in a state with both entities.
      // Since we cannot inspect the store directly in this test, we verify
      // the component did NOT crash and search mode was entered.
      expect(
        screen.getByRole("button", { name: /back to browse/i }),
      ).toBeInTheDocument();
    });

    it("should add globalSearch entities alongside pathSearch entities in merge mode", async () => {
      // Set up pathSearch with FLEET_ALPHA, globalSearch with DRONE_001.
      // After merge search, graphStore.entities should contain both.
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      // We spy on graphStore to verify clearEntities is NOT called in merge mode
      // but upsertEntities IS called.
      const { graphStore } = await import("$lib/stores/graphStore.svelte");
      const clearEntitiesSpy = vi.spyOn(graphStore, "clearEntities");
      const upsertEntitiesSpy = vi.spyOn(graphStore, "upsertEntities");

      render(DataView, { props: { flowId: "test-flow-p3-merge-add" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      // Ensure initial data loaded
      await waitFor(() => {
        expect(upsertEntitiesSpy).toHaveBeenCalled();
      });

      const clearCallsAfterLoad = clearEntitiesSpy.mock.calls.length;

      // Switch to merge mode
      const toggle = screen.queryByTestId("search-mode-toggle");
      if (!toggle) {
        // Toggle not yet implemented — clean up and return
        clearEntitiesSpy.mockRestore();
        upsertEntitiesSpy.mockRestore();
        return;
      }
      await user.click(toggle);
      await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));

      await user.type(screen.getByRole("textbox"), "merge query{Enter}");

      await waitFor(() => {
        expect(mockGlobalSearchFn).toHaveBeenCalled();
        expect(
          screen.queryByTestId("nlq-loading-indicator"),
        ).not.toBeInTheDocument();
      });

      // In merge mode, clearEntities should NOT have been called since the initial load
      expect(clearEntitiesSpy.mock.calls.length).toBe(clearCallsAfterLoad);

      // upsertEntities MUST have been called again (for search results)
      expect(upsertEntitiesSpy.mock.calls.length).toBeGreaterThan(1);

      clearEntitiesSpy.mockRestore();
      upsertEntitiesSpy.mockRestore();
    });

    it("should call clearEntities before upsertEntities in replace mode (default)", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      const { graphStore } = await import("$lib/stores/graphStore.svelte");
      const clearEntitiesSpy = vi.spyOn(graphStore, "clearEntities");

      render(DataView, { props: { flowId: "test-flow-p3-replace-clear" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      // Record how many times clearEntities was called during initial mount
      const clearCallsAfterLoad = clearEntitiesSpy.mock.calls.length;

      // Submit search in default (replace) mode — no toggle click
      await user.type(screen.getByRole("textbox"), "replace query{Enter}");

      await waitFor(() => {
        expect(mockGlobalSearchFn).toHaveBeenCalled();
        expect(
          screen.queryByTestId("nlq-loading-indicator"),
        ).not.toBeInTheDocument();
      });

      // In replace mode, clearEntities must be called at least once more
      // (before loading search results)
      expect(clearEntitiesSpy.mock.calls.length).toBeGreaterThan(
        clearCallsAfterLoad,
      );

      clearEntitiesSpy.mockRestore();
    });

    it("should still enter search mode after a merge search", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-merge-mode" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      await user.type(screen.getByRole("textbox"), "merge search{Enter}");

      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: /back to browse/i }),
        ).toBeInTheDocument();
      });
    });

    it("should still show Back to browse after a merge search", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-btb-merge" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      await user.type(screen.getByRole("textbox"), "fleet query{Enter}");

      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: /back to browse/i }),
        ).toBeInTheDocument();
      });
    });
  });

  // -------------------------------------------------------------------------
  // Deduplication in merge mode
  // -------------------------------------------------------------------------

  describe("merge mode — entity deduplication", () => {
    it("should deduplicate entities by ID when globalSearch returns an entity already in pathSearch", async () => {
      // pathSearch returns FLEET_ALPHA and SENSOR_NORTH.
      // globalSearch also returns SENSOR_NORTH (overlap).
      // After merge, the store should have exactly FLEET_ALPHA, SENSOR_NORTH, and DRONE_001
      // (not a duplicate SENSOR_NORTH entry).
      mockPathSearchFn.mockResolvedValue(
        makePathSearchResult([
          {
            id: SENSOR_NORTH,
            triples: [
              {
                subject: SENSOR_NORTH,
                predicate: "sensor.status",
                object: "active",
              },
            ],
          },
        ]),
      );
      mockGlobalSearchFn.mockResolvedValue(
        makeGlobalSearchResult({
          entities: [
            {
              id: DRONE_001,
              triples: [
                {
                  subject: DRONE_001,
                  predicate: "core.property.name",
                  object: "Drone 001",
                },
              ],
            },
            // SENSOR_NORTH appears in both pathSearch and globalSearch
            {
              id: SENSOR_NORTH,
              triples: [
                {
                  subject: SENSOR_NORTH,
                  predicate: "sensor.status",
                  object: "updated",
                },
              ],
            },
          ],
        }),
      );

      const user = userEvent.setup();

      const { graphStore } = await import("$lib/stores/graphStore.svelte");

      render(DataView, { props: { flowId: "test-flow-p3-dedup" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      await user.type(screen.getByRole("textbox"), "sensor query{Enter}");

      await waitFor(() => {
        expect(mockGlobalSearchFn).toHaveBeenCalled();
        expect(
          screen.queryByTestId("nlq-loading-indicator"),
        ).not.toBeInTheDocument();
      });

      // The store should contain exactly 3 unique entities (no duplicate SENSOR_NORTH)
      // upsertEntities handles deduplication by ID — SvelteMap.set() overwrites same key
      expect(graphStore.entities.size).toBe(3);
    });
  });

  // -------------------------------------------------------------------------
  // Back to browse reloads pathSearch regardless of mode
  // -------------------------------------------------------------------------

  describe("Back to browse in merge mode", () => {
    it("should reload pathSearch when Back to browse is clicked in merge mode", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-btb-reload" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalledTimes(1));

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      await user.type(screen.getByRole("textbox"), "merge then back{Enter}");

      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: /back to browse/i }),
        ).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: /back to browse/i }));

      await waitFor(() => {
        expect(mockPathSearchFn).toHaveBeenCalledTimes(2);
      });
    });

    it("should reset search mode to replace when Back to browse is clicked", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-reset-mode" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      // Switch to merge mode
      const toggle = screen.queryByTestId("search-mode-toggle");
      if (!toggle) {
        // Toggle not implemented yet — guard the test
        return;
      }

      await user.click(toggle);
      await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));

      await user.type(screen.getByRole("textbox"), "query for reset{Enter}");

      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: /back to browse/i }),
        ).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: /back to browse/i }));

      // After Back to browse, search mode should reset to replace
      await waitFor(() => {
        expect(screen.getByTestId("search-mode-toggle")).toHaveTextContent(
          /replace/i,
        );
      });
    });

    it("should exit search mode when Back to browse is clicked after merge search", async () => {
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-exit-merge" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      await user.type(screen.getByRole("textbox"), "exit merge mode{Enter}");

      await waitFor(() => {
        expect(
          screen.getByRole("button", { name: /back to browse/i }),
        ).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: /back to browse/i }));

      await waitFor(() => {
        expect(
          screen.queryByRole("button", { name: /back to browse/i }),
        ).not.toBeInTheDocument();
      });
    });
  });

  // -------------------------------------------------------------------------
  // Mode switching via toggle
  // -------------------------------------------------------------------------

  describe("search mode toggle in DataView", () => {
    it("should render the search mode toggle in the NlqSearchBar", async () => {
      render(DataView, { props: { flowId: "test-flow-p3-toggle-render" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      // DataView must pass searchMode to NlqSearchBar which renders the toggle
      expect(screen.getByTestId("search-mode-toggle")).toBeInTheDocument();
    });

    it("should update search mode when toggle is clicked", async () => {
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-toggle-update" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.getByTestId("search-mode-toggle");
      expect(toggle).toHaveTextContent(/replace/i);

      await user.click(toggle);

      await waitFor(() => {
        expect(toggle).toHaveTextContent(/merge/i);
      });
    });

    it("should toggle back to replace mode after clicking twice", async () => {
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-toggle-twice" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.getByTestId("search-mode-toggle");

      // First click: replace → merge
      await user.click(toggle);
      await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));

      // Second click: merge → replace
      await user.click(toggle);
      await waitFor(() => expect(toggle).toHaveTextContent(/replace/i));
    });

    it("should use the current search mode when submitting a search", async () => {
      // In merge mode, clearEntities should NOT be called during handleSearch.
      // In replace mode, it should be called.
      mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
      const user = userEvent.setup();

      const { graphStore } = await import("$lib/stores/graphStore.svelte");
      const clearEntitiesSpy = vi.spyOn(graphStore, "clearEntities");

      render(DataView, { props: { flowId: "test-flow-p3-mode-used" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.getByTestId("search-mode-toggle");

      // Switch to merge mode
      await user.click(toggle);
      await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));

      const callsBeforeSearch = clearEntitiesSpy.mock.calls.length;

      await user.type(screen.getByRole("textbox"), "merge search query{Enter}");

      await waitFor(() => {
        expect(mockGlobalSearchFn).toHaveBeenCalled();
        expect(
          screen.queryByTestId("nlq-loading-indicator"),
        ).not.toBeInTheDocument();
      });

      // clearEntities must NOT have been called during merge search
      expect(clearEntitiesSpy.mock.calls.length).toBe(callsBeforeSearch);

      clearEntitiesSpy.mockRestore();
    });
  });

  // -------------------------------------------------------------------------
  // Edge cases
  // -------------------------------------------------------------------------

  describe("edge cases", () => {
    it("should preserve existing data when globalSearch returns empty results in merge mode", async () => {
      // globalSearch returns no entities
      mockGlobalSearchFn.mockResolvedValue(
        makeGlobalSearchResult({ entities: [], count: 0 }),
      );
      const user = userEvent.setup();

      const { graphStore } = await import("$lib/stores/graphStore.svelte");
      const clearEntitiesSpy = vi.spyOn(graphStore, "clearEntities");

      render(DataView, { props: { flowId: "test-flow-p3-empty-merge" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      const callsBeforeSearch = clearEntitiesSpy.mock.calls.length;

      await user.type(screen.getByRole("textbox"), "empty result query{Enter}");

      await waitFor(() => {
        expect(mockGlobalSearchFn).toHaveBeenCalled();
        expect(
          screen.queryByTestId("nlq-loading-indicator"),
        ).not.toBeInTheDocument();
      });

      // clearEntities should NOT have been called in merge mode
      expect(clearEntitiesSpy.mock.calls.length).toBe(callsBeforeSearch);

      // The pathSearch entity (FLEET_ALPHA) should still be in the store
      expect(graphStore.entities.has(FLEET_ALPHA)).toBe(true);

      clearEntitiesSpy.mockRestore();
    });

    it("should preserve existing data when globalSearch fails in merge mode", async () => {
      mockGlobalSearchFn.mockRejectedValueOnce(
        new GraphApiError("Service down", 503),
      );
      const user = userEvent.setup();

      const { graphStore } = await import("$lib/stores/graphStore.svelte");
      const clearEntitiesSpy = vi.spyOn(graphStore, "clearEntities");

      render(DataView, { props: { flowId: "test-flow-p3-error-merge" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      const callsBeforeSearch = clearEntitiesSpy.mock.calls.length;

      await user.type(
        screen.getByRole("textbox"),
        "failing merge query{Enter}",
      );

      await waitFor(() => {
        expect(screen.getByRole("alert")).toBeInTheDocument();
      });

      // clearEntities should NOT have been called in merge mode (even on error)
      expect(clearEntitiesSpy.mock.calls.length).toBe(callsBeforeSearch);

      // The original pathSearch entity should still be present
      expect(graphStore.entities.has(FLEET_ALPHA)).toBe(true);

      clearEntitiesSpy.mockRestore();
    });

    it("should show error alert when globalSearch fails in merge mode (same as replace)", async () => {
      mockGlobalSearchFn.mockRejectedValueOnce(
        new GraphApiError("NLQ unavailable", 503),
      );
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-error-alert" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      await user.type(
        screen.getByRole("textbox"),
        "error in merge mode{Enter}",
      );

      await waitFor(() => {
        expect(screen.getByRole("alert")).toBeInTheDocument();
      });
    });

    it("should NOT enter search mode when globalSearch fails in merge mode", async () => {
      mockGlobalSearchFn.mockRejectedValueOnce(
        new GraphApiError("Backend error", 500),
      );
      const user = userEvent.setup();

      render(DataView, { props: { flowId: "test-flow-p3-no-mode-on-error" } });
      await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

      const toggle = screen.queryByTestId("search-mode-toggle");
      if (toggle) {
        await user.click(toggle);
        await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
      }

      await user.type(
        screen.getByRole("textbox"),
        "will fail merge{Enter}",
      );

      await waitFor(() => {
        expect(screen.getByRole("alert")).toBeInTheDocument();
      });

      // Should NOT be in search mode — no "Back to browse" button
      expect(
        screen.queryByRole("button", { name: /back to browse/i }),
      ).not.toBeInTheDocument();
    });
  });

  // -------------------------------------------------------------------------
  // Table-driven: mode behavior matrix
  // -------------------------------------------------------------------------

  describe("table-driven: replace vs merge behavior on search", () => {
    const modeCases: Array<{
      description: string;
      switchToMerge: boolean;
      expectClearOnSearch: boolean;
    }> = [
      {
        description: "replace mode: clearEntities called before upsertEntities",
        switchToMerge: false,
        expectClearOnSearch: true,
      },
      {
        description:
          "merge mode: clearEntities NOT called, upsertEntities only",
        switchToMerge: true,
        expectClearOnSearch: false,
      },
    ];

    it.each(modeCases)(
      "$description",
      async ({ switchToMerge, expectClearOnSearch }) => {
        mockGlobalSearchFn.mockResolvedValue(makeGlobalSearchResult());
        const user = userEvent.setup();

        const { graphStore } = await import("$lib/stores/graphStore.svelte");
        const clearEntitiesSpy = vi.spyOn(graphStore, "clearEntities");

        render(DataView, {
          props: { flowId: `test-flow-p3-matrix-${switchToMerge}` },
        });
        await waitFor(() => expect(mockPathSearchFn).toHaveBeenCalled());

        if (switchToMerge) {
          const toggle = screen.queryByTestId("search-mode-toggle");
          if (!toggle) {
            clearEntitiesSpy.mockRestore();
            return; // Toggle not yet implemented
          }
          await user.click(toggle);
          await waitFor(() => expect(toggle).toHaveTextContent(/merge/i));
        }

        const callsBeforeSearch = clearEntitiesSpy.mock.calls.length;

        await user.type(
          screen.getByRole("textbox"),
          `matrix test ${switchToMerge}{Enter}`,
        );

        await waitFor(() => {
          expect(mockGlobalSearchFn).toHaveBeenCalled();
          expect(
            screen.queryByTestId("nlq-loading-indicator"),
          ).not.toBeInTheDocument();
        });

        if (expectClearOnSearch) {
          expect(clearEntitiesSpy.mock.calls.length).toBeGreaterThan(
            callsBeforeSearch,
          );
        } else {
          expect(clearEntitiesSpy.mock.calls.length).toBe(callsBeforeSearch);
        }

        clearEntitiesSpy.mockRestore();
      },
    );
  });
});
