// Code generated by Reviewer Agent. DO NOT EDIT.
// Attack tests - permanent CI fixtures.
// These tests verify edge cases and concurrent behavior in health tracking.

package graph

import (
	"runtime"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// TestAttack_ConcurrentHealthTracking verifies that concurrent calls to
// recordDetectionFailure and recordDetectionSuccess are race-free.
// This test MUST pass with -race flag.
func TestAttack_ConcurrentHealthTracking(t *testing.T) {
	// Create mock tracker for testing
	tracker := newMockHealthTracker()

	const goroutines = 100
	var wg sync.WaitGroup

	// Mix of failures and successes happening concurrently
	wg.Add(goroutines * 2)
	for i := 0; i < goroutines; i++ {
		go func() {
			defer wg.Done()
			tracker.recordDetectionFailure()
		}()
		go func() {
			defer wg.Done()
			tracker.recordDetectionSuccess()
		}()
	}

	wg.Wait()

	// We don't know exact final state due to interleaving,
	// but we verify no panics and health is one of valid states
	health := tracker.getHealthStatus()
	require.Contains(t, []string{"healthy", "degraded", "unhealthy"}, health,
		"Health must be valid after concurrent operations")
}

// TestAttack_ConcurrentReadDuringUpdate verifies that reading health status
// while updates are happening doesn't race or panic.
func TestAttack_ConcurrentReadDuringUpdate(t *testing.T) {
	tracker := newMockHealthTracker()

	const readers = 50
	const writers = 50
	var wg sync.WaitGroup

	// Start readers
	wg.Add(readers)
	for i := 0; i < readers; i++ {
		go func() {
			defer wg.Done()
			for j := 0; j < 100; j++ {
				_ = tracker.getHealthStatus()
				_ = tracker.getBackoffDuration()
				_ = tracker.shouldSkipDetection()
				_ = tracker.getConsecutiveFailures()
			}
		}()
	}

	// Start writers
	wg.Add(writers)
	for i := 0; i < writers; i++ {
		go func(idx int) {
			defer wg.Done()
			for j := 0; j < 100; j++ {
				if idx%2 == 0 {
					tracker.recordDetectionFailure()
				} else {
					tracker.recordDetectionSuccess()
				}
			}
		}(i)
	}

	wg.Wait()

	// Verify final state is valid
	health := tracker.getHealthStatus()
	require.Contains(t, []string{"healthy", "degraded", "unhealthy"}, health)
}

// TestAttack_ExtremeFailureCounts verifies that health tracking handles
// extremely large failure counts without overflow or panic.
func TestAttack_ExtremeFailureCounts(t *testing.T) {
	tracker := newMockHealthTracker()

	// Simulate 10,000 consecutive failures
	for i := 0; i < 10000; i++ {
		tracker.recordDetectionFailure()
	}

	// Should be unhealthy
	require.Equal(t, "unhealthy", tracker.getHealthStatus())

	// Backoff should be capped
	backoff := tracker.getBackoffDuration()
	require.Equal(t, 5*time.Minute, backoff, "Backoff should be capped at max")

	// Should still skip detection
	require.True(t, tracker.shouldSkipDetection())

	// Failure count should be accurate (no overflow)
	require.Equal(t, 10000, tracker.getConsecutiveFailures())
}

// TestAttack_RapidStateTransitions verifies that rapidly alternating
// between failure and success doesn't leave inconsistent state.
func TestAttack_RapidStateTransitions(t *testing.T) {
	tracker := newMockHealthTracker()

	// Rapidly alternate: F, S, F, S, F, S...
	for i := 0; i < 1000; i++ {
		if i%2 == 0 {
			tracker.recordDetectionFailure()
		} else {
			tracker.recordDetectionSuccess()
		}
	}

	// Last operation was success (i=999 is odd)
	// So failure count should be 0
	require.Equal(t, 0, tracker.getConsecutiveFailures())

	// Health should be based on consecutive successes
	// Only 1 consecutive success, so:
	// - If previous state was unhealthy, should be degraded
	// - Otherwise should stay as is or be healthy (2+ successes)
	health := tracker.getHealthStatus()
	require.Contains(t, []string{"healthy", "degraded"}, health,
		"After alternating pattern ending in success, should not be unhealthy")
}

// TestAttack_BackoffIntegerOverflow verifies that backoff calculation
// doesn't overflow with extreme failure counts.
func TestAttack_BackoffIntegerOverflow(t *testing.T) {
	tests := []struct {
		name         string
		failures     int
		expectCapped bool
	}{
		{name: "normal_range", failures: 5, expectCapped: false},
		{name: "at_cap", failures: 10, expectCapped: true},
		{name: "beyond_cap", failures: 20, expectCapped: true},
		{name: "extreme", failures: 100, expectCapped: true},
		{name: "ridiculous", failures: 1000, expectCapped: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()
			tracker.consecutiveFailures = tt.failures

			backoff := tracker.getBackoffDuration()

			// Should never exceed max
			require.LessOrEqual(t, backoff, 5*time.Minute,
				"Backoff must not exceed max delay")

			if tt.expectCapped {
				require.Equal(t, 5*time.Minute, backoff,
					"Backoff should be capped at max")
			}

			// Should never be negative
			require.GreaterOrEqual(t, backoff, time.Duration(0),
				"Backoff must not be negative")
		})
	}
}

// TestAttack_ZeroTimeBackoff verifies that zero time is handled correctly
// in backoff checks.
func TestAttack_ZeroTimeBackoff(t *testing.T) {
	tracker := newMockHealthTracker()

	// Initial state: no backoff
	require.False(t, tracker.shouldSkipDetection(),
		"Should not skip with zero time backoff")

	// Record failure (sets backoff in future)
	tracker.recordDetectionFailure()
	require.True(t, tracker.shouldSkipDetection(),
		"Should skip after failure sets backoff")

	// Record success (clears backoff to zero time)
	tracker.recordDetectionSuccess()
	require.False(t, tracker.shouldSkipDetection(),
		"Should not skip after success clears backoff")
}

// TestAttack_TimeEdgeCases verifies behavior at backoff boundary times.
func TestAttack_TimeEdgeCases(t *testing.T) {
	tracker := newMockHealthTracker()

	// Set backoff to exactly now (edge case)
	tracker.lastBackoffUntil = time.Now()

	// Should not skip (time.Now().Before(time.Now()) is false)
	time.Sleep(1 * time.Millisecond) // Ensure time has passed
	require.False(t, tracker.shouldSkipDetection(),
		"Should not skip when backoff time is now or past")

	// Set backoff to 1ms in future
	tracker.lastBackoffUntil = time.Now().Add(1 * time.Millisecond)
	require.True(t, tracker.shouldSkipDetection(),
		"Should skip when backoff is in future")

	// Wait for it to expire
	time.Sleep(2 * time.Millisecond)
	require.False(t, tracker.shouldSkipDetection(),
		"Should not skip after backoff expires")
}

// TestAttack_HealthTransitionInvariants verifies that health state
// transitions always follow the rules, even with concurrent access.
func TestAttack_HealthTransitionInvariants(t *testing.T) {
	tracker := newMockHealthTracker()

	// Invariant: 0-2 failures must be healthy (or empty string before init)
	for i := 0; i < 3; i++ {
		tracker.recordDetectionFailure()
		if tracker.consecutiveFailures < 3 {
			health := tracker.getHealthStatus()
			if health != "" && health != "healthy" {
				t.Errorf("With %d failures, health is %q but should be healthy",
					tracker.consecutiveFailures, health)
			}
		}
	}

	// Invariant: 3-7 failures must be degraded
	for i := 3; i < 8; i++ {
		tracker.recordDetectionFailure()
		if tracker.consecutiveFailures >= 3 && tracker.consecutiveFailures < 8 {
			require.Equal(t, "degraded", tracker.getHealthStatus(),
				"With %d failures, should be degraded", tracker.consecutiveFailures)
		}
	}

	// Invariant: 8+ failures must be unhealthy
	for i := 8; i < 20; i++ {
		tracker.recordDetectionFailure()
		if tracker.consecutiveFailures >= 8 {
			require.Equal(t, "unhealthy", tracker.getHealthStatus(),
				"With %d failures, should be unhealthy", tracker.consecutiveFailures)
		}
	}

	// Invariant: Any success resets failure count
	tracker.recordDetectionSuccess()
	require.Equal(t, 0, tracker.consecutiveFailures,
		"Success must reset failure count")
}

// TestAttack_NoGoroutineLeak verifies that health tracking methods
// don't leak goroutines when called repeatedly.
func TestAttack_NoGoroutineLeak(t *testing.T) {
	before := runtime.NumGoroutine()

	tracker := newMockHealthTracker()

	// Perform many operations
	for i := 0; i < 1000; i++ {
		tracker.recordDetectionFailure()
		tracker.recordDetectionSuccess()
		_ = tracker.getHealthStatus()
		_ = tracker.shouldSkipDetection()
		_ = tracker.getBackoffDuration()
	}

	// Allow any cleanup to happen
	runtime.GC()
	time.Sleep(10 * time.Millisecond)

	after := runtime.NumGoroutine()

	// Should not have leaked goroutines (allow small variance for test framework)
	require.LessOrEqual(t, after, before+2,
		"Goroutine leak detected: %d -> %d", before, after)
}

// TestAttack_ConsistentHealthAfterManyOperations verifies that after
// many operations, health state is consistent with failure/success counts.
func TestAttack_ConsistentHealthAfterManyOperations(t *testing.T) {
	tracker := newMockHealthTracker()

	// Do 100 failures
	for i := 0; i < 100; i++ {
		tracker.recordDetectionFailure()
	}

	// Should be unhealthy
	require.Equal(t, "unhealthy", tracker.getHealthStatus())
	require.Equal(t, 100, tracker.getConsecutiveFailures())
	require.Equal(t, 0, tracker.consecutiveSuccesses)

	// Do 2 successes
	for i := 0; i < 2; i++ {
		tracker.recordDetectionSuccess()
	}

	// Should be healthy (2 consecutive successes)
	require.Equal(t, "healthy", tracker.getHealthStatus())
	require.Equal(t, 0, tracker.consecutiveFailures)
	require.Equal(t, 2, tracker.consecutiveSuccesses)

	// Backoff should be cleared
	require.False(t, tracker.shouldSkipDetection())
}

// TestAttack_BackoffNeverNegative verifies that backoff duration
// is never negative, even with edge case inputs.
func TestAttack_BackoffNeverNegative(t *testing.T) {
	tests := []struct {
		name     string
		failures int
	}{
		{name: "zero", failures: 0},
		{name: "negative_via_direct_set", failures: -1},
		{name: "negative_large", failures: -1000},
		{name: "max_int", failures: 1000000},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()
			tracker.consecutiveFailures = tt.failures

			backoff := tracker.getBackoffDuration()
			require.GreaterOrEqual(t, backoff, time.Duration(0),
				"Backoff must never be negative")
		})
	}
}
