// Code generated by Tester Agent. DO NOT EDIT.
// Task: T042-T045 - Unit tests for health recovery and backoff
// Builder must make these tests pass without modification.

package graph

import (
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// healthTracking is a test interface demonstrating the contract Builder must implement.
// BUILDER: Add these fields to the Processor struct and implement these methods.
type healthTracking interface {
	// recordDetectionFailure increments failure count, resets success count
	recordDetectionFailure()

	// recordDetectionSuccess increments success count, resets failure count
	recordDetectionSuccess()

	// getHealthStatus returns "healthy", "degraded", or "unhealthy"
	getHealthStatus() string

	// getBackoffDuration returns current backoff time based on failure count
	getBackoffDuration() time.Duration

	// shouldSkipDetection returns true if currently in backoff period
	shouldSkipDetection() bool

	// getConsecutiveFailures returns current failure count
	getConsecutiveFailures() int
}

// mockHealthTracker implements the health tracking interface for testing
type mockHealthTracker struct {
	mu                   sync.Mutex
	consecutiveFailures  int
	consecutiveSuccesses int
	currentHealth        string
	lastBackoffUntil     time.Time
	baseDelay            time.Duration
	maxDelay             time.Duration
}

func newMockHealthTracker() *mockHealthTracker {
	return &mockHealthTracker{
		currentHealth: "healthy",
		baseDelay:     1 * time.Second,
		maxDelay:      5 * time.Minute,
	}
}

func (m *mockHealthTracker) recordDetectionFailure() {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.consecutiveFailures++
	m.consecutiveSuccesses = 0

	// Update health based on failure count
	if m.consecutiveFailures >= 8 {
		m.currentHealth = "unhealthy"
	} else if m.consecutiveFailures >= 3 {
		m.currentHealth = "degraded"
	} else {
		// Less than 3 failures means healthy
		m.currentHealth = "healthy"
	}

	// Set backoff
	backoff := m.calculateBackoff()
	if backoff > 0 {
		m.lastBackoffUntil = time.Now().Add(backoff)
	}
}

func (m *mockHealthTracker) recordDetectionSuccess() {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.consecutiveSuccesses++
	m.consecutiveFailures = 0

	// Clear backoff on ANY success (we're no longer in failing state)
	m.lastBackoffUntil = time.Time{}

	// Update health based on success count and current state
	if m.consecutiveSuccesses >= 2 {
		m.currentHealth = "healthy"
	} else if m.consecutiveSuccesses == 1 && m.currentHealth == "unhealthy" {
		// Single success from unhealthy moves to degraded
		m.currentHealth = "degraded"
	}
	// Note: Single success from degraded keeps it degraded (need 2 for healthy)
}

func (m *mockHealthTracker) getHealthStatus() string {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.currentHealth
}

// calculateBackoff is internal and called with lock held.
func (m *mockHealthTracker) calculateBackoff() time.Duration {
	if m.consecutiveFailures <= 0 {
		return 0
	}

	// Cap failures before bit shift to prevent int64 overflow.
	// At 10 failures (2^9 * 1s = 512s), we exceed maxDelay (5min = 300s),
	// so anything above 10 returns maxDelay directly.
	failures := m.consecutiveFailures
	if failures > 10 {
		return m.maxDelay
	}

	// Calculate 2^(failures-1) * baseDelay, capped at maxDelay
	multiplier := int64(1) << (failures - 1)
	backoff := time.Duration(multiplier) * m.baseDelay
	if backoff > m.maxDelay {
		backoff = m.maxDelay
	}
	return backoff
}

func (m *mockHealthTracker) getBackoffDuration() time.Duration {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.calculateBackoff()
}

func (m *mockHealthTracker) shouldSkipDetection() bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	return !m.lastBackoffUntil.IsZero() && m.lastBackoffUntil.After(time.Now())
}

func (m *mockHealthTracker) getConsecutiveFailures() int {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.consecutiveFailures
}

// TestProcessor_HealthTransition_HealthyToDegraded verifies that health status
// transitions from healthy to degraded after exactly 3 consecutive failures.
// Requirement: FR-014, SC-005
func TestProcessor_HealthTransition_HealthyToDegraded(t *testing.T) {
	tests := []struct {
		name           string
		failureCount   int
		expectedHealth string
	}{
		{name: "zero_failures_healthy", failureCount: 0, expectedHealth: "healthy"},
		{name: "one_failure_still_healthy", failureCount: 1, expectedHealth: "healthy"},
		{name: "two_failures_still_healthy", failureCount: 2, expectedHealth: "healthy"},
		{name: "three_failures_degraded", failureCount: 3, expectedHealth: "degraded"},
		{name: "four_failures_stays_degraded", failureCount: 4, expectedHealth: "degraded"},
		{name: "seven_failures_stays_degraded", failureCount: 7, expectedHealth: "degraded"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()

			// Simulate failures
			for i := 0; i < tt.failureCount; i++ {
				tracker.recordDetectionFailure()
			}

			health := tracker.getHealthStatus()
			assert.Equal(t, tt.expectedHealth, health,
				"With %d failures, expected %s but got %s",
				tt.failureCount, tt.expectedHealth, health)
		})
	}
}

// TestProcessor_HealthTransition_DegradedToUnhealthy verifies that health status
// transitions from degraded to unhealthy after 5 MORE failures (8 total).
// Requirement: FR-014
func TestProcessor_HealthTransition_DegradedToUnhealthy(t *testing.T) {
	tests := []struct {
		name           string
		failureCount   int
		expectedHealth string
	}{
		{name: "three_failures_degraded", failureCount: 3, expectedHealth: "degraded"},
		{name: "seven_failures_still_degraded", failureCount: 7, expectedHealth: "degraded"},
		{name: "eight_failures_unhealthy", failureCount: 8, expectedHealth: "unhealthy"},
		{name: "ten_failures_stays_unhealthy", failureCount: 10, expectedHealth: "unhealthy"},
		{name: "hundred_failures_stays_unhealthy", failureCount: 100, expectedHealth: "unhealthy"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()

			for i := 0; i < tt.failureCount; i++ {
				tracker.recordDetectionFailure()
			}

			health := tracker.getHealthStatus()
			assert.Equal(t, tt.expectedHealth, health,
				"With %d consecutive failures, expected %s",
				tt.failureCount, tt.expectedHealth)
		})
	}
}

// TestProcessor_BackoffExponential verifies that backoff duration increases
// exponentially with each failure, capped at 5 minutes.
// Requirement: FR-013, FR-015
func TestProcessor_BackoffExponential(t *testing.T) {
	tests := []struct {
		name            string
		failureCount    int
		expectedBackoff time.Duration
	}{
		{name: "zero_failures_no_backoff", failureCount: 0, expectedBackoff: 0},
		{name: "one_failure_base_delay", failureCount: 1, expectedBackoff: 1 * time.Second},
		{name: "two_failures_doubled", failureCount: 2, expectedBackoff: 2 * time.Second},
		{name: "three_failures_four_seconds", failureCount: 3, expectedBackoff: 4 * time.Second},
		{name: "four_failures_eight_seconds", failureCount: 4, expectedBackoff: 8 * time.Second},
		{name: "five_failures_16_seconds", failureCount: 5, expectedBackoff: 16 * time.Second},
		{name: "six_failures_32_seconds", failureCount: 6, expectedBackoff: 32 * time.Second},
		{name: "seven_failures_64_seconds", failureCount: 7, expectedBackoff: 64 * time.Second},
		{name: "eight_failures_128_seconds", failureCount: 8, expectedBackoff: 128 * time.Second},
		{name: "nine_failures_256_seconds", failureCount: 9, expectedBackoff: 256 * time.Second},
		{name: "ten_failures_capped", failureCount: 10, expectedBackoff: 5 * time.Minute},
		{name: "twenty_failures_still_capped", failureCount: 20, expectedBackoff: 5 * time.Minute},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()
			tracker.consecutiveFailures = tt.failureCount

			backoff := tracker.getBackoffDuration()
			assert.Equal(t, tt.expectedBackoff, backoff,
				"Backoff for %d failures: expected %v, got %v",
				tt.failureCount, tt.expectedBackoff, backoff)
		})
	}
}

// TestProcessor_BackoffRespectsDuration verifies that detection is skipped
// during backoff period.
// Requirement: FR-013
func TestProcessor_BackoffRespectsDuration(t *testing.T) {
	tests := []struct {
		name         string
		backoffUntil time.Time
		shouldSkip   bool
	}{
		{
			name:         "no_backoff_zero_time",
			backoffUntil: time.Time{},
			shouldSkip:   false,
		},
		{
			name:         "backoff_expired",
			backoffUntil: time.Now().Add(-1 * time.Minute),
			shouldSkip:   false,
		},
		{
			name:         "backoff_active",
			backoffUntil: time.Now().Add(1 * time.Minute),
			shouldSkip:   true,
		},
		{
			name:         "backoff_just_expired",
			backoffUntil: time.Now().Add(-1 * time.Millisecond),
			shouldSkip:   false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()
			tracker.lastBackoffUntil = tt.backoffUntil

			shouldSkip := tracker.shouldSkipDetection()
			assert.Equal(t, tt.shouldSkip, shouldSkip,
				"shouldSkipDetection with backoffUntil=%v", tt.backoffUntil)
		})
	}
}

// TestProcessor_HealthRecovery verifies that health recovers after consecutive successes.
// Requirement: FR-014, SC-006
func TestProcessor_HealthRecovery(t *testing.T) {
	tests := []struct {
		name             string
		initialFailures  int
		successCount     int
		expectedHealth   string
		expectedFailures int
	}{
		{
			name:             "healthy_one_success_stays_healthy",
			initialFailures:  0,
			successCount:     1,
			expectedHealth:   "healthy",
			expectedFailures: 0,
		},
		{
			name:             "degraded_one_success_still_degraded",
			initialFailures:  3,
			successCount:     1,
			expectedHealth:   "degraded",
			expectedFailures: 0,
		},
		{
			name:             "degraded_two_successes_recovers",
			initialFailures:  3,
			successCount:     2,
			expectedHealth:   "healthy",
			expectedFailures: 0,
		},
		{
			name:             "degraded_high_count_two_successes",
			initialFailures:  7,
			successCount:     2,
			expectedHealth:   "healthy",
			expectedFailures: 0,
		},
		{
			name:             "unhealthy_one_success_to_degraded",
			initialFailures:  8,
			successCount:     1,
			expectedHealth:   "degraded",
			expectedFailures: 0,
		},
		{
			name:             "unhealthy_two_successes_to_healthy",
			initialFailures:  10,
			successCount:     2,
			expectedHealth:   "healthy",
			expectedFailures: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()

			// Set up initial failure state
			for i := 0; i < tt.initialFailures; i++ {
				tracker.recordDetectionFailure()
			}

			// Record successes
			for i := 0; i < tt.successCount; i++ {
				tracker.recordDetectionSuccess()
			}

			assert.Equal(t, tt.expectedHealth, tracker.getHealthStatus(),
				"Health status after %d failures + %d successes",
				tt.initialFailures, tt.successCount)
			assert.Equal(t, tt.expectedFailures, tracker.getConsecutiveFailures(),
				"Failure count should reset to 0 on success")
		})
	}
}

// TestProcessor_HealthRecovery_InterruptedByFailure verifies that recovery
// requires CONSECUTIVE successes - a single failure resets the recovery count.
// Requirement: FR-014
func TestProcessor_HealthRecovery_InterruptedByFailure(t *testing.T) {
	tests := []struct {
		name             string
		initialFailures  int
		events           []string // "S" = success, "F" = failure
		expectedHealth   string
		expectedFailures int
	}{
		{
			name:             "degraded_success_failure_resets",
			initialFailures:  3,
			events:           []string{"S", "F"},
			expectedHealth:   "healthy",
			expectedFailures: 1,
		},
		{
			name:             "degraded_success_failure_success_still_degraded",
			initialFailures:  3,
			events:           []string{"S", "F", "S"},
			expectedHealth:   "healthy",
			expectedFailures: 0,
		},
		{
			name:             "degraded_success_failure_success_success_healthy",
			initialFailures:  3,
			events:           []string{"S", "F", "S", "S"},
			expectedHealth:   "healthy",
			expectedFailures: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()

			// Set up initial failures
			for i := 0; i < tt.initialFailures; i++ {
				tracker.recordDetectionFailure()
			}

			// Process events
			for _, event := range tt.events {
				if event == "S" {
					tracker.recordDetectionSuccess()
				} else {
					tracker.recordDetectionFailure()
				}
			}

			assert.Equal(t, tt.expectedHealth, tracker.getHealthStatus(),
				"Health after events: %v", tt.events)
			assert.Equal(t, tt.expectedFailures, tracker.getConsecutiveFailures(),
				"Failure count after events: %v", tt.events)
		})
	}
}

// TestProcessor_ConsecutiveFailures_TrackedInDebugStatus verifies that
// ClusteringStatus.ConsecutiveFailures reflects current failure count.
// Requirement: FR-010, FR-014
func TestProcessor_ConsecutiveFailures_TrackedInDebugStatus(t *testing.T) {
	tests := []struct {
		name  string
		count int
	}{
		{name: "zero", count: 0},
		{name: "one", count: 1},
		{name: "three", count: 3},
		{name: "eight", count: 8},
		{name: "hundred", count: 100},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			status := ClusteringStatus{
				ConsecutiveFailures: tt.count,
			}

			assert.Equal(t, tt.count, status.ConsecutiveFailures,
				"ConsecutiveFailures field should be %d", tt.count)
		})
	}
}

// TestProcessor_HealthStatus_ReflectedInDebugStatus verifies that
// ClusteringStatus.HealthStatus reflects current health.
// Requirement: FR-010, FR-014
func TestProcessor_HealthStatus_ReflectedInDebugStatus(t *testing.T) {
	tests := []struct {
		name           string
		failures       int
		expectedHealth string
	}{
		{name: "healthy_zero", failures: 0, expectedHealth: "healthy"},
		{name: "healthy_two", failures: 2, expectedHealth: "healthy"},
		{name: "degraded_three", failures: 3, expectedHealth: "degraded"},
		{name: "degraded_seven", failures: 7, expectedHealth: "degraded"},
		{name: "unhealthy_eight", failures: 8, expectedHealth: "unhealthy"},
		{name: "unhealthy_many", failures: 50, expectedHealth: "unhealthy"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()

			// Simulate failures to reach the target state
			for i := 0; i < tt.failures; i++ {
				tracker.recordDetectionFailure()
			}

			status := ClusteringStatus{
				ConsecutiveFailures: tt.failures,
				HealthStatus:        tracker.getHealthStatus(),
			}

			assert.Equal(t, tt.expectedHealth, status.HealthStatus,
				"HealthStatus for %d failures", tt.failures)
		})
	}
}

// TestProcessor_BackoffReset_OnRecovery verifies that backoff state is cleared
// when health recovers.
// Requirement: FR-013, FR-014
func TestProcessor_BackoffReset_OnRecovery(t *testing.T) {
	tests := []struct {
		name             string
		initialFailures  int
		successCount     int
		expectBackoffSet bool
	}{
		{
			name:             "no_backoff_initially",
			initialFailures:  0,
			successCount:     2,
			expectBackoffSet: false,
		},
		{
			name:             "backoff_one_success_keeps",
			initialFailures:  5,
			successCount:     1,
			expectBackoffSet: false, // Success resets, no new backoff
		},
		{
			name:             "backoff_two_successes_clears",
			initialFailures:  5,
			successCount:     2,
			expectBackoffSet: false, // Full recovery clears backoff
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()

			// Set up failures (will set backoff)
			for i := 0; i < tt.initialFailures; i++ {
				tracker.recordDetectionFailure()
			}

			// Record successes
			for i := 0; i < tt.successCount; i++ {
				tracker.recordDetectionSuccess()
			}

			// Check backoff state
			if tt.expectBackoffSet {
				require.False(t, tracker.lastBackoffUntil.IsZero(),
					"Backoff should be set")
			} else {
				require.True(t, tracker.lastBackoffUntil.IsZero() || tracker.lastBackoffUntil.Before(time.Now()),
					"Backoff should be cleared or expired")
			}
		})
	}
}

// TestProcessor_SingleFailureNoChange verifies that 1-2 failures don't
// trigger health degradation.
// Requirement: FR-014
func TestProcessor_SingleFailureNoChange(t *testing.T) {
	tracker := newMockHealthTracker()

	// One failure
	tracker.recordDetectionFailure()
	assert.Equal(t, "healthy", tracker.getHealthStatus(),
		"One failure should keep status healthy")

	// Two failures
	tracker.recordDetectionFailure()
	assert.Equal(t, "healthy", tracker.getHealthStatus(),
		"Two failures should keep status healthy")

	// Third failure triggers degraded
	tracker.recordDetectionFailure()
	assert.Equal(t, "degraded", tracker.getHealthStatus(),
		"Three failures should trigger degraded")
}

// TestProcessor_SingleSuccessNoFullRecovery verifies that one success reduces
// failure count but doesn't restore healthy from degraded.
// Requirement: FR-014
func TestProcessor_SingleSuccessNoFullRecovery(t *testing.T) {
	tests := []struct {
		name            string
		initialFailures int
		expectedAfter   string
	}{
		{
			name:            "degraded_one_success_stays_degraded",
			initialFailures: 5,
			expectedAfter:   "degraded",
		},
		{
			name:            "unhealthy_one_success_to_degraded",
			initialFailures: 10,
			expectedAfter:   "degraded",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tracker := newMockHealthTracker()

			for i := 0; i < tt.initialFailures; i++ {
				tracker.recordDetectionFailure()
			}

			// One success
			tracker.recordDetectionSuccess()

			assert.Equal(t, tt.expectedAfter, tracker.getHealthStatus(),
				"After %d failures + 1 success", tt.initialFailures)
			assert.Equal(t, 0, tracker.getConsecutiveFailures(),
				"Success should reset failure count")
		})
	}
}
