package component

import (
	"encoding/json"
	"testing"
)

// TestPropertySchemaCategorySerialization tests Category field JSON marshaling (T010)
// Given: PropertySchema with Category="basic"
// When: JSON marshal/unmarshal
// Then: Category preserved, omitempty works when empty
func TestPropertySchemaCategorySerialization(t *testing.T) {
	testCases := []struct {
		name     string
		schema   PropertySchema
		expected string
	}{
		{
			name: "Category basic",
			schema: PropertySchema{
				Type:        "string",
				Description: "Test field",
				Category:    "basic",
			},
			expected: `{"type":"string","description":"Test field","category":"basic"}`,
		},
		{
			name: "Category advanced",
			schema: PropertySchema{
				Type:        "int",
				Description: "Advanced field",
				Category:    "advanced",
			},
			expected: `{"type":"int","description":"Advanced field","category":"advanced"}`,
		},
		{
			name: "Category empty (omitempty)",
			schema: PropertySchema{
				Type:        "bool",
				Description: "No category",
				Category:    "",
			},
			// Should not include category field when empty
			expected: `{"type":"bool","description":"No category"}`,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Marshal to JSON
			jsonData, err := json.Marshal(tc.schema)
			if err != nil {
				t.Fatalf("Failed to marshal: %v", err)
			}

			// Verify JSON output
			if string(jsonData) != tc.expected {
				t.Errorf("Expected JSON:\n%s\nGot:\n%s", tc.expected, string(jsonData))
			}

			// Unmarshal back
			var unmarshaled PropertySchema
			if err := json.Unmarshal(jsonData, &unmarshaled); err != nil {
				t.Fatalf("Failed to unmarshal: %v", err)
			}

			// Verify Category preserved
			if unmarshaled.Category != tc.schema.Category {
				t.Errorf("Expected Category %q, got %q", tc.schema.Category, unmarshaled.Category)
			}
		})
	}
}

// TestPropertySchemaBackwardCompatibility tests omitempty ensures backward compatibility (T010)
// Given: JSON without Category field (old format)
// When: Unmarshal into PropertySchema
// Then: No error, Category empty string
func TestPropertySchemaBackwardCompatibility(t *testing.T) {
	// Old JSON format without Category field
	oldJSON := `{"type":"string","description":"Legacy field","default":"value"}`

	var schema PropertySchema
	if err := json.Unmarshal([]byte(oldJSON), &schema); err != nil {
		t.Fatalf("Failed to unmarshal old format: %v", err)
	}

	// Should have empty Category, not cause errors
	if schema.Category != "" {
		t.Errorf("Expected empty Category for old format, got %q", schema.Category)
	}

	// Other fields should be present
	if schema.Type != "string" {
		t.Errorf("Expected Type string, got %q", schema.Type)
	}

	if schema.Description != "Legacy field" {
		t.Errorf("Expected Description 'Legacy field', got %q", schema.Description)
	}
}

// =============================================================================
// DebugStatusProvider Interface Tests
// Code generated by Tester Agent. DO NOT EDIT.
// Task: 001-fix-async-coordination - Debug API
// Builder must make these tests pass without modification.
// =============================================================================

// TestDebugStatusProvider_InterfaceDefinition verifies the DebugStatusProvider
// interface is correctly defined and can be type-asserted
func TestDebugStatusProvider_InterfaceDefinition(t *testing.T) {
	t.Run("interface is defined", func(t *testing.T) {
		// This test verifies DebugStatusProvider interface exists
		// by attempting to use it in a type assertion
		var iface interface{} = (*DebugStatusProvider)(nil)
		if iface == nil {
			t.Fatal("DebugStatusProvider interface should exist")
		}
	})

	t.Run("has DebugStatus method", func(t *testing.T) {
		// This test ensures the interface has the correct method signature
		// If the signature is wrong, this won't compile
		var provider DebugStatusProvider
		if provider != nil {
			_ = provider.DebugStatus() // Should return any
		}
	})
}

// TestDebugStatusProvider_TypeAssertion verifies that components can be
// checked for DebugStatusProvider implementation at runtime
func TestDebugStatusProvider_TypeAssertion(t *testing.T) {
	tests := []struct {
		name            string
		component       interface{}
		shouldImplement bool
	}{
		{
			name:            "nil component",
			component:       nil,
			shouldImplement: false,
		},
		{
			name:            "non-component interface",
			component:       struct{}{},
			shouldImplement: false,
		},
		{
			name:            "mock implementing DebugStatusProvider",
			component:       &mockDebugProvider{},
			shouldImplement: true,
		},
		{
			name:            "mock not implementing DebugStatusProvider",
			component:       &mockNonDebugProvider{},
			shouldImplement: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, ok := tt.component.(DebugStatusProvider)
			if ok != tt.shouldImplement {
				t.Errorf("Type assertion result %v, expected %v", ok, tt.shouldImplement)
			}
		})
	}
}

// TestDebugStatusProvider_ReturnValue verifies DebugStatus returns
// JSON-serializable data
func TestDebugStatusProvider_ReturnValue(t *testing.T) {
	t.Run("returns any type", func(t *testing.T) {
		provider := &mockDebugProvider{
			status: map[string]interface{}{
				"key": "value",
			},
		}

		result := provider.DebugStatus()
		if result == nil {
			t.Fatal("DebugStatus should return non-nil value")
		}

		// Verify the result is the expected type
		resultMap, ok := result.(map[string]interface{})
		if !ok {
			t.Fatal("Result should be map[string]interface{}")
		}
		if resultMap["key"] != "value" {
			t.Errorf("Expected 'value', got %v", resultMap["key"])
		}
	})

	t.Run("supports various return types", func(t *testing.T) {
		testCases := []struct {
			name   string
			status interface{}
		}{
			{
				name:   "map",
				status: map[string]string{"test": "data"},
			},
			{
				name:   "struct",
				status: struct{ Field string }{Field: "value"},
			},
			{
				name:   "slice",
				status: []string{"a", "b", "c"},
			},
		}

		for _, tc := range testCases {
			t.Run(tc.name, func(t *testing.T) {
				provider := &mockDebugProvider{status: tc.status}
				result := provider.DebugStatus()
				if result == nil {
					t.Error("DebugStatus should return non-nil value")
				}
			})
		}
	})
}

// Mock implementations for DebugStatusProvider testing

type mockDebugProvider struct {
	status interface{}
}

func (m *mockDebugProvider) DebugStatus() interface{} {
	if m.status == nil {
		return map[string]interface{}{}
	}
	return m.status
}

type mockNonDebugProvider struct{}
