// Code generated by Tester Agent. DO NOT EDIT.
// Task: Phase 2 - Query Infrastructure
// Builder must make these tests pass without modification.

package component

import (
	"encoding/json"
	"testing"
)

// =============================================================================
// QueryCapabilityProvider Interface Tests
// =============================================================================

// TestQueryCapabilityProvider_InterfaceDefinition verifies the QueryCapabilityProvider
// interface is correctly defined and can be type-asserted
func TestQueryCapabilityProvider_InterfaceDefinition(t *testing.T) {
	t.Run("interface is defined", func(t *testing.T) {
		// This test verifies QueryCapabilityProvider interface exists
		// by attempting to use it in a type assertion
		var iface interface{} = (*QueryCapabilityProvider)(nil)
		if iface == nil {
			t.Fatal("QueryCapabilityProvider interface should exist")
		}
	})

	t.Run("has QueryCapabilities method", func(t *testing.T) {
		// This test ensures the interface has the correct method signature
		// If the signature is wrong, this won't compile
		var provider QueryCapabilityProvider
		if provider != nil {
			_ = provider.QueryCapabilities() // Should return QueryCapabilities
		}
	})
}

// TestQueryCapabilityProvider_TypeAssertion verifies that components can be
// checked for QueryCapabilityProvider implementation at runtime
func TestQueryCapabilityProvider_TypeAssertion(t *testing.T) {
	tests := []struct {
		name            string
		component       interface{}
		shouldImplement bool
	}{
		{
			name:            "nil component",
			component:       nil,
			shouldImplement: false,
		},
		{
			name:            "non-component interface",
			component:       struct{}{},
			shouldImplement: false,
		},
		{
			name:            "mock implementing QueryCapabilityProvider",
			component:       &mockQueryProvider{},
			shouldImplement: true,
		},
		{
			name:            "mock not implementing QueryCapabilityProvider",
			component:       &mockNonQueryProvider{},
			shouldImplement: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, ok := tt.component.(QueryCapabilityProvider)
			if ok != tt.shouldImplement {
				t.Errorf("Type assertion result %v, expected %v", ok, tt.shouldImplement)
			}
		})
	}
}

// =============================================================================
// QueryCapabilities Struct Tests
// =============================================================================

// TestQueryCapabilities_JSONSerialization tests that QueryCapabilities
// can be marshaled and unmarshaled correctly
func TestQueryCapabilities_JSONSerialization(t *testing.T) {
	tests := []struct {
		name     string
		input    QueryCapabilities
		validate func(t *testing.T, result QueryCapabilities)
	}{
		{
			name: "complete capabilities",
			input: QueryCapabilities{
				Component: "graph-ingest",
				Version:   "1.0.0",
				Queries: []QueryCapability{
					{
						Subject:        "graph.ingest.query.entity",
						Operation:      "getEntity",
						Description:    "Get entity by ID",
						RequestSchema:  map[string]any{"type": "object"},
						ResponseSchema: map[string]any{"type": "object"},
					},
				},
				Definitions: map[string]any{
					"EntityState": map[string]any{"type": "object"},
				},
			},
			validate: func(t *testing.T, result QueryCapabilities) {
				if result.Component != "graph-ingest" {
					t.Errorf("Expected component 'graph-ingest', got '%s'", result.Component)
				}
				if result.Version != "1.0.0" {
					t.Errorf("Expected version '1.0.0', got '%s'", result.Version)
				}
				if len(result.Queries) != 1 {
					t.Fatalf("Expected 1 query, got %d", len(result.Queries))
				}
				if result.Queries[0].Subject != "graph.ingest.query.entity" {
					t.Errorf("Expected subject 'graph.ingest.query.entity', got '%s'", result.Queries[0].Subject)
				}
				if len(result.Definitions) != 1 {
					t.Errorf("Expected 1 definition, got %d", len(result.Definitions))
				}
			},
		},
		{
			name: "minimal capabilities without definitions",
			input: QueryCapabilities{
				Component: "graph-index",
				Version:   "2.0.0",
				Queries: []QueryCapability{
					{
						Subject:        "graph.index.query.outgoing",
						Operation:      "getOutgoing",
						RequestSchema:  map[string]any{"type": "object"},
						ResponseSchema: map[string]any{"type": "array"},
					},
				},
				// Definitions is nil/empty - should be omitted in JSON
			},
			validate: func(t *testing.T, result QueryCapabilities) {
				if result.Component != "graph-index" {
					t.Errorf("Expected component 'graph-index', got '%s'", result.Component)
				}
				if result.Version != "2.0.0" {
					t.Errorf("Expected version '2.0.0', got '%s'", result.Version)
				}
				if len(result.Queries) != 1 {
					t.Fatalf("Expected 1 query, got %d", len(result.Queries))
				}
			},
		},
		{
			name: "multiple queries",
			input: QueryCapabilities{
				Component: "graph-query",
				Version:   "1.0.0",
				Queries: []QueryCapability{
					{
						Subject:        "graph.query.pathSearch",
						Operation:      "pathSearch",
						Description:    "PathRAG traversal",
						RequestSchema:  map[string]any{"type": "object"},
						ResponseSchema: map[string]any{"type": "array"},
					},
					{
						Subject:        "graph.query.graphSearch",
						Operation:      "graphSearch",
						Description:    "GraphRAG with communities",
						RequestSchema:  map[string]any{"type": "object"},
						ResponseSchema: map[string]any{"type": "array"},
					},
				},
			},
			validate: func(t *testing.T, result QueryCapabilities) {
				if len(result.Queries) != 2 {
					t.Fatalf("Expected 2 queries, got %d", len(result.Queries))
				}
				if result.Queries[0].Operation != "pathSearch" {
					t.Errorf("Expected first operation 'pathSearch', got '%s'", result.Queries[0].Operation)
				}
				if result.Queries[1].Operation != "graphSearch" {
					t.Errorf("Expected second operation 'graphSearch', got '%s'", result.Queries[1].Operation)
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Marshal to JSON
			jsonData, err := json.Marshal(tt.input)
			if err != nil {
				t.Fatalf("Failed to marshal QueryCapabilities: %v", err)
			}

			// Unmarshal back
			var result QueryCapabilities
			if err := json.Unmarshal(jsonData, &result); err != nil {
				t.Fatalf("Failed to unmarshal QueryCapabilities: %v", err)
			}

			// Validate result
			tt.validate(t, result)
		})
	}
}

// TestQueryCapabilities_DefinitionsOmitempty verifies that Definitions field
// is omitted from JSON when empty (omitempty behavior)
func TestQueryCapabilities_DefinitionsOmitempty(t *testing.T) {
	tests := []struct {
		name               string
		capabilities       QueryCapabilities
		shouldHaveDefField bool
	}{
		{
			name: "with definitions",
			capabilities: QueryCapabilities{
				Component: "test",
				Version:   "1.0.0",
				Queries:   []QueryCapability{},
				Definitions: map[string]any{
					"Entity": map[string]any{"type": "object"},
				},
			},
			shouldHaveDefField: true,
		},
		{
			name: "empty definitions map",
			capabilities: QueryCapabilities{
				Component:   "test",
				Version:     "1.0.0",
				Queries:     []QueryCapability{},
				Definitions: map[string]any{},
			},
			shouldHaveDefField: false, // Empty map should be omitted
		},
		{
			name: "nil definitions",
			capabilities: QueryCapabilities{
				Component:   "test",
				Version:     "1.0.0",
				Queries:     []QueryCapability{},
				Definitions: nil,
			},
			shouldHaveDefField: false, // Nil should be omitted
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			jsonData, err := json.Marshal(tt.capabilities)
			if err != nil {
				t.Fatalf("Failed to marshal: %v", err)
			}

			var raw map[string]any
			if err := json.Unmarshal(jsonData, &raw); err != nil {
				t.Fatalf("Failed to unmarshal to map: %v", err)
			}

			_, hasDefinitions := raw["definitions"]
			if hasDefinitions != tt.shouldHaveDefField {
				t.Errorf("Expected definitions field present=%v, got present=%v. JSON: %s",
					tt.shouldHaveDefField, hasDefinitions, string(jsonData))
			}
		})
	}
}

// =============================================================================
// QueryCapability Struct Tests
// =============================================================================

// TestQueryCapability_JSONSerialization tests that QueryCapability
// can be marshaled and unmarshaled correctly
func TestQueryCapability_JSONSerialization(t *testing.T) {
	tests := []struct {
		name     string
		input    QueryCapability
		validate func(t *testing.T, result QueryCapability)
	}{
		{
			name: "complete capability with description",
			input: QueryCapability{
				Subject:        "graph.ingest.query.entity",
				Operation:      "getEntity",
				Description:    "Get entity by ID",
				RequestSchema:  map[string]any{"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string"}}},
				ResponseSchema: map[string]any{"$ref": "#/definitions/EntityState"},
			},
			validate: func(t *testing.T, result QueryCapability) {
				if result.Subject != "graph.ingest.query.entity" {
					t.Errorf("Expected subject 'graph.ingest.query.entity', got '%s'", result.Subject)
				}
				if result.Operation != "getEntity" {
					t.Errorf("Expected operation 'getEntity', got '%s'", result.Operation)
				}
				if result.Description != "Get entity by ID" {
					t.Errorf("Expected description 'Get entity by ID', got '%s'", result.Description)
				}
				if result.RequestSchema == nil {
					t.Error("Expected non-nil RequestSchema")
				}
				if result.ResponseSchema == nil {
					t.Error("Expected non-nil ResponseSchema")
				}
			},
		},
		{
			name: "minimal capability without description",
			input: QueryCapability{
				Subject:        "graph.index.query.outgoing",
				Operation:      "getOutgoing",
				Description:    "", // Empty description
				RequestSchema:  map[string]any{"type": "object"},
				ResponseSchema: map[string]any{"type": "array"},
			},
			validate: func(t *testing.T, result QueryCapability) {
				if result.Subject != "graph.index.query.outgoing" {
					t.Errorf("Expected subject 'graph.index.query.outgoing', got '%s'", result.Subject)
				}
				if result.Operation != "getOutgoing" {
					t.Errorf("Expected operation 'getOutgoing', got '%s'", result.Operation)
				}
				// Description can be empty string
			},
		},
		{
			name: "capability with complex schemas",
			input: QueryCapability{
				Subject:   "graph.query.pathSearch",
				Operation: "pathSearch",
				RequestSchema: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"startEntity": map[string]any{"type": "string"},
						"maxDepth":    map[string]any{"type": "integer"},
					},
					"required": []string{"startEntity"},
				},
				ResponseSchema: map[string]any{
					"type": "array",
					"items": map[string]any{
						"$ref": "#/definitions/Entity",
					},
				},
			},
			validate: func(t *testing.T, result QueryCapability) {
				// Verify complex nested structures survive round-trip
				reqSchema, ok := result.RequestSchema.(map[string]any)
				if !ok {
					t.Fatal("RequestSchema should be map[string]any")
				}
				if reqSchema["type"] != "object" {
					t.Errorf("Expected RequestSchema type 'object', got '%v'", reqSchema["type"])
				}

				respSchema, ok := result.ResponseSchema.(map[string]any)
				if !ok {
					t.Fatal("ResponseSchema should be map[string]any")
				}
				if respSchema["type"] != "array" {
					t.Errorf("Expected ResponseSchema type 'array', got '%v'", respSchema["type"])
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Marshal to JSON
			jsonData, err := json.Marshal(tt.input)
			if err != nil {
				t.Fatalf("Failed to marshal QueryCapability: %v", err)
			}

			// Unmarshal back
			var result QueryCapability
			if err := json.Unmarshal(jsonData, &result); err != nil {
				t.Fatalf("Failed to unmarshal QueryCapability: %v", err)
			}

			// Validate result
			tt.validate(t, result)
		})
	}
}

// TestQueryCapability_DescriptionOmitempty verifies that Description field
// is omitted from JSON when empty (omitempty behavior)
func TestQueryCapability_DescriptionOmitempty(t *testing.T) {
	tests := []struct {
		name                string
		capability          QueryCapability
		shouldHaveDescField bool
	}{
		{
			name: "with description",
			capability: QueryCapability{
				Subject:        "test.subject",
				Operation:      "testOp",
				Description:    "Test description",
				RequestSchema:  map[string]any{},
				ResponseSchema: map[string]any{},
			},
			shouldHaveDescField: true,
		},
		{
			name: "empty description",
			capability: QueryCapability{
				Subject:        "test.subject",
				Operation:      "testOp",
				Description:    "",
				RequestSchema:  map[string]any{},
				ResponseSchema: map[string]any{},
			},
			shouldHaveDescField: false, // Empty string should be omitted
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			jsonData, err := json.Marshal(tt.capability)
			if err != nil {
				t.Fatalf("Failed to marshal: %v", err)
			}

			var raw map[string]any
			if err := json.Unmarshal(jsonData, &raw); err != nil {
				t.Fatalf("Failed to unmarshal to map: %v", err)
			}

			_, hasDescription := raw["description"]
			if hasDescription != tt.shouldHaveDescField {
				t.Errorf("Expected description field present=%v, got present=%v. JSON: %s",
					tt.shouldHaveDescField, hasDescription, string(jsonData))
			}
		})
	}
}

// =============================================================================
// Integration Tests - Real Usage Patterns
// =============================================================================

// TestQueryCapabilityProvider_RealUsagePattern tests that a component can
// implement QueryCapabilityProvider and return valid capabilities
func TestQueryCapabilityProvider_RealUsagePattern(t *testing.T) {
	// Simulate a real component implementing the interface
	component := &mockQueryProvider{
		component: "graph-ingest",
		version:   "1.0.0",
		queries: []QueryCapability{
			{
				Subject:        "graph.ingest.query.entity",
				Operation:      "getEntity",
				Description:    "Get single entity by ID",
				RequestSchema:  map[string]any{"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string"}}},
				ResponseSchema: map[string]any{"$ref": "#/definitions/EntityState"},
			},
			{
				Subject:        "graph.ingest.query.batch",
				Operation:      "getBatch",
				Description:    "Get multiple entities by IDs",
				RequestSchema:  map[string]any{"type": "object", "properties": map[string]any{"ids": map[string]any{"type": "array"}}},
				ResponseSchema: map[string]any{"type": "array"},
			},
		},
		definitions: map[string]any{
			"EntityState": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"entityID": map[string]any{"type": "string"},
					"triples":  map[string]any{"type": "array"},
				},
			},
		},
	}

	// Type assertion to QueryCapabilityProvider
	provider, ok := interface{}(component).(QueryCapabilityProvider)
	if !ok {
		t.Fatal("mockQueryProvider should implement QueryCapabilityProvider")
	}

	// Get capabilities
	capabilities := provider.QueryCapabilities()

	// Verify structure
	if capabilities.Component != "graph-ingest" {
		t.Errorf("Expected component 'graph-ingest', got '%s'", capabilities.Component)
	}
	if capabilities.Version != "1.0.0" {
		t.Errorf("Expected version '1.0.0', got '%s'", capabilities.Version)
	}
	if len(capabilities.Queries) != 2 {
		t.Fatalf("Expected 2 queries, got %d", len(capabilities.Queries))
	}

	// Verify first query
	q1 := capabilities.Queries[0]
	if q1.Subject != "graph.ingest.query.entity" {
		t.Errorf("Expected subject 'graph.ingest.query.entity', got '%s'", q1.Subject)
	}
	if q1.Operation != "getEntity" {
		t.Errorf("Expected operation 'getEntity', got '%s'", q1.Operation)
	}

	// Verify second query
	q2 := capabilities.Queries[1]
	if q2.Subject != "graph.ingest.query.batch" {
		t.Errorf("Expected subject 'graph.ingest.query.batch', got '%s'", q2.Subject)
	}

	// Verify definitions
	if len(capabilities.Definitions) != 1 {
		t.Errorf("Expected 1 definition, got %d", len(capabilities.Definitions))
	}

	// Verify JSON serialization of full response
	jsonData, err := json.Marshal(capabilities)
	if err != nil {
		t.Fatalf("Failed to marshal capabilities: %v", err)
	}

	var unmarshaled QueryCapabilities
	if err := json.Unmarshal(jsonData, &unmarshaled); err != nil {
		t.Fatalf("Failed to unmarshal capabilities: %v", err)
	}

	if unmarshaled.Component != capabilities.Component {
		t.Errorf("Component mismatch after JSON round-trip")
	}
	if len(unmarshaled.Queries) != len(capabilities.Queries) {
		t.Errorf("Queries count mismatch after JSON round-trip")
	}
}

// TestQueryCapabilityProvider_DiscoveryPattern tests the discovery pattern
// where a coordinator can type-assert and discover capabilities
func TestQueryCapabilityProvider_DiscoveryPattern(t *testing.T) {
	// Simulate multiple components, some with query capabilities, some without
	components := []interface{}{
		&mockQueryProvider{
			component: "graph-ingest",
			version:   "1.0.0",
			queries: []QueryCapability{
				{
					Subject:        "graph.ingest.query.entity",
					Operation:      "getEntity",
					RequestSchema:  map[string]any{},
					ResponseSchema: map[string]any{},
				},
			},
		},
		&mockNonQueryProvider{}, // Doesn't implement QueryCapabilityProvider
		&mockQueryProvider{
			component: "graph-index",
			version:   "1.0.0",
			queries: []QueryCapability{
				{
					Subject:        "graph.index.query.outgoing",
					Operation:      "getOutgoing",
					RequestSchema:  map[string]any{},
					ResponseSchema: map[string]any{},
				},
			},
		},
	}

	// Discovery logic (what graph-query coordinator would do)
	var discoveredCapabilities []QueryCapabilities
	for _, comp := range components {
		if provider, ok := comp.(QueryCapabilityProvider); ok {
			caps := provider.QueryCapabilities()
			discoveredCapabilities = append(discoveredCapabilities, caps)
		}
	}

	// Should discover 2 components with query capabilities
	if len(discoveredCapabilities) != 2 {
		t.Fatalf("Expected to discover 2 components with query capabilities, got %d", len(discoveredCapabilities))
	}

	// Verify discovered components
	if discoveredCapabilities[0].Component != "graph-ingest" {
		t.Errorf("Expected first discovered component 'graph-ingest', got '%s'", discoveredCapabilities[0].Component)
	}
	if discoveredCapabilities[1].Component != "graph-index" {
		t.Errorf("Expected second discovered component 'graph-index', got '%s'", discoveredCapabilities[1].Component)
	}
}

// =============================================================================
// Mock Implementations for Testing
// =============================================================================

// mockQueryProvider implements QueryCapabilityProvider for testing
type mockQueryProvider struct {
	component   string
	version     string
	queries     []QueryCapability
	definitions map[string]any
}

func (m *mockQueryProvider) QueryCapabilities() QueryCapabilities {
	return QueryCapabilities{
		Component:   m.component,
		Version:     m.version,
		Queries:     m.queries,
		Definitions: m.definitions,
	}
}

// mockNonQueryProvider does not implement QueryCapabilityProvider
type mockNonQueryProvider struct{}
